### ISSUE TITLE
Fedora 27 pip3 install fails

### ISSUE THREAD

**Issue by buskjan** [autokey/autokey#123]
## Classification:

Bug

## Reproducibility:

Always

## Summary
pip3 install --user git+https://github.com/autokey-py3/autokey fails with error

Summary of the problem.

## Steps to Reproduce
pip3 install --user git+https://github.com/autokey-py3/autokey

## Expected Results

- This should happen.
Autokey installs without problems

## Actual Results

- Instead, this happens. :(
      File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-gm5mgwt5/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-build-gm5mgwt5/dbus-python/build/temp.linux-x86_64-3.6/prefix']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gm5mgwt5/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-hzj_drlm-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-gm5mgwt5/dbus-python/

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

AutoKey-Py3 version ???
Installed via pip link according to instructions on githup page. So the version should be the latest. Could not se the version on github page and since autokey isn't starting....

Installed via: pip3 install --user git+https://github.com/autokey-py3/autokey

Distro:
Fedora 27

**Comment by buskjan** [comment]
Installed via pip link according to instructions on githup page. So the version should be the latest. Could not se the version on github page and since autokey isn't starting....

Installed via: pip3 install --user git+https://github.com/autokey-py3/autokey

**Comment by private-lock** [comment]
Failed building wheel for dbus-python
otherwise same error in Kubuntu 17.10

[autokey-install-output.txt](https://github.com/autokey/autokey/files/1876790/autokey-install-output.txt)

**Comment by luziferius** [comment]
AutoKey uses DBus for some interprocess communication tasks. The Python DBus implementation uses C bindings to use the system libdbus.

When you install AutoKey using pip3, it will try to install all dependencies from PyPi, including `python-dbus`. This, in turn, will compile the C code part of that module, which requires (among other things) the dbus development headers to be present on your system.

In short: Your system misses non-Python dependencies that pip3 cannot fulfil, so make sure that `dbus-python` is installed using your package management to avoid this. (Or alternatively, install all dependencies so that pip3 can compile the dbus module.)

If you launch `python3` and can successfully `import dbus.mainloop.glib`, it should be solved.

(Personally, I never used Fedora, so I’m not 100% sure.) I looked around the Fedora repository and found this https://apps.fedoraproject.org/packages/python3-dbus, which looks about right. So if you install `python3-dbus` from the Fedora repositories, autokey should install fine.

**Comment by buskjan** [comment]
Tnx for coming back to me!
Python3-dbus is installed and I can import the lib in python3. Still same error when installing.
Installed version is: python3-dbus-1.2.4-13.fc28.x86_64
Is this the correct version of dbus?

**Comment by luziferius** [comment]
This _looks like_ being the right package. You said you can import the package in the python3 prompt, so Python does find it.

Hmmm. The error message says that it executes `/tmp/pip-build-gm5mgwt5/dbus-python/configure`, which means that it tries to compile `dbus-python`, which is the library name on PyPi. If that still happens after you installed python3-dbus, this means that pip3 is unable to detect that the requirement is already installed.
This happened to me, too and I thought that my system is at fault, but it seems to be a problem with pip3. Odd.

Try cloning autokey with git (or download a ZIP), then remove the dependency from the setup.py file.
It is here: https://github.com/autokey/autokey/blob/afc20502b3e07d942eba1116b8fd369a8afd449a/setup.py#L166
Change that to `    install_requires=['pyinotify', 'python3-xlib'],`.

Then install using `pip3 install --user /path/to/your/local/copy`

**Comment by luziferius** [comment]
I have removed the `'dbus-python'` dependency from `setup.py`. It should install now, without trying to compile the dbus bindings.

AutoKey still needs the `dbus` package installed, so you’ll need to manually install https://apps.fedoraproject.org/packages/python3-dbus.
