### ISSUE TITLE
AutoKey and xterm

### ISSUE THREAD

**Issue by johndebord** [autokey/autokey#132]
**System: Ubuntu 16.04**

Here is a simple script.
`keyboard.send_keys("<up>")`
It works perfectly in every other application.
However it does not work in xterm.
Using the `showkey -a` and pressing the key that the script is bound to doesn't spit back anything.
Does anyone know what's going on here?

**Comment by josephj11** [comment]
Usage questions will get more love if posted on our [support list](https://gitter.im/autokey/autokey), or for more technical questions, on [Gitter](https://gitter.im/autokey/autokey).

**Comment by luziferius** [comment]
I can confirm that it works in Konsole, but not in xterm.
Running `xev`, pressing the UP key:
```
KeyPress event, serial 40, synthetic NO, window 0x7e00001,
    root 0xb6, subw 0x0, time 16057911, (56,94), root:(1374,353),
    state 0x0, keycode 111 (keysym 0xff52, Up), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Output when binding AutoKey `keyboard.send_keys("<up>")` to a hotkey and using that:
```
KeyPress event, serial 40, synthetic YES, window 0x7e00001,
    root 0xb6, subw 0x0, time 0, (1,1), root:(1,1),
    state 0x0, keycode 111 (keysym 0xff52, Up), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Note the `synthetic YES` in the output. Maybe xterm ignores all software-created, thus synthetic key presses? Then nothing can be done about it, except by going for some low-level keyboard emulation.
(Emulating a real keyboard by providing an input device in `/dev`.)

**Comment by luziferius** [comment]
@johndebord 
To quote the xterm man page:
```
allowSendEvents (class AllowSendEvents)
    Specifies whether or not synthetic key and button events (generated using the X protocol
    sendEvent request) should be interpreted or discarded. 
    The default is “false” meaning they are discarded.
    Note that allowing such events would create a very large security hole, therefore
    enabling this resource forcefully disables the allowXXXOps resources.
    The default is “false”.
```
In other words: AutoKey does not work with xterm, because of a security feature built into xterm.
A simple security hole would be using AutoKey as your password manager: Xterm prevents you from storing your passwords in Phrases and expand them using abbreviations/hotkeys.

You can disable this feature, (and therefore enable AutoKey usage in xterm), by holding [CTRL]+[Left Mouse Button] to show xterm’s main menu and checking the `allow SendEvents` option.

@troxor I think, this can be closed. Maybe add this as a question to the FAQ in the Wiki?
