### ISSUE TITLE
Autokey installs but won't run on (18.04)

### ISSUE THREAD

**Issue by rickstaa** [autokey/autokey#135]
## Classification:

Bug

## Reproducibility:

- Try to install autokey through ubuntu store
- Try to install autokey with the pip3 setup.py install command
- Try to install autokey with the apt-get autokey-gtk

## Summary

I am trying to install the autokey package on Ubuntu 18.04 and It worked the first time but when I had to remove it I couldn't get it to reinstall again.

## Steps to Reproduce

Remove the program the following way:
- sudo apt-get purge --auto-remove autokey-gtk

Install the program by using one of the following ways;
- sudo apt-get update;
  sudo apt-get autokey-gtk
- pip3 setup.py install;

## Expected Results
When i try to open autokey from terminal or the pacakge explorere I would expect a GUI to open.

## Actual Results
The program won't open the GUI.

## Error While loading
autokey-gtk --version
Traceback (most recent call last):
  File "/usr/local/bin/autokey-gtk", line 11, in <module>
    load_entry_point('autokey==0.94.0', 'console_scripts', 'autokey-gtk')()
  File "/home/ricks/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ricks/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/ricks/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/ricks/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/autokey-0.94.0-py3.6.egg/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/usr/local/lib/python3.6/dist-packages/autokey-0.94.0-py3.6.egg/autokey/gtkapp.py", line 44, in <module>
    from autokey import service, monitor
  File "/usr/local/lib/python3.6/dist-packages/autokey-0.94.0-py3.6.egg/autokey/service.py", line 25, in <module>
    from .iomediator.key import Key
ModuleNotFoundError: No module named 'autokey.iomediator'

## my thoughts
I am new to Linux so I accidentally removed some crucial files when purging the program.

## Version
AutoKey-Py3 version: Latest version
Installed via: (PPA, pip and ubuntu store)
Distro: Ubuntu Bionic beaver (18.04)

**Comment by luziferius** [comment]
Hmmm…

> I am new to Linux so I accidentally removed some crucial files when purging the program.

`sudo apt-get purge --auto-remove autokey-gtk` looks totally fine. (Side note: You could use the newer `apt` instead of `apt-get`, but the quoted command looks ok.)

> When I try to open autokey from terminal or the package explorer I would expect a GUI to open.

(Side note: Even if AutoKey had started, by default it does not open a GUI and just sits in the system tray. To open the GUI supply the `-c` or `--configure` command line switch when starting or right-click on the tray icon and click on `Show Main Window`.)

This backtrace looks like it is from the current git HEAD (the newest development revisions). If you got the (exact) same backtrace from the the version in ubuntu repositories, something is severely broken in the repository, as the package `.iomediator.key` should not exist in the released version 0.94.0. The official ubuntu repository still has version 0.90.
I assume you did: Clicked on the green `Clone or download` button on Github, then downloaded the zip archive, and then ran the command you listed on the extracted zip. Right?


I tried to reproduce this bug, but could not. On my system the GTK version works as expected.
It seems there is some installation problem

1. Uninstall autokey again. `sudo -H pip3 uninstall autokey`
2. Look at `/usr/local/lib/python3.6/dist-packages/`.
3. Is there still a directory named `autokey-0.94.0-py3.6.egg` (or similar)? If yes, manually remove it. It is in `/usr/local`, so manually removing things there is safe. If the uninstall in step 1 did not remove it, it was an untracked left-over, which might have interfered.
4. Install again. Assuming install from ZIP folder: `sudo -H pip3 install /path/to/zip/extracted/directory` (or without `sudo -H` to do a local user installation instead of a system-wide one.)

If this does not fix it, I’ll see if I can do something about it. Would you mind installing some development/testing versions? I’ll try some things and if those changes fix your problem, they will get integrated into the master branch.

**Comment by rickstaa** [comment]
Dear Luziferus,

Thanks so much for your fast response. The steps you provided repaired the "autokey-gtk" version. I don't know what caused the conflict but installing the current GitHub repository and uninstalling repaired the "Autokey-gtk" version. I think there were some conflicting files left over from the previous installation.

Thanks a lot!

**Comment by luziferius** [comment]
Edit: Glad it is solved.

**Comment by josephj11** [comment]
Looks like the OP originally tried to install both versions - one from the repo (0.90.4) and the other from GitHub - at the same time. That's why it wasn't happy.

I am gradually trying to improve the instructions in the [wiki](https://github.com/autokey/autokey/wiki/Installing) and would appreciate any feedback or direct revisions from anyone who actually has done the install successfully. Then you can point them there instead of explaining it from scratch each time.
