### ISSUE TITLE
Behavior change: Using date shortcut now adds newline where it didn't before

### ISSUE THREAD

**Issue by lwhitty** [autokey/autokey#145]
## Classification:

bug

## Reproducibility:

Reproducible

## Summary

As of version 0.94.0-1 on Fedora, using Insert Date sample script adds newline to date entry

## Steps to Reproduce

v0.90.4-11 and earlier:Typing ";d" inserts date. This is the desired behavior
v0.94.0-1: Typing ";d" inserts date, then newline. Makes it difficult to rename a file including the date.

## Expected Results

Inserting date should insert the date, then leave the cursor immediately after the date

## Actual Results

Inserting date inserts the date, then places the cursor on the next line. When renaming a file, the added return character ends the rename operation.

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

autokey and autokey-common v0.94.0-1

If the problem is known to be present in more than one version, please list all of those.

Installed via: dnf update

Distro: Fedora 27

## Notes

Describe any debugging steps you've taken yourself; 

If you've found a workaround, provide it here: Downgraded to v0.90.4-11

**Comment by luziferius** [comment]
General cause: Since the Python3 port, system.exec_command() did not remove trailing newlines from output anymore. The now-merged fix re-introduces this newline trimming, restoring the previous behaviour.

As a workaround, until the fix is pushed everywhere: Edit the first line in that script to be
`output = system.exec_command("date")[:-1]`
This removes the trailing newline. If you use the workaround, remember to revert it when you get this update, because otherwise it will start removing the last actual output character.

For reference:
The old (commented out) code that removed the newline at end of output: 
https://github.com/autokey/autokey/blob/d4dc979d930d6651ece76f81dc76193e4f72ec65/lib/autokey/scripting.py#L430

The new code (since Python 3) that does not remove trailing newlines:
 https://github.com/autokey/autokey/blob/d4dc979d930d6651ece76f81dc76193e4f72ec65/lib/autokey/scripting.py#L426

**Comment by sporkwitch** [comment]
Update pushed to 18.04 PPA and available for download.
