### ISSUE TITLE
keyboard.sendkeys in script called by phrase not working

### ISSUE THREAD

**Issue by M15071060** [autokey/autokey#147]
## Classification:

bug

## Reproducibility:

always

## Summary

When attempting to insert clipboard contents (in the form of a python script) in a Phrase, it appears to improperly call and inserts the phrase name, with the remainder of the characters in the clipboard.

It also appears to place this at the beginning of the file when it runs properly, however when it runs _improperly_ it is referenced in the intended location.

[Insert Clipboard Phrase.txt](https://github.com/autokey/autokey/files/2025120/Insert.Clipboard.Phrase.txt)

python script:
```
import time
time.sleep(0.25)
text = clipboard.get_clipboard()
keyboard.send_keys("{}".format(text))
```

## Steps to Reproduce

- type abbreviation for phrase (`textins`)
- confirm expansion

## Expected Results

- output should be:

> Prefix text
> Clipboard content
> Suffix text 

## Actual Results

> Phrase name
> beginning of clipboard content minus length of phrase name(*)Prefix text
> suffix text

* if the phrase is "textins" and the clipboard contains "textinsOne", the output is:

textins
*tex*Prefix text
Suffix text

where the *tex* is the remaining space of the clipboard. I hope this helps clarify that behaviour.

[autokeyVerbose.txt](https://github.com/autokey/autokey/files/2025127/autokeyVerbose.txt)

## Version
AutoKey-gtk version 0.90.4 

Installed via: elementaryOS AppCenter

Distro: elementaryOS

**Comment by luziferius** [comment]
Autokey 0.90.4 is a 6(?) years old version and unmaintained.
ElementaryOS seems to still use this old version: https://packages.ubuntu.com/bionic/autokey-gtk
I’ll look into this and see if I can reproduce this in the newest version and fix it there.

**Comment by sporkwitch** [comment]
@whitemoth I've not used ElementaryOS myself, but from what I can find, it's binary-compatible with ubuntu and its PPAs.  I have a PPA listed in the readme for 18.04 that's current.

**Comment by M15071060** [comment]
Thanks @sporkwitch & @luziferius 

I'll dig into this in a bit, for some reason even when following the steps to add a PPA (which I had to add something _else_ to do because elementaryOS stripped that) it reverts to installing the previous version.

**edit**

@sporkwitch When adding the PPA and performing update (log file here: [file.log] (https://github.com/autokey/autokey/files/2029041/file.log)) I receive errors on 50-1 and 60-4 indicating it's not fully successful, I'm not sure if I'm missing a step there.

I'd like to confirm that it's purely a version issue before anyone digs into something else; with these errors, when I update, it simply installs autokey-gtk 90.4 again.

**Comment by luziferius** [comment]
This is broken in the latest version, too.
I can confirm that this happens on my own autokey-qt branch (my latest changes on top of current git master).
I didn’t even know that such constructs were possible!

**Comment by M15071060** [comment]
@luziferius That's good to know that it's broken in real life too. I work predominately on macOS, and in Alfred the same setup looks like:

![screen shot 2018-05-23 at 21 16 11](https://user-images.githubusercontent.com/12193730/40451599-9fd97568-5ece-11e8-8c53-8cbd2c4e56ae.png)

**Comment by luziferius** [comment]
This code snipped here is executed when a phrase is pasted:
https://github.com/autokey/autokey/blob/54bd77c664aa1403d296b66a78dfa25e9ebdf902/lib/autokey/service.py#L390-L397
I haven’t found out the details in the called code, which is quite complex and completely undocumented. But the general work flow is:
1. Preprocess the phrase content
  - This includes executing embedded scripts
2. Paste the phrase using the method stored for the phrase.(Keyboard, Clipboard…)
Thus, if you do a `keyboard.send_keys("text")` in the script, this is executed prior to the phrase expansion in the preprocess step, ending up at the beginning of the output. It is then partly deleted by the abbreviation deletion code. So this won’t work at all.

(Below are more or less developer notes.)
I thought a bit about the problem and came up with two possible solutions.

## Possible solutions

Let’s consider the following phrase:
```
Part1 <script name=Script1 args=nil>
Part2 <srcipt name=Script2 args=nil>
Part3
```
### Split the phrase at <script> tokens into parts and process them in order.
In the example above, split the phrase into five parts, then process the items in order (I’m using pseudo-code function calls to show the flow.):
```
Remove_Typed_Abbreviation_If_Triggered_Using_Abbreviation_Mode()
Expand("Part 1 ")
Execute(Script1)
Expand(Part 2 ")
Execute(Script2)
Expand("Part3")
```
Advantage: (Should be) Simple to implement and should work quite reliably, even if the user bypasses our scripting API. It breaks if the user deliberately tries to break it in the script code. (E.g. by switching applications using `wmctrl`, using `system.exec_command("systemctl poweroff")`, `system.exec_command("killall autokey-gtk")`, etc. etc…)
Disadvantage: Phrase expansion cannot be undone, unless using the brute-force method: Backup everything.
Backup strategy draft (it is this complicated to keep the current cursor position and not move it to the begin or end):
1. Save the clipboard.
2. Copy everything before the cursor into the clipboard: Send <Ctrl>+<Shift>+<Home>, <Ctrl>+C>.
3. Save content part 1.
4. Send <Left> to restore cursor position
5. Save everything after the current cursor position: Send <Ctrl>+<Shift>+<End>, <Ctrl>+C>
6 Save content part 2.
7. Send <Right> to restore cursor position
8. Concatenate part 1 and part 2 into a full backup.
9. Restore clipboard


### Inject a 'virtual' keyboard into the global script scope
Background: When executing a Script, some class instances are injected into the scripts global scope before execution starts. This is used to provide the additional built-ins (`keyboard`, `mouse`, etc.)

https://github.com/autokey/autokey/blob/54bd77c664aa1403d296b66a78dfa25e9ebdf902/lib/autokey/service.py#L437-L443

If a Script is executed from within a Phrase, inject 'virtual' API classes instead. Those provide the same interface as the regular ones, but only operate on some internal buffer. This collects all keyboard interactions from a script (and recursively called scripts, see `system.run_script()` function) into a single string. Those can be inserted at the appropriate positions in the phrase text, and then expanded.

Advantages:
- Easy to undo, as the final result is fully known.
- It is an all or nothing approach. It can’t abort at some intermediate step. If preprocessing fails, nothing is done.

Disadvantages:
- Needs CAREFUL crafting. (What happens if the first thing a script does is pressing the backspace key? What if the user does complex cursor movement, text selection and clipboard magic?)
- Breaks if users use external tools and bypass the scripting API.

**Comment by luziferius** [comment]
@whitemoth The feature works as expected, this is a usage mistake. I think the documentation needs some clarifications.


Well, I just found the relevant interface…
AutoKey provides two functions for phrase-script interactions:
- [`engine.get_macro_arguments()`](https://autokey.github.io/lib.scripting.Engine-class.html#get_macro_arguments) provides the arguments from the `<script>` tag to the script
- [`engine.set_return_value(string)`](https://autokey.github.io/lib.scripting.Engine-class.html#set_return_value) sets the return value. This return value is evaluated and inserted into the phrase.

The user is not supposed to type directly with `keyboard.send_keys`, but instead use `engine.set_return_value` to provide the to be inserted data back to the phrase.

Try this fixed script:
```
import time
time.sleep(0.25)
text = clipboard.get_clipboard()
engine.set_return_value(text)
```
When using your example code, this will result in 
```
Prefix text

My clipboard content.

Suffix text 
```
