### ISSUE TITLE
autokey-gtk fails to restore pre-existing clipboard when expanding phrase using clipboard

### ISSUE THREAD

**Issue by ronjouch** [autokey/autokey#153]
## Classification:

Bug

## Reproducibility:

Always

## Steps to Reproduce

1. Create phrase expanding `foo` to `foobar`, with phrase setting `Paste using Clipboard`.
2. Select text `autokey` and press <kbd>Ctrl</kbd>+<kbd>c</kbd>. `autokey` is in your clipboard.
3. Expand phrase `foo` (by typing `foo`). `foo` is expanded to `foobar`, using the clipboard
4. Press <kbd>Ctrl</kbd>+<kbd>v</kbd>

## Expected Results

The pre-existing clipboard contents, `autokey`, are pasted.

## Actual Results

Instead, the expanded phrase, `foobar`, is pasted :( . Autokey used the clipboard to perform the phrase insertion, but failed to restore what was in the clipboard before expansion.

## Version

autokey-py3 0.94.1

Distro: bug reproduced both in Arch (AUR package) and Ubuntu (PPA package).

## Notes

Maybe `Mouse selection` is affected too, not sure. Haven't been able to test, as `Mouse selection` crashes 0.94.1 (bug fixed since then in https://github.com/autokey/autokey/pull/152 ) and I didn't take the time to test a `master` build.

Workaround: use other expansion modes.

**Comment by luziferius** [comment]
A note for myself: The clipboard restoration code is there:
https://github.com/autokey/autokey/blob/1476ca0502c5a9dac50795cd800268f5d0816982/lib/autokey/interface.py#L558-L565
It needs the same fix as done in #152.

It seems that this function is either not called or the clipboard is not properly stored, causing the first check to skip the function body. (Otherwise autokey would crash…)

Edit: After fiddling a bit with the GTK GUI, i got randomly locked up keyboards (#72), crashes, fatal errors killing autokey (leaving stacktraces). The only thing not working reliable is pasting using the mouse or clipboard…

**Comment by luziferius** [comment]
@ronjouch I refactored the whole pasting code, and it works properly on my side now. You may want to give it a try.

**Comment by ronjouch** [comment]
> I refactored the whole pasting code, and it works properly on my side now. You may want to give it a try.

@luziferius fix tested and confirmed working on my {Ubuntu,Arch}/python36 machines! Thanks 🙂🙂🙂.
