### ISSUE TITLE
Change Python directory

### ISSUE THREAD

**Issue by USchneid** [autokey/autokey#156]
Hallo, 
how can I change the Python directory? 
I would like to use my own anaconda-python instead of the preset Linux python version.
Best regards

**Comment by snippins** [comment]
@USchneid autokey-gtk is a python script, so you can try edit it directly and replace "/usr/bin/python3" with path to the python binary you want to use.

**Comment by luziferius** [comment]
Please note that autokey requires at least Python 3.5, so make sure your anaconda-python build is compatible.

The autokey-gtk (and autokey-qt) scripts are automatically generated by `setuptools` during the application install or during the package build, if you use a distribution package, so we can’t really do anything about it.

Directly editing the scripts as pointed out above should work. Your system should pick up the interpreter specified in the first line and use it to execute the script.
If installed using distribution packages, this approach has a potential drawback: It will make system validation tools (like `debsums`) unhappy, because you manually altered system files.

Another option is executing the file directly using your python executable, like `/usr/local/bin/anaconda-python3 /usr/bin/autokey-gtk` (adjust the example paths to your needs). This way, you can use any interpreter you want (even python2.7 if you really want to get an error message ;) ).
You can edit the `autokey-gtk.desktop` file and adjust the executable in there.
