### ISSUE TITLE
Does not work with Rofi

### ISSUE THREAD

**Issue by snippins** [autokey/autokey#157]
## Classification:
Bug

## Reproducibility:
Always

## Summary
I use a launcher program called [rofi](https://github.com/DaveDavenport/rofi). I use autokey phrases to map arrow keys to hyper + hjkl (I modified the us layout file to have capslock as the hyper key). When I open to rofi window to run a program, autokey seems to send the keys to the window below it instead. 

## Steps to Reproduce
For example:
1. Using firefox and then open rofi, 
2. Try to use Hyper + j/k to move between the programs listed in rofi.

## Expected Results
It should act like arrow keys and move change the highlighted program up/down.

## Actual Results
The page in firefox scroll in stead, a bunch of j,k letters is typed in to rofi.

## Version
Latest git e1b6ba4.

Distro:
KDE Neon, basically Ubuntu 16.04

**Comment by ghost** [comment]
Can confirm the same issue is happening to me, except I use `alt+i` to go up one entry and `alt+k` to go down one.

**Comment by bard** [comment]
Try launching rofi with the `-normal-window` command line option.

**Comment by mattiasJohnson** [comment]
Having the same problem, does indeed work if you launch it with  `-normal-window` although that's not really a solution for everyone who want's to use rofi the normal way (i.e. not creating a big window and messing up the workspace)

**Comment by bard** [comment]
@mattiasJohnson what window manager do you use? With i3 the following works nicely, no big window nor messing:

```
bindsym $mod+space exec "rofi -modi 'combi' -combi-modi window,drun,run,ssh -show combi -normal-window"
for_window [class="Rofi"] floating enable
```

**Comment by luziferius** [comment]
The interface AutoKey uses requires the receiving application to hold the current window focus, because the window holding the focus receives the events generated by XRecord.

I assume that without `-normal-window`, Rofi does not take the window focus at all and instead listens on it’s own for events coming from the physical keyboard, while rendering some kind of overlay.

Thus, It may not work at all in normal mode, using stock AutoKey in it’s current form.

But you may have success by using `uinput` to emulate a physical keyboard. This has it’s own drawbacks, but depending on your use-case, it might be a viable workaround.
In #195, I wrote a proof-of-concept construct that enables AutoKey to send input to `xterm`, which otherwise ignores key presses generated by AutoKey. Adopting it to this case needs some Python coding skills, but should be doable…

**Comment by WillForan** [comment]
this doesn't help with rofi, but for xterm (@luziferius) you can enable `allowSendEvents` via ctrl+right click menu, as cli option,  or via resource file (e.g. `.Xdefaults`)
```
*XTerm*allowSendEvents: True
```

**Comment by josephj11** [comment]
I knew xterm had an option for that, but I didn't know what it was.

(@luziferius was our lead developer until he ghosted us a year or two ago.) I think his analysis of this problem is probably correct.

If anyone is interested in pursuing this further, the first thing to do would be to run an AutoKey [trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide).

This should show you every keypress that AutoKey detects and what key it thinks that represents. If it tries to run an event, it will also show you the name of the active window AutoKey is interacting with.

As @luziferius notes, I suspect it is talking directly to the application window and not to whatever process rofi is running as.

Also, the OP makes some references to remapping their keyboard and the CapsLock key. AutoKey tends to interact at a level below such remapping and may ignore it all together. A trace will show if this is the case.

If the above is correct, then it's a artifact of the i/o libraries AutoKey uses and there's nothing we can do about it short of a major rewrite that only _might_ address the problem.

That being said, there may be other things you can try.

Look at xbindkeys. It might allow you to bind a keypress to run a script or program of your choice. If you code it carefully, you may be able to enable/disable this behavior on demand based  on an external factor such as  a lock file which you could manipulate with or without AutoKey.

I haven't worked with this, so I'm not sure of what it will or won't do.

Since this has been around for four years and probably can't be fixed, I'm leaning toward closing this issue as not an AutoKey problem, or as won't fix. @BlueDrink9 , what do  you think?
