### ISSUE TITLE
autokey-qt 0.95.2 does not start on Kubuntu 18.04

### ISSUE THREAD

**Issue by alpenblauwtje** [autokey/autokey#170]
## Classification:

Bug

## Reproducibility:

Always

## Summary

autokey-qt 0.95.2 does not start on Kubuntu 18.04

## Steps to Reproduce (if applicable)
I installed autokey-qt 0.95.2 on Kubuntu 18.04.1, by downloading and installing the `autokey-common` and `autokey-qt` package (the installation documentation is not very clear on this, or maybe I missed something).
I started autokey (Qt) from the menu, but nothing (visually) happened. Then I started autokey-qt from the CLI and got the following error:

```
$ autokey-qt
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 11, in <module>
    load_entry_point('autokey==0.95.2', 'console_scripts', 'autokey-qt')()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 110, in __init__
    self._configure_root_logger()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 169, in _configure_root_logger
    backupCount=common.MAX_LOG_COUNT
  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/.local/share/autokey/autokey.log'
```

I checked ~/.local/share and by default there is not autokey folder. After I created an autokey folder here it worked!

**Comment by josephj11** [comment]
Glad you got it to work. In the immediate future, please check at
this [PPA](https://launchpad.net/~sporkwitch/+archive/ubuntu/autokey)
for use with 18.04. At the moment, it's slightly behind the latest version.

For the latest version, install using pip. See
these [instructions](https://github.com/autokey/autokey/wiki/Installing).

**Comment by luziferius** [comment]
That manual installation is fine. You only need the `autokey-common` and `autokey-qt` package. All other dependencies are in the official repositories. As said, you may want to use the PPA and get automatic updates.

You only need pip, if you want to install the latest commits right from the git master branch.
(The version from PiPy seems to be outdated…)

Ok, I found the issue…
The logger (which is configured to write the log to a file) is configured before the directories get created…
https://github.com/autokey/autokey/blob/78570d02e8c5c57527e861c722056c1d8a73fc4a/lib/autokey/qtapp.py#L110-L114

I’ll push a fix in some minutes. You won’t need to install the fix, since the directory now already exists on your system.

Thank you for reporting this!

**Comment by luziferius** [comment]
Fixed in https://github.com/autokey/autokey/commit/5ac974de3191306a5d6ed00109fd448d7cb46aad
This will be included in 0.95.3.

**Comment by alpenblauwtje** [comment]
Thank you both for your support and quick fix! Good to see there's active development for this great tool!

**Comment by alpenblauwtje** [comment]
Wrt the documention: joseph refers to another PPA (ppa:sporkwitch/autokey) than listed in the documentation (ppa:troxor/autokey). The doc also mentions '_As of 10/2017, the PPA only supports Ubuntu 16.04 and derivatives._', the reason I used .deb packages instead of the PPA. 
Which PPA is the right one, and is 18.04 supported?

**Comment by luziferius** [comment]
`ppa:sporkwitch/autokey` is the current one, supporting bionic (18.04) only, and is listed in the project readme.
`ppa:troxor/autokey` was the previous PPA, which was abandoned, because of whatever reason, it stopped accepting new package builds. (As far as I know)

I think, you found another bug in the wiki. I’ll update the page to reflect the currently valid information.
Thank you for pointing that documentation issue out.
