### ISSUE TITLE
Preventing data deletion in a folder when the created folder's name is same as existing folder.

### ISSUE THREAD

**Issue by 1nsp1r3rnzt** [autokey/autokey#171]
## Classification:

Data Loss

## Reproducibility:
Always

## Summary
I created a new folder "blog" in the root of folder hierarchy in AutoKey. I didn't noticed that folder is being created inside HOME.
There was already a folder "blog" in HOME which contained my blog's source code.
When I cut the folder "blog" in Autokey and pasted it inside "My Phrases" folder, I accidently lost all the data inside ~/blog folder which was not moved along to "(Default Folder)/My Phrases/ blog".
## Steps to Reproduce
1. Create a folder inside Autokey with same name as any folder in HOME.
2.  Cut the folder in AutoKey and paste inside any other folder.
3. Browse the folder and all the files are missing except a newly created file ".folder.json".

## Expected Results

- This is an edge case and involves user's carelessness but still accidental data loss must be prevented by moving existing user data to another folder "ignoredData" which can be ignored by AutoKey.
- It should not delete any files.

## Actual Results

- Autokey retained only the folders and deleted all the files while moving the folder. 

## Version

AutoKey version: 0.95.1

Used GUI (Gtk, Qt, or both): Gtk

Installed via: (PPA, pip3, …). I don't remember it exactly.

Distro: Ubuntu 18.04

**Comment by luziferius** [comment]
I’m sorry to hear that AutoKey deleted your data. I hope you have a backup of the deleted data.

I looked around, and the code involved wasn’t touched in years. I wonder why no-one else already reported this…
When cutting, autokey reads in the known data, and then deletes the files. Drag&Drop move is implemented as "cut (delete everything), then paste (re-create files)" instead of a proper file system move.
Nonetheless, this should never delete data (unknown to autokey).
Another way to lose data seems to be cutting an element, then closing autokey.
The whole thing needs to be re-written. Both in `autokey-gtk` and `autokey-qt`.

**Comment by josephj11** [comment]
I think very few people have realized that you can even create a new folder
outside of AutoKey (~/.config/autokey/data/...). I use it so my scripts are
safe even if I purge AutoKey.

In the OP's case, AutoKey probably should have warned that the folder
already exists (or actually blocked it from being used) when the user tried
to create it in AutoKey

**Comment by luziferius** [comment]
@1nsp1r3rnzt I have added a warning message that explains the possible data loss and discourages from using a directory that already contains files. If the selected directory contains files, AutoKey will ask a second time. This should prevent accidental losses.
