### ISSUE TITLE
keyboard.send_keys sends Hotkey too.

### ISSUE THREAD

**Issue by nemonein** [autokey/autokey#181]
## Summary

Version : Autokey Qt v0.95.3, on Kubuntu 18.04.
I've installed the deb package you've uploaded here.

I've been using autokey for Short-cut changer. (I'm a Dvorak keyboard user, and Autokey's this function really helps me.)

For example, I change the usual "Ctrl + F" to "Ctrl + U".
So, 
```
 Hotkey : <ctrl>+u
 Command : keyboard.send_keys("<ctrl>+f")
```
This worked good before v0.95.3. If I press Ctrl + U, only Ctrl + F signal is out.
However, on v0.95.3, Ctrl + U and Ctrl + F keys out simultaneously.
On Google Chrome, pressing Ctrl + U triggers 'Page Source' and 'Find'.

## Expected Results

Above example, only Ctrl + F has to be out.

**Comment by luziferius** [comment]
Hmmm. I tried to reproduce it and failed.
I installed chromium (the open source version of the Chrome browser) and the autokey deb packages attached to the release, reconfigured my session to use the English (US) version of Dvorak keyboard layout, and used the exact script as provided.
When I press \<ctrl>+u, I see the search pop-up window appearing. I don’t get a new tab showing the page sources.

I tried this in firefox, and got the same expected result.

I suspect this is some spurious timing issue. Or autokey fails to grab the \<ctrl>+u global hotkey.

You said, it worked before. So it worked in 0.95.2? Or was it an even earlier version?

**Comment by nemonein** [comment]
Sorry for the confusion.
I tried again, but it did not happen. (It did yesterday..)
Anyway, as far as I concern, it always has worked fine until 0.95.2.

I'll tell you if it happens again.
By the way, when it happens, what should I check? (Log, or any messages from autokey).

You can close this for now.

**Comment by nemonein** [comment]
It's just happened again.
This time I could record.
![autokey-send-keys-err](https://user-images.githubusercontent.com/5688288/44977550-495a8800-afa3-11e8-94bc-47d58b7a5ad3.gif)

I pressed `<Ctrl>` + `<U>` on Dvorak keyboard, and Autokey should send `<Ctrl>` + `<F>`, but it sends both keys.
It just happened not only on Chrome, but also on Kate, the text editor.

**Comment by luziferius** [comment]
Thanks, that looks like a definite proof ;)
I’m quite puzzled by this, because I didn’t touch the `keyboard` scripting code… (This is the full diff: [v0.95.2...v0.95.3](https://github.com/autokey/autokey/compare/v0.95.2...v0.95.3#files_bucket))

You can try running autokey from the console using `autokey-qt --verbose` in verbose mode. (Quit any running instance before, because only one instance can run at a time.)
Then look through the output (save like the last 50 lines when the issue happens), and post them here. (Don’t post the log, if it contains passwords, of course!)


If you wish, you can try to identify the offending git commit. This might be a lengthy process and might give no usable result, but we can try it nonetheless:

Here is the list of all changes made: https://github.com/autokey/autokey/compare/v0.95.2...v0.95.3. If this bug happens in 0.95.3 and does not in 0.95.2, there must be one commit in that list that introduced this issue.
- Uninstall the currently installed version of autokey.
- Perform some command line tasks:
- Clone the git repository: `git clone https://github.com/autokey/autokey.git` This will create an `autokey` directory containing the current version and all previous changes.
- `cd autokey`
- `sudo -H pip3 install -e .` (Note that dot. It will install the program at the current location). The `-e` switch installs the git repository in developer mode. All changes in the downloaded directory will be reflected in the installed version without the need to re-install after changes.
- At this point, you should be able to start autokey-qt again using `autokey-qt`.


Now the tedious part begins:
Use autokey as usual. If the bug happens (best if you can reproduce it several times in a row.)
1. Exit autokey, open a Konsole at the cloned autokey repository. (`cd /path/to/your/autokey/clone`)
2. `git checkout <some_commit_hash>`. Use a SHA1 hash from the list above, between the two releases. (For example `git checkout 968622ad6050c47a7f17079c2d6a170452ba24b8`). The hashes can be extracted from the commit links. A [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm) might be the fastest to get this to an end.
3. Start autokey-qt again and try to reproduce the bug.
    - If it still happens: Repeat the numbered steps, but replace the commit hash in step 2 with an _earlier_ commit hash.
    - If it does not happen any more: Repeat the numbered steps, but replace the hash with a _later_ commit hash (but still earlier than another commit you already tried)

In the end, you should end up with knowing that one commit works and the next (or so) commit does not work as expected. Post your findings.

I’ll try to figure out how the change caused this issue and try to fix it.

**Comment by edy1234** [comment]
The same thing has been happening to me on 0.95.3 from the AUR, on both the gtk and qt versions. What I noticed, is that it doesn't happen if I have CAPS LOCK enabled. It doesn't matter what browser or app is the visible window it seems. Also, I'm a QWERTY keyboard user.

E.g if I have a simple script that remaps ctrl+v onto a single key, it first pastes the single key's value and then pastes the text from my clipboard. If I have capslock enabled when pressing the hotkey, it only pastes the text I wanted.

I did what you suggested with the git commits, and it seems to be caused by commit

eb46b8440d8a513c07bbe5b2c2184738f153e952

Or at least, in my tests, the problem happened with that commit (and the later commits I tried), while it didn't appear in the earlier commits I tried.

**Comment by luziferius** [comment]
Thank you!!!
OP said 0.95.2 was fine, so I was really scratching my head over this diff [`v0.95.2...v0.95.3`](https://github.com/autokey/autokey/compare/v0.95.2...v0.95.3#files_bucket). The comment you indicated is between 0.95.1 and 0.95.2.
The affected code does some boolean operations with bit flags. I did transform those step-wise using equivalent expressions until I minimized the logic code while keeping the semantics. I’ll double check if i had done it correctly.
This is a performance optimization and causes the code to be faster, which then causes unexpected timing issues… 

This is a very local change, so if you want to patch it yourself for now, you can use rebase to remove the commit from the history. `git rebase --interactive v0.95.1`, and then `drop` the commit from history. (In the opened editor, replace the `pick` in the line with `d` or `drop`, save, close the editor and let git rebase.) Then you can install your local copy, without having the offending commit.
(If you do rebase it out, please also report back if it is fixed on your side.)

**Comment by edy1234** [comment]
I don't have much experience with git, but if I followed your instructions correctly, then rebasing and dropping that commit worked in getting a local copy without the timing issue bug.

Thank you very much for your help and for teaching me a few handy things about git and pip!

**Comment by LeroyZwakman** [comment]
i've added a second pipe in it; ant it works for me in interface.py:
`
            if Key.CAPSLOCK in self.modMasks and Key.NUMLOCK in self.modMasks:
                window.grab_key(keycode, mask|self.modMasks[Key.CAPSLOCK]||self.modMasks[Key.NUMLOCK], True, X.GrabModeAsync, X.GrabModeAsync)
`

**Comment by LeroyZwakman** [comment]
this is my code that works now (interface.py)
```
    def __grabHotkey(self, key, modifiers, window):
        """
        Grab a specific hotkey in the given window
        """
        logger.debug("Grabbing hotkey: %r %r", modifiers, key)
        try:
            keycode = self.__lookupKeyCode(key)
            mask = 0
            for mod in modifiers:
                mask |= self.modMasks[mod]

            window.grab_key(keycode, mask, True, X.GrabModeAsync, X.GrabModeAsync)

            if Key.NUMLOCK in self.modMasks:
                mask |= self.modMasks[Key.NUMLOCK]
                
            window.grab_key(keycode, mask, True, X.GrabModeAsync, X.GrabModeAsync)
          
            if Key.CAPSLOCK in self.modMasks:
	        mask |= self.modMasks[Key.CAPSLOCK]

            window.grab_key(keycode, mask, True, X.GrabModeAsync, X.GrabModeAsync)

        except Exception as e:
            logger.warning("Failed to grab hotkey %r %r: %s", modifiers, key, str(e))
```

**Comment by LeroyZwakman** [comment]
got that fixed; for ctrl that is; for the superkey it' still broken.

**Comment by luziferius** [comment]
I reverted the offending commit https://github.com/autokey/autokey/commit/eb46b8440d8a513c07bbe5b2c2184738f153e952 and released version 0.95.4.

This should be fixed. If the issue is still present on 0.95.4, please report back.

**Comment by nemonein** [comment]
I've installed 0.95.4, and it seems it works fine.
Thanks!

**Comment by SymbolicFrank** [comment]
This still happens with Autokey (Qt) 0.96.10 on Linux Mint 21.3 Cinnamon.

I made a script: "keyboard.send_key(Key.DOWN)", assigned a Window Filter (window class scummvm.scummvm) and a Hotkey ("s"). 

It sends both, first Key.DOWN, then "s".

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @SymbolicFrank !

The behavior you ran into is somewhere between a feature and a bug. Mainly, it just won't work the way you are attempting to do it.

`keyboard.send_key()` is a special purpose API call that should only be used as a last resort. It can only send one key and that doesn't include compound keys even as simple as shift+s to get an uppercase S.
In addition to this, some of our API calls including keyboard.send... and all the clipboard calls are asynchronous while others like keyboard.press... are synchronous which in simple language means that they don't work together.

Doing things like you want to do is very common in AutoKey, so we have several articles in our wiki describing how it works and how to do it. Check out [this](https://github.com/autokey/autokey/wiki/Emitting-Keyboard-Events), [this](https://github.com/autokey/autokey/wiki/Key-Combinations), and [this](https://github.com/autokey/autokey/wiki/Special-Keys).

Also, check out the rest of our wiki. It contains a number of useful articles and lots of example scripts. 

For general support and to discuss anything related to AutoKey, join us on our forums. See boilerplate below.
They're pretty quiet lately, but people usually respond to questions and I check them almost every day.

Joe

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

New users are encouraged to spend some time browsing through our [wiki](https://github.com/autokey/autokey/wiki). There are a number of helpful articles there as well as many example AutoKey scripts.
