### ISSUE TITLE
Cannot find D-Bus Qt5 module despite installed

### ISSUE THREAD

**Issue by DaAwesomeP** [autokey/autokey#184]
## Classification:

Bug

## Reproducibility:

Always

## Summary

Autokey cannot find the `dbus.mainloop.qt` module despite being present on the system.

## Steps to Reproduce (if applicable)

I installed the latest Autokey from pip3. I tried both the latest release version and the latest master. I installed the necessary D-Bus development dependency in OpenSUSE so that pip could compile all the dependencies and install successfully. I tried installing both python3-qt4 and python3-qt5 from the OpenSUSE repos.

## Expected Results

Autokey should launch without issue.

## Actual Results

```bash
$ autokey-qt
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 56, in <module>
    from autokey.qtapp import Application
  File "/usr/lib/python3.6/site-packages/autokey/qtapp.py", line 23, in <module>
    import dbus.mainloop.qt
ModuleNotFoundError: No module named 'dbus.mainloop.qt'
```
However, I have verified that the Python3 Qt5 D-Bus module is on my system:

```bash
$ ls /usr/lib/python3.6/site-packages/dbus/mainloop/
glib.py  __init__.py  __pycache__  pyqt5.so  qt.so
```

I can also verify that the D-Bus module is included in the OpenSUSE python3-qt5 package from [the build spec file line 198](https://build.opensuse.org/package/view_file/openSUSE:Leap:15.0/python-qt5/python-qt5.spec?expand=1).

## Version

AutoKey versions: v0.95.3, master 3e60a0161e3f3d0854dac5207de2f607aa20d7a3

Used GUI: Qt

Installed via: pip3

Distro: OpenSUSE Leap 15.0 x64

**Comment by luziferius** [comment]
Well, OK… Just Nope.
I ripped out the `dbus.mainloop.qt` dependency here: https://github.com/autokey/autokey/commit/171a30e4afc5f01d0da4b1019e3185195bdb8e8b. Newer versions (0.95.0 onwards) don’t use that library any-more, because of exactly the issue you are experiencing.

This means your have another version (<=0.94) installed. `pip3` installations default to `/usr/local` if installed as root, or `~/.local` if installed as a regular user. So uninstall the version installed using your package manager. Your system probably prefers the old version, because the `/usr/bin/` is listed before `/usr/local/bin` in `$PATH`.

By the way: If you installed `python-dbus` using `pip3`, remove it again, because it breaks other PyQt applications using dbus (like the HPLIP software).

**Comment by DaAwesomeP** [comment]
I see! Unless my pip3 is really messed up, it shows v0.93.10 as the latest version. This is what I did to get it to work:
```
pip3 uninstall autokey dbus-python pyinotify python3-xlib python-xlib
pip3 install https://github.com/autokey/autokey/archive/v0.95.3.tar.gz
zypper in python3-qt5 python3-qscintilla-qt5
```
Thank you for this fine piece of software! I've already setup my text expansions/phrases!
