### ISSUE TITLE
How to get the current (not "most recent") selection?

### ISSUE THREAD

**Issue by lpirl** [autokey/autokey#186]
When calling ``clipboard.get_selection()`` from scripts, the _most recent_ selection is returned.

E.g., if the user types "foo bar", selects "bar" and hits backspace (which deletes "bar"), a subsequent call to ``clipboard.get_selection()`` would still return "bar", although there is no selection anymore.
However, for most situations (at least for mine :)), getting the _current_ selection is of more interest.

I am aware of the workaround used [here](https://github.com/autokey/autokey/wiki/Scripting#key-wrapper).

As you folks are probably aware of this confusing GTK API, I'd like to ask if there is a more elegant solution compared to the one above.

## Version

AutoKey version: 0.95
Used GUI (Gtk, Qt, or both): Gtk
Installed via: pip3
Distro: Debian

**Comment by luziferius** [comment]
This issue tracker is not intended for usage questions, but for actual program issues like bugs or enhancement proposals. These kind of usage questions are better asked somewhere else, like in our gitter chatroom. (Link is at the top of our readme file).

Anyways, I’ll answer it here.

This is just how the selection works. AutoKey follows the standard X11 clipboard specification. There are three clipboards available: `PRIMARY` is equivalent to the _last selected_ text, `SECONDARY` is unused and ignored by most applications and `CLIPBOARD`, which is used for keyboard combination copy/cut/paste operations.

The API function`clipboard.get_selection()` simply reads and returns what the X server provides as `PRIMARY`, whatever that might be. It is not empty after deselection, because deselection does not clear`PRIMARY`, by protocol specification.

Try it yourself: Select some text, deselect it again, and then press the middle mouse button over a text editor. Your previously selected text is pasted. This might be an interesting read: https://standards.freedesktop.org/clipboards-spec/clipboards-latest.txt

Now what you can do:
```
backup_clipboard_content = clipboard.get_clipboard()
keyboard.send_keys("<ctrl>+c")  # Copy the current selection
time.sleep(0.1)  # Wait for asynchronous operations to finish. This might need tweaking.
current_selection = clipboard.get_clipboard()  # Get the actual selection data.
clipboard.fill_clipboard(backup_clipboard_content)  # Restore previous clipboard
if current_selection:  # There is something selected
    pass  # current_selection is full. Do what you need here
else:  # There is nothing selected
    pass  # current_selection is empty. Do something else?
```

**Comment by lpirl** [comment]
Alright, this is what I found as well but thank you so much for the quick response @luziferius.

Now that I know that this project does not want questions in the tracker, I'll head over to IRC next time, of course (I ask myself: "Is the IRC archived? If questions cannot be asked here, where can users search for past questions asked?". Anyway :)).

**Comment by luziferius** [comment]
IRC isn’t archived unfortunately (as far as I know). But you can ask there, and check back here: https://gitter.im/autokey/autokey The Gitter chat is bridged with the IRC, is archived and can be browsed.

I was following the previously established "no-usage-questions" policy. Personally, I don’t really care.

We have a [stackoverflow tag](https://stackoverflow.com/questions/tagged/autokey), a [forum on google group](https://groups.google.com/forum/#!forum/autokey-users), the IRC and the [Gitter chat](https://gitter.im/autokey/autokey).

If you ask there, you can additionally ping me using the gitter chat. A @ mention sends me a mail.
