### ISSUE TITLE
chaotic results in different programmes

### ISSUE THREAD

**Issue by herrdeh** [autokey/autokey#189]
## Classification:
Bug
## Reproducibility:
Always
## Summary
In different programmes, AutoKey expands the abbreviations to different results.
## Steps to Reproduce (if applicable)
I changed all the phrases to "paste usíng clipboard (ctrl-V). Then, type the abbrevs as below: 

### LibO
"iban" creates 3 different solutions:
ibDE3976090900222366720
iDE3976090900222273606 
ibaD397609090022227360

... instead of:
DE39760909002222736600

"sgdh" reliably expands to:
Sehr geehrte Damen und HeSehr geehrte Damen und Herren,

### Evolution
"sgdh" produces:
sgdhSehr geehrte Damen und Herre
occasionally:
sgdSehr geehrte Damen und Herren

"mdfg" goes to:
mdfgMit Dank und freundlichen Grüßen,
Wolf Drech

### Firefox
In FF these results

sSehr geehrte Damen und Herren,

->
sgSehr geehrte Damen und Herren,
sSehr geehrte Damen und Herren,
instead of
Sehr geehrte Damen und Herren,

sgr ->
sgSehr geehrter Herr
Sehr geehrter Herr
Sehr geehrter Herr
sSehr geehrter Herr
sSehr geehrter Herr
sSehr geehrter Herr
sSehr geehrter Herr

sge ->
sSehr geehrte Frau
sSehr geehrte Frau
sgSehr geehrte Frau
Sehr geehrte Frau
sgSehr geehrte Frau

## Version

AutoKey version: 0.95.1
Used GUI (Gtk, Qt, or both): unsure - using GNOME desktop
Installed via: http://ppa.launchpad.net/sporkwitch/autokey/ubuntu
Distro: ubuntu 18.04

**Comment by josephj11** [comment]
Possibly related to #151 and #153 which are being worked on. 

0.95.1 is the current PPA version which not updated as quickly as the pip version which is at least 0.95.3. When this gets fixed, there may be some lag before it gets into the PPA.

**Comment by herrdeh** [comment]
I'd say, #151 is my issue. I'll feed my info there and close.
Thanks!

**Comment by luziferius** [comment]
@herrdeh By the way: If you use abbreviations in LibreOffice, make sure they don’t clash with the abbreviations defined in the LibO autocorrection settings.
I was puzzled why I was able to reproduce `Sehr geehrte Damen und HeSehr geehrte Damen und Herren,`, but only with `sgdh` as abbreviation and NOT with `sgdh1`, for example.

I looked at the settings (`Extras` → `AutoKorrektur` → `AutoKorrektur-Optionen`). There is a full list of those abbreviations defined. Especially, there is `sgdh` defined as `Sehr geehrte Damen und Herren`. Thus this particular case is caused by a double expansion.
