### ISSUE TITLE
Add a --version switch to the command line interface

### ISSUE THREAD

**Issue by luziferius** [autokey/autokey#190]
## Classification:

Enhancement

## Summary

Add a `-V` and `--version` command line switch that prints the current version.
Use the `argparse` version action to implement it.

## Version

AutoKey version: <=0.95.3

Used GUI (Gtk, Qt, or both): both

**Comment by josephj11** [comment]
While you're at it, what do you think about adding -v as a synonym for -l? v == verbose in many programs.

**Comment by luziferius** [comment]
Done for autokey-qt in https://github.com/autokey/autokey/commit/aaa863354c12cbc94622e2fbb65b249cea2e2093
And for autokey-gtk in https://github.com/autokey/autokey/commit/ee747a09e5a6ac703a880bdd7c935258fe091b5a

@josephj11 I don’t know. I guess that `-l` was chosen over `-v`, because the latter is easily confusing. Like in: “Was it the short form for `--version` or `--verbose`?”
In `-v` vs. `-V`: I tried to find some definitions [here](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html#Command_002dLine-Interfaces) and [here](https://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table), but it is not really defined, so this may be application-dependant.

The alias can be easily added here: https://github.com/autokey/autokey/blob/aaa863354c12cbc94622e2fbb65b249cea2e2093/lib/autokey/argument_parser.py#L26
Just add `"-v"` to the list. In my personal opinion, this adds ambiguity for no real benefit. I like the GNU style long options and prefer them over the short ones whereever reasonable.

What do do expect, if you run `autokey-qt -lv` or `autokey-gtk -l -v`?

**Comment by josephj11** [comment]
It's not a big deal. Maybe just a personal preference. If you specified them both, it wouldn't do anything additional as there are no logging levels and no flag to turn logging off. (I'm not suggesting that there should be.) If you don't think it's a good idea, I'm fine with that.

As far as definitions, that's one of the major weaknesses of Linux. (Linux Hater's Handbook is a good read. It's very dated, but a lot of it is still true.) Since there was and is no centralized control at levels beyond the kernel - especially at the user interface level - there are all sorts of arbitrary and whimsical command names and options. As an example, grep stands for global regular expression print, but I'm sure (with no evidence whatsoever)  they considered the joke that grepse means to burp in Yiddish. Or somebody wanted another copy program like cat, so they named it dog. I hear that the Unix folks started to try to make things better with Plan 9,  but that was a dead end.
