### ISSUE TITLE
Autokey QT discards script exception stack traces, making debugging impossible

### ISSUE THREAD

**Issue by nyanpasu64** [autokey/autokey#192]
## Classification:

UI/Usability

## Reproducibility:

Always

## Summary

When a script encounters an exception, Autokey QT discards the exception, making it impossible for me to know why the script failed.

## Steps to Reproduce (if applicable)

- Write a script which throws an exception. (I'm trying to map Ctrl+Down/Up to "long scroll", by importing a "long scroll" function from another file, to avoid duplication).

## Expected Results

- Backtrace is displayed to the user, or saved to a log file.

## Actual Results

- The exception trace is discarded, and the exception is swallowed.

https://github.com/autokey/autokey/blob/4d95766b604215636a957ea0b819c9516709048a/lib/autokey/service.py#L468

## Version

AutoKey version: 0.95.1 (same code present in master)

Used GUI (Gtk, Qt, or both): Qt

Installed via: (PPA, pip3, …). PPA

Distro: Kubuntu 18.04

**Comment by nyanpasu64** [comment]
Apparently `e` is an unused variable, but the stacktrace is saved via `traceback.format_exc` and rendered in "Settings/Show log view".

Nonetheless the existence of such a log console was not intuitive, maybe the popup notification should specify "Check Settings/Show log view to see error details"?

**Comment by luziferius** [comment]
You can view the last error (the complete stack trace) in Tools->Show last script error.
This was done, because it was not expected that users open autokey in a console window to view error messages.

I checked, and AutoKey does log the exception information to the standard output. The exceptions are caught, so that user scripting mistakes do not crash the whole application.
