### ISSUE TITLE
feature request: AutoSave changes

### ISSUE THREAD

**Issue by allanlaal** [autokey/autokey#194]
would be an opt-in setting

## use case:

I always forget to hit Save when doing a change and wonder why AutoKey is not working

**Comment by josephj11** [comment]
What happens if you go into Settings->Configure AutoKey->General->Application and uncheck Prompt for unsaved changes?
I think that makes it save changes upon exit automatically.

It won't save them every five minutes or anything like that and it won't help if you make a change and test without saving or leaving the main AutoKey window, but it will keep you from losing work.

**Comment by luziferius** [comment]
Unchecking "Prompt for unsaved changes" will cause AutoKey to automatically save as soon as you
- switch to another item in the left tree
- close the main window (currently only in the GTK interface, the Qt interface will keep the unsaved changes)
- quit AutoKey (i think it does save)

Maybe the option text should be re-worded.

**Comment by josephj11** [comment]
Prompt instead of auto-saving changes
Prompt before auto-saving changes

**Comment by luziferius** [comment]
How about negating the text? Instead of 
- [ ] Prompt for unsaved changes

do

- [x] Automatically save changes without confirmation

The checkbox state will be inverted. It is a simple thing to add a `not` to the logic loading and saving the boolean values and keep it compatible with existing user saves.

**Comment by josephj11** [comment]
@luziferius - That's much better. The only time it doesn't save is if it gets killed before one of the events that causes it to autosave. And that's like almost any other program except those that are transaction based.

**Comment by luziferius** [comment]
I updated the wording in both the [Qt](https://github.com/autokey/autokey/commit/4ed8d611a213f86e8afa389bd719527603c69d33) and [GTK](https://github.com/autokey/autokey/commit/1833806ad95f0344a4822047c2d0b3117469c68e) GUI.

The change will be in the next release. Both GUIs now phrase the setting as `Automatically save changes without confirmation`.

**Comment by luziferius** [comment]
Released version [`0.95.5`](https://github.com/autokey/autokey/releases/tag/v0.95.5), containing the updated wording.
