### ISSUE TITLE
No uppercase letters

### ISSUE THREAD

**Issue by fodiator** [autokey/autokey#20]
Hi,
I have installed this recent version on kubuntu 15.10 with a german keyboard layout.
Unfortunately all my phrases are converted to lowercase when inserted by autokey-qt, although they are displayed correctly within the config window of autokey.
This bug shows up since I've upgraded to 15.10. On my notebook under kubuntu 15.04 autokey-qt works as expected.
THX in advance

**Comment by RaymiiOrg** [comment]
I've got this issue as well. Arch linux with KDE Plasma 5.6 and autokey-qt. Different paste methods don't make a difference. The GTK version on XFCE and MATE does work as expected (with capitals).

**Comment by fodiator** [comment]
Issue is solved for me since upgrading to kubuntu 16.04

**Comment by fodiator** [comment]
In all GTK apps, even under KDE autokey works as expected. Just QT-Apps insert all phrases lowercase.

**Comment by RaymiiOrg** [comment]
Well that would explain why in some cases it does work and in some cases it doesn't work. @fodiator is correct here, in my QT terminal (SecureCRT) capitals are not inserted, in my GTK term (Mate terminal) they are. Any update on this issue?

**Comment by GHPS** [comment]
I can confirm the bug: I just switched from Kubuntu 14.04 LTS to 16.04 LTS. Autokey-Py3 has been working fine for years - even with German umlauts. In the current version I can't insert any uppercase letters using the "keyboard" method. Had to switch all scripts to "mouse selection" instead.

**Comment by GHPS** [comment]
Well - this bug is quite annoying. More so since it not only affects upper 
case letters but all keys that require the Shift modifier key, e.g. "? ! > "

And since Autokey is such a useful and well written piece of software.

Funny enough the Control modifier works fine (as in "Ctrl-V")

Time to investigate more into the cause of the bug...

1) Qt4- vs. Qt5-Autokey source files

  The first guess is that the problem is caused by the switch from Qt4 to Qt5
  Using Kubuntu 14.04 and Qt4 everything worked fine, in Kubuntu 16.04 and Qt5
  all lower case letters have disappeared from the Autokey macros. 

  For its GUI Autokey-Py3 relies on a number of py-files (in src/lib/qtui/) 
  that were converted from the original UI files (in uic/) with the help of pykdeuic4.
  These files have been generated five years ago - the idea lies at hand that they are
  outdated. Using pykdeuic4-3.5 (from python-kde4-dev) gives fresh Qt4 files for
  the GUI and after a number of small changes Autokey starts without problem.

  But the modifier bug is still present.

2) Python 3.3/3.4 vs. Python 3.5

  So it seems that the handling of modifiers inside of Autokey is broken, 
  perhaps due to the switch to Python 3.5. Luckily enough Autokey has the "--verbose"
  command line option which enables logging to console. This reveals that 
  sending keys is initiated by "iomediator" but handled by "interface" which 
  then uses the event interface of the X subsystem (no Qt routines here).  

  Adding a number of logging statements made the call order clear: 
  iomediator - Send via event interface -> interface - sendKey  -> interface - sendKeyCode -> interface - sendKeyPressEvent. 

  In this process the modifier keys (Shift is "1") are handed down to the lowest level correctly. 

  Autokey is quite innocent that the modifier handling is broken.

3) Python3-xlib vs. python-xlib

  So the culprit has be on the event handling side - the xlib library.

  Years ago LiuLang ported the original xlib library (https://github.com/python-xlib/python-xlib) 
  to Python3 (https://github.com/LiuLang/python3-xlib).
  Autokey-Py3 relied on the latter which hasn't seen an update since November 2014.
  Meanwhile python-xlib was ported to Python 3 and is under continuous development.

  Uninstalling python3-xlib and installing the official python-xlib seemed to be 
  a good idea to check if the older library was malfunctioning with Plasma5. 

  Unfortunately the bug is still present after the upgrade.

4) Python-xlib send_event

  Evidences are now pointing towards python-xlib as the core of the problem.
  Autokey calls send_event in Xlib/xobject/drawable.py - not much of the 
  code there to call "request" can go wrong. Even the modifiers are preseved correctly.

  The easiest way to test the send_event functionality of python-xlib was to
  use the small Python utility "pykey" by Akkana Peck found on 
  http://www.shallowsky.com/software/crikey/ (Python port in the middle of the page).

  By default this utility uses the fake_input method of XTest so "UseXTest = False"
  has to be set to enable the send_event methods.

  And, voila, while modifiers worked using XTest they stopped working with
  send_event.

  pykey Test
  -> test

[UPDATE 1]
5) Plasma5

  Two conclusions lie at hand: 1) There is a problem between the python-xlib library and Plasma5
  handling the Shift modifier. 2) There is a problem in Plasma5 since python-xlib
  is only a thin interface layer between Python and X.

Let's check if python-xlib causes the problem by using crikey - the C original of
pykey (available on the same page). After turning off XTest (UseXTest=0) crikey
gives the same results as pykey:

crikey Test
-> test
crikey !
->  1

Second check: Use the virtual keyboard xvkbd. To use the send_event-method start 
xvkbd -xsendevent.

Pressing Shift-A ("A") results in "a". Bingo!

[UPDATE 2/3]
6) Qt5

Step back: What applications are affected by this bug?
1) Qt5-KDE-Applications (e.g. Kate) under Plasma5
2) Qt5-KDE-Applications (e.g. Konsole) under Non-Plasma Window Managers like xfce (Gtk+) 

Not affected are:
1) Qt4-KDE-Applications (e.g. Okular at the moment)
2) Gtk-Applications (e.g. Thunderbird)
3) Chromium
4) LibreOffice

Conclusion: Currently there seems to be a problem introduced in Qt5 handling the Shift modifier
in the send_event routines.

Sadly enough there is nothing Autokey-py3 can do to fix this bug.

But there is hope: The fake-input routines from xtest have worked fine in every test.
A work around could use the already present __fakeKeypress functions in 
interface/__sendString to set the Shift modifier correctly and send the respective keys.

**Comment by fodiator** [comment]
THX for this well elaborated answer!
Could/would you place bug-reports within the mentioned/affected dev-teams?

**Comment by RaymiiOrg** [comment]
@GHPS That's an impressive bug chase you did, thank you. The workaround I now use is not use QT applications when I need text expansion, sadly...

**Comment by GHPS** [comment]
> The workaround I now use is not use QT applications when I need text expansion, sadly...

Well - as far as I can see it's not the Qt side of the application that causes the problem. 
It's more likely related to Plasma5.

Which brings me to the question: Has anybody this kind of problem (with the Shift modifier in
pasting keys) and is NOT using Plasma5?

**Comment by RaymiiOrg** [comment]
Yes, I do also have a workstation that uses XFCE as its main desktop, but with Konsole installed (Arch). XFCE terminal works correctly and Konsole has the issue.

**Comment by GHPS** [comment]
@RaymiiOrg thanks for the info - I updated the initial posting.

**Comment by ghost** [comment]
Any update or fix regarding this bug?

**Comment by GHPS** [comment]
Well - I've filed a bug report for Plasma5: https://bugs.kde.org/show_bug.cgi?id=372554

[Update]
And for Qt5: https://bugreports.qt.io/browse/QTBUG-57296

**Comment by ghost** [comment]
The bug seems to be fixed in qt5 5.7.1. Thank you!

**Comment by troxor** [comment]
Thanks @GHPS for the diligence with investigating this bug! I started #56 which hopefully should lead to a resolution.

**Comment by GHPS** [comment]
Just checked against Plasma 5.9.0 with Qt 5.7.1 (neon-devedition-gitstable-20170201-1047-amd64): 
Bug is fixed.

**Comment by troxor** [comment]
Thanks for your vigilance @GHPS. Does the GTK frontend still work in Qt applications?

**Comment by jnich3ls0n** [comment]
Hey all, I thought I replicated this issue running build 0.93.10 using autokey-gtk and xfce but it was user error in my case.  I had the following results:

Phrase: This is my test1 phrase!
Abbreviation: ^test1
Output: this is my test1 phrase!

After digging through the code I realized that my specific problem was the result of the phrase's abbreviation setting: Match phrase case to typed abbreviation.  This needs to be unchecked to always preserve the original format.  When checked, ^test1 forces the phrase to all lowercase and ^Test1 results in the desired format.

Hopefully this helps anyone who is here because of a similar experience.

**Comment by luziferius** [comment]
@troxor This is fixed upstream, could this be closed?

**Comment by GHPS** [comment]
Yes - the issue is fixed. In upstream and mainstream - Kubuntu 18.04 LTS for example.

**Comment by Galicarnax** [comment]
Just installed AutoKey in Xubuntu 18.04, using XFCE4 desktop. Spent an hour trying both autokey-gtk and autokey-qt (installed from repository with apt-get, autokey version 0.95.1). Tried all combinations of options for abbreviations. Nothing. All phrases are inevitably converted to lower-case.

**Comment by Galicarnax** [comment]
Ok, I found that this behavior is application-specific. For most apps it works fine - phrases are pasted just as they've been written in the autokey settings. But if I use the same abbreviation in Mathematica notebook, all phrases are converted to lower case. I failed to find any relevant settings in Mathematica itself. Any hints how this might be fixed? (Actually, I want to simplify the input of special Mathematica symbols. For example, instead of typing Esc + a + Esc to obtain the Greek alpha as usually done throug Mathematica notebooks, I would like to press a + Tab, so that it would paste \[Alpha]. The problem is that it pastes \[alpha], and this does not understood by Mathematica).

**Comment by luziferius** [comment]
@Galicarnax Then Mathematica seems to dislike the way AutoKey generates key presses.
Try to use the clipboard pasting modes. These use the system clipboard to expand phrases instead of typing the letters.

**Comment by oud23** [comment]
Hey.  Sorry to resurrect an old thread, but this issue has appeared again.  Currently using Autokey gtk 0.95.9 on Mint 19.3 and it has trouble entering capitals and symbols (such as curly braces) on certain apps (Notepadqq v1.4.8 in my case, which I believe is based on Qt).  Pasting via CTRL-V seems to work fine, but in a code editor this can be annoying because your code blocks come out misaligned.  I've tried installing the Qt debian package with and without the GTK debian package; neither method fixes the problem.  I previously used Autokey with Notepadqq on Mint 19.2, with no problems.  Was a fix for this ever created?

**Comment by luziferius** [comment]
@oud23 Can you test if it happens with other keyboard automation tools?
See https://github.com/autokey/autokey/issues/20#issuecomment-243875781.
For example start the virtual keyboard xvkbd using `xvkbd -xsendevent`. Then press `<Shift>+A` on the virtual keyboard. If that prints a lower case `a`, then this Qt Bug https://bugreports.qt.io/browse/QTBUG-57296 reappeared.

**Comment by oud23** [comment]
@luziferius I tried xvkbd with Notepadqq.  If I start it with just "xvkbd" it prints capitals fine.  If I use xvkbd -xsendevent, it won't print capitals or symbols using the Shift key.  Seems to work fine when sending input to a terminal.  Plain xvkbd seems to work fine when printing to Xed, but xvkbd -xsendevent won't send any input to Xed at all, capital or otherwise.

**Comment by luziferius** [comment]
@oud23 Thank you for testing. 

> If I use xvkbd -xsendevent, it won't print capitals or symbols using the Shift key. Seems to work fine when sending input to a terminal. 

Then it is definitely the aforementioned bug in Qt again. `xvkbd -xsendevent` uses the same X11 protocol extension than AutoKey to produce output.
If `xvkbd -xsendevent` fails in a similar way, then this is nothing AutoKey can fix, other than by using a different protocol/API for key press generation. Or reporting to the Qt Folks that it is broken _again_.

> Plain xvkbd seems to work fine when printing to Xed, but xvkbd -xsendevent won't send any input to Xed at all, capital or otherwise.

Another known limitation: Many applications using pure X11 toolkit disregard the events generated using XSendEvent. E.g. It won’t work in XSane and XTerm either.

Edit: I’ve added Xed to the list of known not-working applications here: https://github.com/autokey/autokey/wiki/Known-limitations#interacting-with-pure-x-toolkit-applications-does-not-work

**Comment by kreezxil** [comment]
Amazingly this is still a thing.

![image](https://user-images.githubusercontent.com/3880072/79369770-1b774c80-7f17-11ea-8f76-5720355ad08a.png)
![image](https://user-images.githubusercontent.com/3880072/79369815-2fbb4980-7f17-11ea-8d48-60153747e185.png)
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.2
Kernel Version: 5.4.31-1-MANJARO
OS Type: 64-bit
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 31.3 GiB of RAM
```

**Comment by elprott** [comment]
Hi All,

I found a "worksforme" kind of type workaround:
-It works under Fedora 32, and plasmashell 5.18.5

Use chr(ord()). Awkward, but seems to work:

```python
str_out = chr(ord('H')) + 'i,\n' + chr(ord('A')) + 'll'
keyboard.send_keys(str_out)
```

Tried in Sublime Text, Kate, Libreoffice Writer and in EditPad Pro (running under Wine)
Did not try with special chars.

**Comment by elprott** [comment]
`str_out = chr(ord('H')) + 'i,\n' + chr(ord('A')) + 'll'
keyboard.send_keys(str_out)`

**Comment by josephj11** [comment]
@elprott I believe you if you say it works, but how is chr(ord('H')) any different from 'H'? Isn't that an identity function? Could it have something to do with using a variable instead of a literal? 

Does running this with and without  the function produce identical AutoKey traces?

Is there anything going on here with non-EN-US character sets? keyboard.send_keys() doesn't like them to start with.

Maybe your function is reducing a multibyte character to an ASCII or UTF-8 one. I don't work with non-EN-US character sets, so I don't know the ins and outs of them. Is chr(ord('H')) == 'H'?

**Comment by elprott** [comment]
Hi Joseph,

You are right,
chr(ord('H')) == 'H'

chr(NNN) seemed to work, so it is convenient for me to use the ord call instead of knowing any given char's code number.
I don't know exactly why it works, maybe I had a hunch that this way the needed character somehow would be decoupled from the current keyboard layout, so maybe you are right, it has to do with using variables instead of (keyboard) literals.

-I also use it for some non-EN/US characters, because mostly I use the en-US keyboard layout, except in emails written in my native language. (Central Europe, so didn't tested it with utf chars outside of the extended ascii table)

Telling the truth, I'm only beginner-intermediate level at programming in Python, and didn't bother/have time to delve into the inner workings of Autokey, and did not test it further.
This clumsy workaround seems to work for me, that's why I shared in hope to be useable for others too.

**Comment by josephj11** [comment]
> Well - I've filed a bug report for Plasma5: https://bugs.kde.org/show_bug.cgi?id=372554
> 
> [Update] And for Qt5: https://bugreports.qt.io/browse/QTBUG-57296

These two bug reports are closed as fixed.

**Comment by josephj11** [comment]
@kreezxil and @BlueDrink9 Is this still a problem or can this be closed?

**Comment by kreezxil** [comment]
> @kreezxil and @BlueDrink9 Is this still a problem or can this be closed?

from me I would count it as closed. i'm on the latest autokey and the latest Manjaro Linux as of this date, these are the specific details:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.18.19-3-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 23.4 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2
Manufacturer: MSI
Product Name: MS-7693
System Version: 5.0
```
![image](https://user-images.githubusercontent.com/3880072/197402717-b98bf61c-f07a-4a06-971e-f2e1e441cfa8.png)
And I have not had any issues since confirming the bug and upgrading to the betas way back then and when.
