### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by y2kbadbug** [autokey/autokey#204]
Hello,

I've created a FreeBSD port for Autokey.  I have submitted a bug report to FreeBSD to get this added to the main ports tree, however, that can take awhile.

Until it is approved, consider things to change, I just wanted to open this ticket to provide you guys with the progress on getting the port added.

If you wish to try the port out, I have uploaded it here: https://github.com/y2kbadbug/freebsd-ports-y2kbadbug/tree/y2kbadbug/deskutils/py-autokey

If there is anything I may have missed, please let me know.

The bug report for the port is here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232801

**Comment by luziferius** [comment]
### Repository link
The link in https://github.com/y2kbadbug/freebsd-ports-y2kbadbug/blob/y2kbadbug/deskutils/py-autokey/pkg-descr is outdated, you can replace it with https://github.com/autokey/autokey (just remove the `-py3` in the URL)
### GUI specific modules and packages
If you intend to only ship one GUI flavour instead of both simultaneously, you can trim the installation a bit more:
https://github.com/y2kbadbug/freebsd-ports-y2kbadbug/blob/a6c9ecc1d17ec1d833c51b566ac6ed3236472cb9/deskutils/py-autokey/Makefile#L45-L53
For a pure PyQt5 build, also remove `lib/autokey/gtkapp.py` and the `lib/autokey/gtkui` package.
For a pure GTK build, also remove `lib/autokey/qtapp.py` and the `lib/autokey/qtui` package.
The Debian packages do this. The Debian package build process packages the GUI specific files into `autokey-gtk` and `autokey-qt` and the rest into `autokey-common`.
### PyQt5 build dependencies
The build process will use the `pyrcc5` PyQt5 resource compiler to compile Qt Designer UI files and icons into a binary resource. Currently, the build process always ships the uncompiled files, because there were problems when users didn’t have `pyrcc5` installed. (The supposed-to-be transparent fail-over did not work reliably.) If you use `pyrcc5`, you can additionally remove `lib/autokey/qtui/resources` from the final package, because autokey-qt will prefer `lib/autokey/qtui/compiled_resources.py`, if it is available.
### Qt5 dependency
Are you sure, this (https://github.com/y2kbadbug/freebsd-ports-y2kbadbug/blob/a6c9ecc1d17ec1d833c51b566ac6ed3236472cb9/deskutils/py-autokey/Makefile#L37) is the right thing?
The PyQt5 GUI only relies on PyQt5 and not on Qt5, which is the C++ library. Are you sure you need to specify `qt5`? The PyQt5 dependencies should take care of pulling the C++ libraries.

### Shebangfix?
https://github.com/y2kbadbug/freebsd-ports-y2kbadbug/blob/a6c9ecc1d17ec1d833c51b566ac6ed3236472cb9/deskutils/py-autokey/Makefile#L23
What is that shebangfix? Is that referring to `setup.py` missing `#!/usr/bin/env python3`? That will be fixed in the next release.

**Comment by y2kbadbug** [comment]
A lot of changes have been made since I originally opened this issue and the port has been approved and added to the official FreeBSD ports tree.

Review:
https://reviews.freebsd.org/D18407

Commit:
https://svnweb.freebsd.org/ports?view=revision&revision=488737

I've attached my build log for reference.
[py36-autokey-0.95.4.log](https://github.com/autokey/autokey/files/2717520/py36-autokey-0.95.4.log)

I'm not using pyrcc5.  So that part is irrelevant.  It didn't seem like a requirement.  If it is let me know.

For shebangfix:
https://www.freebsd.org/doc/en/books/porters-handbook/uses-shebangfix.html
FreeBSD does not install Python as python3, it uses its version.  So shebangfix would update the file to be `#!/usr/local/bin/python3.6` (example).  It's not something wrong with the code, it's just a way FreeBSD does things.

Having the qt:5 use flag is recommended as the software uses qt5.
All it does is give access to QT5 variables in qt.mk, it doesn't actually install any dependencies unless you use USE_QT

The stuff you mentioned about GUI specific options I will take into consideration for the next release and port commit.

Thank you for the support and insight!

As the port is completed and added, this can be closed if you wish.

**Comment by y2kbadbug** [comment]
I cleaned up the port and did a revision, I was actually missing the qt flag for PYQT.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234533
https://svnweb.freebsd.org/ports/head/deskutils/py-autokey/Makefile?view=markup&pathrev=488832
