### ISSUE TITLE
[Personal Issue] How to install latest version?

### ISSUE THREAD

**Issue by tecosaur** [autokey/autokey#238]
Autokey-py3 seems to still suffer from [this](https://github.com/autokey/autokey/issues/153) issue.

It would be nice if this could be fixed as this is causing me some major headaches atm.

**Comment by tecosaur** [comment]
Ooops I checked the version I've got from me repo (linux, solus distro) and it seems to be a bit behind (v0.93.10) so that would cause it...

Now I've just got to find a way to get the latest version.

**Comment by luziferius** [comment]
OK, If it still happens, after you updated to the newest version, the delay length I guessed are insufficient on some systems. If so, just comment again. 

You want to:

- Uninstall the version you installed, if it is installed using your package manager.
- Make sure to install the dependencies using your package manager, so that it does not automatically remove them. If you intend to use the Qt interface, you need the PyQt5 packages, as described in the README.
- Install using `pip3`. Use *one* of those ways:
  - `pip3 install autokey` as indicated in the readme to install the version uploaded to [PyPi](https://pypi.org/project/autokey/).
  - Or download and extract a source archive snapshot from the [GitHub releases page](https://github.com/autokey/autokey/releases), then use `pip3 install .` from within the extracted archive.
  - Or install AutoKey directly from the git repository: `pip3 install git+https://github.com/autokey/autokey`. This will install current git HEAD from the master branch, containing some additional bugfixes that are not included in the current version, but will go into the next released version. (fixes for #113, #197, #229)

**Comment by tecosaur** [comment]
If I install via something like `python3 -m pip install autokey` will that also add the gui _'app entry'_? (not sure quite what to call it offhand) 
![screenshot from 2018-12-24 19 44 35](https://user-images.githubusercontent.com/20903656/50405972-716d3180-07b4-11e9-9b00-9996749e4661.png)

Thanks for the detailed mini-guide :)

**Comment by luziferius** [comment]
Running pip3 just calls `setup.py` several times to build an archive and install it. Here, `setup.py` defines where the `.desktop` files providing the ‘app entry’ and icons are placed during an installation. Normally, it is installed below `/usr/local`, where your system should pick them up:
https://github.com/autokey/autokey/blob/cbc0408b9397c14e2e4a2d399901719d3b3edb39/setup.py#L139-L162
So It *should* add the files to appropriate places.
But you can’t choose between GUIs, it just installs the files for both. (They are small.) You may want to remove the `.desktop` file you don’t want.

**Comment by tecosaur** [comment]
I see. Interestingly with `sudo python3 -m pip install autokey` and `sudo pip3 install autokey` I encountered the following:

```log
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4h2wzrrc/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-eagcu1pc/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-4h2wzrrc/dbus-python/
```

Would you have any clue what's going on?

**Comment by luziferius** [comment]
In short: To just get it to install on your side, download one of the `Source code` archives from the [GitHub release page](https://github.com/autokey/autokey/releases/tag/v0.95.4), extract it and manually remove the `dbus-python` dependency from the [setup.py file, in line 169](https://github.com/autokey/autokey/blob/v0.95.4/setup.py#L169), like the [Arch Linux AUR patch](https://aur.archlinux.org/cgit/aur.git/tree/requires.patch?h=autokey-py3) patch does. Then install from there using `pip3 install .`.

For further reading:

It seems pip3 does not find the `dbus` Python module on your system. It then downloads them from PyPi and tries to compile the needed C library bindings. Those are needed to call C library functions to interface with the dbus system. The compilation fails because of missing C/C++ header files, a missing  compiler (`gcc`) or similar.

In general, pip3 should not download the dbus bindings from PyPi at all, if those are supplied by the system. Installing them from PyPi may in fact be dangerous, because it shadows additional plugins the system version may have. For example, it breaks all PyQt4/5 applications using the Qt dbus plugin, like the HPLIP software suite.

This is an issue that sometimes arises on random machines. I think I’ll follow the [Arch Linux AUR patch](https://aur.archlinux.org/cgit/aur.git/tree/requires.patch?h=autokey-py3) and simply remove dbus-python from the dependency list for the next release.
