### ISSUE TITLE
GUI not starting

### ISSUE THREAD

**Issue by ProkopRandacek** [autokey/autokey#244]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.2-1.fc29

Used GUI (Gtk, Qt, or both): Gtk

Installed via: dnf

Linux Distribution: Fedora 29

## Summary

Interface won't shows up.

## Steps to Reproduce (if applicable)

- $ autokey-gtk --verbose

## Expected Results

- Application should start

## Actual Results

 - No interface created.

```
https://pastebin.com/XyNx27Cd
```

## Notes

![screenshot from 2019-02-01 20-44-51](https://user-images.githubusercontent.com/40907224/52146540-4f44ba00-2664-11e9-8a9a-3bd61a2f75af.png)

**Comment by luziferius** [comment]
If it does not obviously crash, but shows infos about key presses in the console window, it runs and works normally.
(It is normal that it does not detach from the current shell.)

Because AutoKey is a background application, it does not open the GUI by default. 

Try the `--configure` switch or click the tray icon to show the GUI.


This should be documented better, I think I'll add a section to the README.

**Comment by luziferius** [comment]
This is placed in the FAQ in the wiki.
