### ISSUE TITLE
Abbreviations not fully deleted in Firefox

### ISSUE THREAD

**Issue by BetaRavener** [autokey/autokey#253]
## Classification:
Bug

## Reproducibility:
Sometimes

## Version

AutoKey version: 0.90.4

Used GUI: Qt
Installed via: APT.

Linux Distribution: Ubuntu 16.04

Firefox: Firefox Quantum 64.0

## Summary
Abbreviations won't get fully deleted after pressing trigger key, leaving some characters in the input. I'm using keyboard method for pasting but Ctrl+V behaved same.

## Steps to Reproduce (if applicable)
* Set abbreviation for a phrase
* Write the phrase in input field

## Expected Results
Abbreviation `greet` for phrase `Hello` should leave just `Hello` in input field. 

## Actual Results
Sometimes the result is `gHello` or `grHello`. Happens on ~80% cases.

## Notes
This seems to be isolated to Firefox. I'm using abbreviations for user name during login and it's bit of a pain to have to correct it on occasion. I've tried using abbreviation in Gedit and Terminal and it seems to not happen (or much more rarely and I haven't observed it yet).

**Comment by luziferius** [comment]
This has the same cause as #151
It is probably a bug in the X server, GTK, or the input handler in Firefox and LibreOffice.
It only happens on certain systems and configurations. Only Firefox and LibreOffice are reported to behave like this. If you try, you’ll probably reproduce it in LibreOffice, too.

But if it happens, even a programmatically inserted one second delay between each key press does not fully fix this.
There is definitely something shady going on in the receiving applications. You may try a slowed down version. The discussion in #151, starting with https://github.com/autokey/autokey/issues/151#issuecomment-459950222 might be an interesting read.

**Comment by BetaRavener** [comment]
Thanks, I missed that one while going through open issues. The idea of going with scripts gave me a few ideas to test. Will report on Monday if I manage to create something reliable.

**Comment by josephj11** [comment]
0.90.4 is almost seven years old and unmaintained. You should really upgrade if at all possible.

Unfortunately, Debian has no one assigned to updating their AutoKey package and most Debian-based distributions get AutoKey from them so you still get 0.90.4 when you use their repositories.

To upgrade:

If you have phrases and scripts, you need to save them:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.

If you are using Ubuntu 18.04 or a derivative, you can use our pre-built deb files.

All our current deb files are built for Ubuntu 18.04. If you are using a different distro, install using pip. See below.

AutoKey releases are available here:

https://github.com/autokey/autokey/releases/

Select the one you want and then download the common and gtk debs to a directory on your system

Change into that directory (in a terminal) then

To install it on a Debian-based system, use the following:

sudo dpkg --install autokey-common_VERSION_all.deb autokey-gtk_VERSION_all.deb

(substituting the version you downloaded for "VERSION".)

They need to be installed at the same time and dpkg will get it right while apt might not.

If you're using the QT front end, you can download and install that instead of (or in addition to) the GTK version.

Otherwise, you need to install using pip.

Follow the instructions here:
https://github.com/autokey/autokey/wiki/Installing#pip-installation
That will get you up to our current version.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by BetaRavener** [comment]
Thanks! It didn't occur to me that I might be running such an old version when I download from repository. As a suggestion, there could be current version tag next to IRC, Chat and StackOverflow in readme. I'll install new version and see if the problem persists, as the new comments in other open issue are also just few days old.

**Comment by BetaRavener** [comment]
So I've tried the new version and it seems to handle deletion in Firefox correctly. It has some problems with expansions using keyboard method (hapened that 1 letter of phrase was missing) but after switching to clipboard it was fine. 

As side note on what I was planning to do. Script that would `<ctrl>+<shift>+<left>` select the text until next white space, ~`<delete>`~ you don't even need to delete, copy phrase into clipboard and paste. This way I would prevent any counted/repeated key presses and hopefully workaround the issue. But seems like it won't be needed anymore.
