### ISSUE TITLE
v0.95.5 seems to have broken AutoKey for me

### ISSUE THREAD

**Issue by prosoitos** [autokey/autokey#261]
## Classification:

Bug

## Version

AutoKey version: 0.95.6-1
**edit:** 0.95.5 has the same behaviour

Used GUI (Gtk, Qt, or both): Gtk

Installed via: (PPA, pip3, …). autokey-py3 from the AUR

Linux Distribution: Arch Linux

## Summary

It seems that the update to v0.95.5 broke AutoKey for me (unless I am missing something). And the update to 0.95.6 did not fix it.

I can launch AutoKey and open the window, but none of my scripts nor phrases work anymore (nothing happens). I also cannot kill the application. In order to relaunch it (after moving to a new version), I have to reboot. This had previously happened to me when I had written faulty scripts that made AutoKey crash.  Except this time, it is not due to a bad script.

Reverting to v0.95.4 returned AutoKey to a normal behaviour and everything working.

**Comment by prosoitos** [comment]
Actually, it seems that it is the 0.95.5 update that broke it: downgrading to it did not solve my problem while downgrading to 0.95.4 did solve it (so I updated the previous post).

**Comment by luziferius** [comment]
0.95.5 only lived for about two days. It contained a bug (#254) that unfortunately slipped through the testing and broke AutoKey for many users. That’s why the .6 follow-up was issued shortly after the reports arrived here.

A debug level log excerpt may be helpful. Just create a Phrase with some content, add a trigger to it.
Then quit AutoKey, and start it with the `--verbose` flag and capture all output. Like `autokey-gtk --verbose | tee autokey.log.txt`. Just start AK like this, try to trigger something, then exit again. Then either post the log file content into a block quote or attach it as a file here. 

Neither abbreviations nor hotkeys work?\
The phrase configuration for a non-triggered Phrase may be helpful. (That is the .json file that is alongside the Phrase text file in the autokey data directory, `~/.config/autokey/data/`). If I get the `.<phrase_name>.json` file content, I can try to configure a phrase to the same configuration and reproduce it on my side. It will be used to write a test case, so that it can’t happen again.

Neither sending SIGTERM nor SIGKILL terminates the autokey process?\
That always helped here, even after fully deadlocking AutoKey, for example triggered in #229.

Then one of the bug fixes in this list https://github.com/autokey/autokey/milestone/1?closed=1 is at fault, here. I suspect you triggered another issue in the new case folding logic, implemented for https://github.com/autokey/autokey/issues/197

**Comment by prosoitos** [comment]
Sorry for my slow replies. I have very little time right now. I will try to help as soon as I have a bit of time, but for now quickly:

> Neither abbreviations nor hotkeys work?

Indeed

> Neither sending SIGTERM nor SIGKILL terminates the autokey process?

Actually, the problem is probably on my end: I just realized that I simply cannot kill AutoKey cleanly, even when everything is fine (bugfree version and no bad script). SIGTERM and SIGKILL kill AutoKey, but leave behind a defunct pid:

```sh
pidof autokey-gtk
```
does not return anything, but

```sh
ps ax  | grep autokey-gtk
```
returns a defunct pid.

And when I try to restart AutoKey, I get the following error:

```
AutoKey is already running as pid xxx but is not responding

org.freedsktop.DBus.Error.ServiceUnknown: The name org.autokey.Service was not provided by any .service files
```
Not sure why that is and I guess I will have to figure this out (is it possible that some bad setting on my side is the reason why AutoKey is still broken for me while it isn't anymore for other users??).

I start AutoKey automatically with an entry in my `.xinitrc` file, but that shouldn't matter I guess. So as things are, when I kill AutoKey, there remains a defunct pid that I cannot kill. So in order to relaunch AutoKey, I have to reboot. This makes trouble-shooting quite tedious as any test takes the time of a full reboot.

As for the .json files, here is an example:

```json
{
    "type": "phrase",
    "description": "mhb",
    "modes": [
        1
    ],
    "usageCount": 0,
    "prompt": false,
    "omitTrigger": false,
    "matchCase": false,
    "showInTrayMenu": false,
    "abbreviation": {
        "abbreviations": [
            "mhbf"
        ],
        "backspace": true,
        "ignoreCase": false,
        "immediate": true,
        "triggerInside": true,
        "wordChars": "[\\w]"
    },
    "hotkey": {
        "modifiers": [],
        "hotKey": null
    },
    "filter": {
        "regex": null,
        "isRecursive": false
    },
    "sendMode": "kb"
}
```
One thing that I always do for phrases is to have them triggered automatically. But that shouldn't be the problem as it wouldn't explain why my scripts aren't working either.

---
Note:

> The phrase configuration for a non-triggered Phrase may be helpful.

None of the phrases do trigger. It is a general problem. AutoKey simply does not do anything anymore.

---
Note 2 about the DBus error:

I am not using any Desktop Environment (I only have a Window Manager). I don't know anything about DBus and it is very possible that something is simply not set in my system. Something that has not affected me so far, but which creates problems to kill AutoKey (any version) and which now creates additional problems with the new version which prevent it from running properly. This is only a very wild guess though and there may be no link between my problem killing AutoKey and the fact that the new version does not work for me. I need to learn about DBus...

**Comment by luziferius** [comment]
Thank you for your response and feedback.

> Sorry for my slow replies. I have very little time right now. I will try to help as soon as I have a bit of time, but for now quickly:

No problem, take your time

> SIGTERM and SIGKILL kill AutoKey, but leave behind a defunct pid:

This means, the AutoKey is left as a zombie process (https://en.wikipedia.org/wiki/Zombie_process).
Processes are kept in the process table, until the parent process requests the exit status. If AutoKey stays, it means the parent process (that spawned the AutoKey process) does not care and does not clean up. You may want to use some other mechanism to start AutoKey.

Can you use the built-in autostart mechanism? If your system evaluates `~/.config/autostart`, you can just tick the autostart option in the settings. AutoKey will then place a .desktop file in there for your system to start at login.

> And when I try to restart AutoKey, I get the following error:
> `org.freedsktop.DBus.Error.ServiceUnknown: The name org.autokey.Service was not provided by any .service files`

AutoKey uses the DBus inter process communication service to offer it’s service to other programs. You can use it to run scripts or expand phrases directly from other programs.
For example, you can issue `dbus-send --session --type=method_call --dest="org.autokey.Service" "/AppService" "org.autokey.Service.show_configure"` from the command line to open the AutoKey GUI. Scripts and Phrases can be accessed in a similar way.

The error message states that no process registered the interface, although there should be one, because the AutoKey process is still running. But since it is dead, you can remove the PID-file, which will allow another instance to start.
The location depends on the system. AutoKey follows the XDG standards, so it should be in `/run/user/<your_user_id>/autokey/`. To definitely find it, open a `python3` shell, then `import autokey.common` and then `print(autokey.common.LOCK_FILE)`

> As for the .json files, here is an example:
> [snip]


I can use this to add a new test case, if this particular configuration is not already covered. It will help to improve the test coverage.

**Comment by prosoitos** [comment]
Thank you so much @luziferius for taking the time to explain to me the cause of this zombie process. I am still a noob in many ways and it was extremely helpful.

Removing AutoKey from my `.xinitrc` file and starting it from the cli indeed does not result in any zombie process staying behind. There must be something improper in my system setup because I should be able to start applications through the `.xinitrc` file without running into bad cleanup. I am not sure what it is, but will try to find out.
 
I do not use any desktop environment (only a window manager) and my .desktop files are thus not read. So the autostart setting does not work (unless I install a desktop environment, which maybe I should do. I have been pondering this lately for other reasons).

In the meantime, I will start AutoKey from the cli and it will allow me to troubleshoot the current issue much more easily since I won't have to constantly reboot.


> I can use this to add a new test case, if this particular configuration is not already covered. It will help to improve the test coverage.

Great! This is my most common configuration, so I am very happy to hear this! :slightly_smiling_face: 


> you can remove the PID-file, which will allow another instance to start.
The location depends on the system. AutoKey follows the XDG standards, so it should be in `/run/user/<your_user_id>/autokey/`. To definitely find it, open a `python3` shell, then `import autokey.common` and then `print(autokey.common.LOCK_FILE)`

Yet more extremely useful information! Thank you so much. This is very handy to know. My AutoKey process is here:

```sh
/run/user/1000/autokey/autokey.pid
```

> AutoKey uses the DBus inter process communication service to offer it’s service to other programs. You can use it to run scripts or expand phrases directly from other programs.
For example, you can issue `dbus-send --session --type=method_call --dest="org.autokey.Service" "/AppService" "org.autokey.Service.show_configure"` from the command line to open the AutoKey GUI. Scripts and Phrases can be accessed in a similar way.

I see. Very cool! :slightly_smiling_face:

**Comment by prosoitos** [comment]
I made some progress in trouble-shooting the problem:

To my total surprise, I realized that AutoKey 0.95.6 runs perfectly fine if I launch it from the cli. However, as I mentioned earlier, if I launch it at startup from my `.xinitrc` file, it runs (there is a process with an id, and not a zombie process), however, it does not respond to anything (no script nor phrase).

Now, I found a workaround for my cleanup problem and that might bring some light into the current issue:

I didn't want to install a full DE only to be able to run `.desktop` files, but I found this great program https://github.com/jceb/dex.

Now, I can put `dex -a` in my `.xinitrc` file and `.desktop` files in autostart folders are read when Xorg is launched.

This solves the problem of cleanup (no more zombie process if I kill AutoKey), but this issue is the same: AutoKey launched this way has a pid, but no reaction.

Running `dex -a` from the cli works fine and launches a working version of AutoKey.

So the problem seems to be that AutoKey, if launched from a `.xinitrc` file, does not work anymore while it used to be no problem until version 0.95.4.

And I think that the fact that launching it through `dex` in the `.xinitrc` file leads to the same issue (while solving the cleanup problem) means that it has nothing to do with how it is launched (so nothing to do with the `.xinitrc` file itself). I think it is a question of timing. No? 

Maybe it only works now if launched after other processes have started, hence breaking something if it is launched too early as happens when launched through a `.xinitrc` file.

Of course, I could be totally wrong though. As I said, I am a noob. I'd be curious if this is reproducible. Maybe you can test it?

**Comment by prosoitos** [comment]
Note about the cleanup problem: I start many applications through my `.xinitrc` file. And I can kill them all without any issue. AutoKey is the only one which is not cleaned up. So the fact that I have to use `dex` and a `.desktop` file to solve this might already be a sign of something weird going on, even if it was not leading to major issue until the latest updates???

**Comment by prosoitos** [comment]
Since the problem only happens when AutoKey is started from my `.xinitrc` file, I had to put `autokey-gtk --verbose | tee autokey.log.txt &` in it to get a log when the problem happens.

One suspicious line:

```
Xlib.error.BadAtom: <class 'Xlib.error.BadAtom'>: code = 5, resource_id = 0, sequence_number = 540, major_opcode = 20, minor_opcode = 0
```

Full file here (with a few sections I cut and replaced by `[cut]`):

[autokey.log.txt](https://github.com/autokey/autokey/files/2867859/autokey.log.txt)

Note: when trying to expand phrases or run scripts, nothing else gets added to the log.

**Comment by luziferius** [comment]
`2019-02-14 18:38:22,552 DEBUG - service - Window visible title: 'urxvt', Window class: 'urxvt.URxvt'`
+
`Xlib.error.BadAtom: <class 'Xlib.error.BadAtom'>`

This looks strangely like #257. There is a similar situation: Arch Linux, urxvt, `Xlib.error.BadAtom` errors and non-working Phrases.

Can you try running the current git master branch? It currently contains v0.95.6 + the one patch for #257. This may resolve both this and #240.
You can run AutoKey directly from a cloned git repository, see the Zero-installation method in the README.

(The logging output the current git master generates is a bit messy, because it still logs many stack traces coming from BadAtom errors. This needs to be tuned down in the future but shouldn’t affect functionality for now.)

**Comment by prosoitos** [comment]
I only have issues when launching it from `.xinitrc` though. I have no problem otherwise.

I'll try to launch the master branch from the `.xinitrc` file and report.

**Comment by prosoitos** [comment]
It works :slightly_smiling_face: 

It does not help at all for #240 however. But I can now launch it from within the `.xinitrc` file and have it run scripts and phrases fine.

**Comment by prosoitos** [comment]
Closing this now.

Thank you for the very quick help @luziferius! Much appreciated! And the zero-installation is really easy and cool! Really love this program :slightly_smiling_face:

**Comment by luziferius** [comment]
Ok. I’m glad that it worked and you can use the new version now.
(The `.xinitrc` is just a plain shell script, right?) Then you can put something like this into it, to start the local checkout instead of the installed version:
```sh
pushd /path/to/autokey_clone/lib
python3 -m autokey.gtkui &
popd
```

 It looked like that it _might_ also help with #240. That’s why I mentioned it.

**Comment by josephj11** [comment]
I don't know much about how X11 works, but some of these issues almost (but not quite) sound like things that might happen if AutoKey launched by X11 is not owned by your user. The problem is that if that was the case, you'd have issues with anything else launched that way.

BTW, for killing AutoKey, `pkill autokey` is what I usually use. It's less steps and should normally get all instances if more than one exists.

**Comment by prosoitos** [comment]
> (The `.xinitrc` is just a plain shell script, right?)

Yes

> Then you can put something like this into it, to start the local checkout instead of the installed version:

```shell
pushd /path/to/autokey_clone/lib
python3 -m autokey.gtkui &
popd
```

I guess your method is probably more proper. What I put in it is a noob very basic line (just the code I would put in a cli), but it seems to work fine:

```sh
cd /path/to/autokey_clone/lib; python3 -m autokey.gtkui &
```

*edit: I see the point now. My method leaves my terminal emulator at the `/path/to/autokey_clone/lib` :slightly_smiling_face: (unless I add yet another `cd` at the end). So your method is definitely better and I'll use it instead. Thanks!*

*re-edit: actually, that also leaves me in that path. So I guess I'll go back to my code and add another `cd` at the end.*

*re-re-edit: I finally understood what was going on. Doing another `cd` behind the above code in `.xinitrc` doesn't help: the problem is that I am launching my terminal emulator with an AutoKey script. That's why it defaults to `/path/to/autokey_clone/lib` instead of `~` :smile: Passing an option in the script did the trick.*

> It looked like that it _might_ also help with #240. That’s why I mentioned it.

Oh, of course :slightly_smiling_face: I was just giving feed-back on it, but no worries!

> BTW, for killing AutoKey, `pkill autokey` is what I usually use. It's less steps and should normally get all instances if more than one exists.

I never use `pkill` and will look into it.

*edit: oh, I see. `pkill` saves me from having to look up the pid. But it is otherwise the same as what I was doing. So that doesn't change anything about my zombie process though, if AutoKey is launched directly from `.xinitrc`.*

**Comment by prosoitos** [comment]
> It looked like that it _might_ also help with #240. That’s why I mentioned it.

Actually, one thing that it did do is to reduce the freeze time after inserting accented characters! :slightly_smiling_face:
