### ISSUE TITLE
Feature request: Error message and Python major version number

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#262]
## Reproducibility: N/A

AutoKey version: 95.4

Used GUI (Gtk, Qt, or both):  Both

Linux Distribution: Linux Mint 19.1

## Expected Results.

Make: Please make the error message to be accessible by a button on the toolbar.
And please indicate the Python major version number on the 'About AutoKey' box.

**Comment by luziferius** [comment]
> Please make the error message to be accessible by a button on the toolbar.

What exactly do you mean with `the error message`. The error message dialogue for errors from Scripts? In other words: The dialogue you can access from `Tools`→`View script error`? If yes, it’s not a big deal to add it to the toolbar. Right of the `Run script` button seems to be a nice spot.


> And please indicate the Python major version number on the 'About AutoKey' box.

That sounds reasonable, I’ll put it onto the TODO for the next release.

**Comment by ineuw** [comment]
Thanks for your speedy reply. 

**"The dialogue you can access from `Tools`→`View script error`? If yes, it’s not a big deal to add it to the toolbar. Right of the `Run script` button seems to be a nice spot."** 

Yes, that is what I meant. I am new to Python and using Autokey to learn, but still make a make a lot of typos and errors, so I work with the AutoKey Main Window open and minimized,

**Comment by luziferius** [comment]
Ok. Both points seem reasonable, so I’ve enqueued the request for the next release.

By the way: You can access the script error dialogue via the tray icon context menu, too. If you use the GTK GUI (autokey-gtk), you have to keep the main window open for it to work, until #222 is resolved. (The entry is only shown if an error is logged.)
If you use the Qt GUI (autokey-qt), the feature is available too, since version 0.95.5.

All scripting errors are also logged in the console output. You can exit any running instance and then start a new instance from a terminal. If you use the `--verbose` flag, AutoKey will print all scripting errors, amongst other output, in the terminal window. You can then see all scripting errors without having to repeatedly access that dialogue.

**Comment by ineuw** [comment]
Thanks luziferius,

**Comment by josephj11** [comment]
@ineuw I'm a long term Python newbie. ;) What I've found very helpful is to take the parts of a script that don't need the AutoKey API and put them in an external file such as mytest.py and test them directly in Python. That's much easier because you can see everything they do and even add print statements for debugging. Once they work, you can put them back in AutoKey and add the API stuff.

**Comment by ineuw** [comment]
Much thanks for the great idea. Newbie you say?

ineuw

**Comment by luziferius** [comment]
@josephj11 One additional off-topic remark from my side: You can use unittest.mock.MagicMock() to fake the API objects ;)
It get’s a bit more complicated if you use the values returned by API functions and need to fake them, too. But if you don’t care about returned values, you can just throw in
```python3
from unittest.mock import MagicMock
keyboard = MagicMock()
mouse = MagicMock()
dialog = ...
```
and the scripts basically work outside of AutoKey, (without actual functionality, of course).

**Comment by shervinemami** [comment]
Thanks guys, these techniques (ways of seeing the error messages, and ways
of testing using normal Python) seem quite handy!

It would be useful if they are all listed as debugging methods in the
documentation. If they aren't already mentioned, can someone please add
them (or tell me where is the best place to add them, and I'll try adding
them myself)?

Cheers,
Shervin Emami.
http://shervinemami.info/

**Comment by josephj11** [comment]
@shervinemami One of these days, we have to reorganize the wiki. For now, this could go under Troubleshooting or maybe as a new topic such as debugging or programming tips. Anyone with a GitHub account can edit the wiki. If you want to, you can write a draft and share it with us first.

Come on over to our [list](https://groups.google.com/forum/#!forum/autokey-users) or [Gitter](https://gitter.im/autokey/autokey) for discussing things like this. Thanks.

**Comment by shervinemami** [comment]
Yeah sure, I'll write something up for the wiki. I don't want to join the
developer's list cos I might get hooked and I've already got too many
projects that take up my time as it is!

Cheers,
Shervin Emami.
http://shervinemami.info/

**Comment by shervinemami** [comment]
I pasted the tips you guys gave, into a new page [https://github.com/autokey/autokey/wiki/Script-Debugging](https://github.com/autokey/autokey/wiki/Script-Debugging). If you guys are happy with it, I'll add a link to it from another 1 or 2 wiki pages.

**Comment by josephj11** [comment]
@shervinemami Nice page. I'm happy with it.

**Comment by ineuw** [comment]
@shervinemami, thanks for the added info. It's well done.
