### ISSUE TITLE
Mouse stops working

### ISSUE THREAD

**Issue by dlewis7444** [autokey/autokey#264]
## Classification:

Crash/Hang/Data Loss

## Reproducibility:

Sometimes

## Version

AutoKey version: 0.90.4
Used GUI (Gtk, Qt, or both): GTK
Installed via: (PPA, pip3, …).  yum
Linux Distribution: RHEL Workstation 7.6

## Summary

On occasion, I'm unable to click on anything. I can alt-tab, and I can type in windows.  The mouse will move but clicking does nothing.  Also, say in a terminal window, I hold down the Alt key.  The menu (File, Edit, View...) lights up but if I then hit Alt-F, to open the File menu, nothing happens.

Sometimes I can click on tabs in Firefox and they change - but I can't actually bring Firefox into the foreground, nor click the X to close it.

This has been happening since I installed Autokey shortly after building the system.  The funny thing is, I find Autokey so bloody useful that, even if it is the culprit here and can't be fixed, I'm still going to continue using Autokey.

## Steps to Reproduce (if applicable)
Can happen any time.  Seems to happen more often when I watch a web video or other web content.  But, watching videos does not always trigger it.

Likewise, I can be doing nothing but typing in terminal windows for 2 hours and then I try to click and no response.

## Log Entries
```
Some log entries while it's acting up.  The first one occurs any time I click on a gnome-shell window while it's broke:
Feb 22 08:16:33 mybox gnome-shell[6845]: pushModal: invocation of begin_modal failed

Feb 22 08:17:38 mybox autokey-gtk.desktop[7488]: X protocol error:
Feb 22 08:17:38 mybox autokey-gtk.desktop[7488]: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = Xlib.xobject.resource.Resource(0x00e11c6b), sequence_number = 46319, major_opcode = 33, minor_opcode = 0

Feb 22 08:17:50 mybox gnome-shell[6845]: g_array_unref: assertion 'array' failed
```

## Workaround
If I go to TTY2 (ctrl-alt-f2) and then back to TTY1, it fixes it.  Until the next time.  Sometimes the fix only lasts for seconds but, if I keep trying, it will be okay for a long time - maybe minutes, maybe hours.

**Comment by josephj11** [comment]
0.90.4 is almost seven years old and unmaintained. You should really upgrade if at all possible.

Unfortunately, Debian has no one assigned to updating their AutoKey package and most Debian-based distributions get AutoKey from them so you still get 0.90.4 when you use their repositories.

You might try running our 0.95.6 deb file through alien to make it an rpm. If that doesn't work, then you need to install via pip3.

To upgrade:

If you have phrases and scripts, you need to save them:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.

If you are using Ubuntu 18.04 or a derivative, you can use our pre-built deb files.

All our current deb files are built for Ubuntu 18.04. If you are using a different distro, install using pip. See below.

AutoKey releases are available here:

https://github.com/autokey/autokey/releases/

Select the one you want and then download the common and gtk debs to a directory on your system

Change into that directory (in a terminal) then

To install it on a Debian-based system, use the following:

sudo dpkg --install autokey-common_VERSION_all.deb autokey-gtk_VERSION_all.deb

(substituting the version you downloaded for "VERSION".)

They need to be installed at the same time and dpkg will get it right while apt might not.

If you're using the QT front end, you can download and install that instead of (or in addition to) the GTK version.

Otherwise, you need to install using pip.

Follow the instructions here:
https://github.com/autokey/autokey/wiki/Installing#pip-installation
That will get you up to our current version.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by dlewis7444** [comment]
Ah, thanks - I didn't realize it was that out of date.

Tried to install newer versions using alien, pip, and rpmfind's Fedora versions.  Ran into obstacles for each.  I'm giving up for now and going back to the old version.  Autokey is well worth dealing with the mouse issues (ctrl-alt-f2, ctrl-alt-f1 a few times a day costs me less than 2 minutes - Autokey saves me way more than that).

Pip seems the best bet - I'll try again at some point.

**Comment by josephj11** [comment]
AutoKey has been ported to Fedora and they have recent versions available through dnf. I forgot about that when I originally posted.

**Comment by Elliria** [comment]
Is this still an issue, @dlewis7444? A quick poke around in Google suggests that what you're seeing is [a known GNOME issue](https://bugzilla.gnome.org/show_bug.cgi?id=751335). I'm not sure if the GNOME team fixed it, but the bug report has links at the bottom that you can follow to recreate the bug report in their new tracker if it's still an issue.

**Comment by dlewis7444** [comment]
No, this issue resolved itself a long time ago.

**Comment by Elliria** [comment]
Ah, that's good news and it can be closed. Thanks, @dlewis7444.
