### ISSUE TITLE
Unable to send notifications using notify-send

### ISSUE THREAD

**Issue by john-wicc** [autokey/autokey#267]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: .90.4

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).

Linux Distribution: Ubuntu 16.04

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

- run system.exec_command('notify-send hello')

## Expected Results

- Notification 'hello' should be displayed

## Actual Results

- get error non-zero exit status returned

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

I know that notify-send requires some environment variables to be set. I am setting them by sourcing a file with saved environment variables

**Comment by josephj11** [comment]
0.90.4 is almost seven years old and unmaintained. You should really upgrade if at all possible.

Unfortunately, Debian has no one assigned to updating their AutoKey package and most Debian-based distributions get AutoKey from them so you still get 0.90.4 when you use their repositories.

To upgrade:

If you have phrases and scripts, you need to save them:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.

If you are using Ubuntu 18.04 or a derivative, you can use our pre-built deb files.

All our current deb files are built for Ubuntu 18.04. If you are using a different distro, install using pip. See below.

AutoKey releases are available here:

https://github.com/autokey/autokey/releases/

Select the one you want and then download the common and gtk debs to a directory on your system

Change into that directory (in a terminal) then

To install it on a Debian-based system, use the following:

sudo dpkg --install autokey-common_VERSION_all.deb autokey-gtk_VERSION_all.deb

(substituting the version you downloaded for "VERSION".)

They need to be installed at the same time and dpkg will get it right while apt might not.

If you're using the QT front end, you can download and install that instead of (or in addition to) the GTK version.

Otherwise, you need to install using pip.

Follow the instructions here:
https://github.com/autokey/autokey/wiki/Installing#pip-installation
That will get you up to our current version.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by john-wicc** [comment]
Thanks! Works after updating.
