### ISSUE TITLE
Does AutoKey support input() and print()?

### ISSUE THREAD

**Issue by gusbemacbe** [autokey/autokey#268]
## Classification:

Feature and Enhancement

## Reproducibility:

Unable

## Version

* AutoKey version: 0.95.6
* Used GUI (Gtk, Qt, or both): GTK
* Installed via: AUR
* Linux Distribution: Manjaro Linux

## Summary

I use `input()` and `print()`. When you type the abbreviation, the script does not open the dialog and AutoKey leaves you with an empty. 

## Steps to Reproduce (if applicable)

1. Create a script snippet:

```python
import time

time.sleep(0.25)

iconame = input()
icon_name = clipboard.get_selection(print(iconame))

retCode, icon_name = dialog.input_dialog("Ícone original", "Escreva a ligação simbólica do ícone original")
if retCode == 0:
    keyboard.send_keys("cp -R $(find -L -samefile " + icon_name + ".svg) ~/Pictures/icons")
```

Simply:

```python
iconame = input("Write the original icon symlink:" )
print("cp -R $(find -L -samefile " + iconame + ".svg) ~/Pictures/icons")
# Output: cp -R $(find -L -samefile gnome-logs.svg) ~/Pictures/icons
```
2. Write your favourite abbreviation;
3. Type your abbreviation on VSCode, Sublime Text or on the terminal;
4. AutoKey script does not open the dialog window and leaves an empty.

## Expected Results

I believe that Autokey needs to be enhanced with a new feature to support `input` and `print`, allowing us to type script abbreviation when it opens the dialog window. 

## Actual Results

AutoKey script does not open the dialog window and leaves an empty.

**Comment by josephj11** [comment]
The developer is busy, so I'll jump in, but my Python fu is pretty low, so I may be off base.

It looks like `input()` and `print()` may be linked to standard streams (stdin and stdout). These are not normally available (to any programs) when operating in a GUI environment. That's why AutoKey provides the GtkDialog/QtDialog [API](https://autokey.github.io/index.html) calls to support rudimentary GUI-based I/O.

For more sophisticated I/O requirements, it is possible to directly use an external dialog manager such as Zenity, Kdialog, or yad via the `subprocess()` function.

I hope this addresses your issue.

For debugging the non-API parts of scripts, I sometimes run them directly in Python (with the AutoKey API calls disabled or faked). Then, things like `print()` work and are useful for displaying intermediate results, etc.

**Comment by luziferius** [comment]
Both `input` and `print` work with AutoKey (I just tested it with the Qt GUI).
But both functions are Python built-in functions, which AutoKey does not overwrite.
Both work on the standard output and standard input, so are only available for actual usage if you run AutoKey from a terminal window.
AutoKey scripts wait on `input()` for text entered in the terminal window and `print()` the results into the terminal window. If you can’t send text to the AutoKey standard input stream, calls to `input` will deadlock. I don’t know what happens if you enter text while multiple scripts simultaneously read text input. (You can run any number of scripts in parallel.)

If you want to input text using a graphical input dialogue, you can use the appropriate API object, as @josephj11 already pointed out. (It is available under the name `dialog` inside scripts.)
