### ISSUE TITLE
Cannot use Alt Gr as hotkey

### ISSUE THREAD

**Issue by Pilvinen** [autokey/autokey#272]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 
0.90.4

Used GUI (Gtk, Qt, or both): 
GUI

Linux Distribution:
Ubuntu

## Summary

Alt Gr cannot be configured as a hotkey. GUI doesn't support it and all attempts to edit the scripts failed also. xev shows the key as "ISO_Level3_Shift" but adding <ISO_Level3_Shift>, <alt_gr>, <alt_r>, <mode_shift>, etc all equally fail.

## Expected Results

Should be able to map alt gr.

## Actual Results

Cannot map alt gr. No errors. Just doesn't work plain and simple.

**Comment by luziferius** [comment]
Alt Gr is a modifier key, like Ctrl or Shift.
Configuring the key to be used as a hotkey makes it totally impossible to be used otherwise, thus breaking all symbols that need the modifier to be typed.
Based on your location (as set in GitHub), I assume you are using this keyboard layout:
https://en.wikipedia.org/wiki/QWERTY#/media/File:KB_Finnish_Multilingual.svg

If you _never_ use Alt Gr to type symbols (that are marked blue in the image above), you can use it as a hotkey. But It is unsupported by AutoKey by design. So you’ll need to remap the key to some other non-modifier key, using tools like `xmodmap`. If you remap it to something like `F13`, you can then use it as a hotkey inside AutoKey.

**Comment by Pilvinen** [comment]
What I wanted to do was map "Alt Gr" + "tilde" to "tilde" so I wouldn't have to hit "Alt Gr" + "tilde tilde" (twice) to get the tilde symbol. It is configured that way by default on Finnish/Nordic keyboards.

I know this would disable some symbols, but you are right in your assumption that I do not have any use for such accented characters.

I think it's a bad design decision to take away the option to map Alt Gr in otherwise excellent software. I think it should be left to the users' discretion.

I want this option badly. If I wanted to use xmodmap or some such - I would have used them and not Autokey. I am using Autokey because it has a GUI and it's simple to use. I have no interest in putting any more effort into mapping my keys than is strictly necessary, I just want it to work. If there were better - graphical - alternatives to Autokey with this functionality supported out of the box I would simply switch. But unfortunately it doesn't get much better than Autokey.

With this in mind I would greatly appreciate it if you were to reconsider implementing Alt Gr as an option.

**Comment by luziferius** [comment]
Well, It was not my decision, back when it was implemented. The current code does not support using a modifier as a hotkey on it’s own. And I fear that this will need a major rewrite.

> What I wanted to do was map "Alt Gr" + "tilde" to "tilde" so I wouldn't have to hit "Alt Gr" + "tilde tilde" (twice) to get the tilde symbol. It is configured that way by default on Finnish/Nordic keyboards.

Ah ok. That sounds much more reasonable. Your first post sounded like you want to map the "Alt Gr" key on it’s own to something. Because that would also disable symbols like `@` or `€`, I doubted that this is what you want.

> but you are right in your assumption that I do not have any use for such accented characters.

Then I think I found the solution for you. If you don’t need to use accented characters at all, you can use a different keyboard layout variant. I tried it on my system and gave the result you described, without fiddling with AutoKey and command line tools.

Based on your description, you have `Finnish (classic)` configured as your keyboard layout. This has the so-called dead keys enabled, which are normally used to compose accented characters. To get the accent by itself, you need to double press the button (as you know).

So go to your system's keyboard configuration GUI and change the default keyboard layout to `Finnish (classic, no dead keys)`. (This is how the layouts are called on my system, running KDE 5. They should be similar on yours.) This will disable the dead keys function, while keeping the rest as-is. Each press will then immediately type the respective symbol. So "Alt Gr"+~ will immediately type a tilde without the need to double press the key.

If that helps, you are done.

**Comment by Pilvinen** [comment]
That was a very good tip and it works perfectly. Thank you.
