### ISSUE TITLE
Using different location for folders

### ISSUE THREAD

**Issue by DutchPete** [autokey/autokey#279]
## Classification: Usability

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility: Always

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: 0.95.1

Used GUI (Gtk, Qt, or both): GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). PPA

Linux Distribution: Mint 19.1 XFCE

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

- I installed Autokey. In the .config folder Ak created an *autokey* folder with a subfolder *data*, which holds the *My Phrases* and *Sample Scripts* folders.

## Expected Results

- What I want is to have the Ak app use a different location for the scripts and phrases.
**Please advise how to do this.**

## Actual Results

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by josephj11** [comment]
Read to end before doing this!

Open the AutoKey main window. On the left there is a panel showing the folders (directories) that hold your AutoKey phrases and scripts.
Do the following:
New->Folder->Create Elsewhere
Select the directory your folder will be in and, optionally, select New Folder to create it.
Select OK.
You have your external folder.

But:
I don't remember the exact details, but if you delete the folder in AutoKey it deletes it in the file system too. And there may be other issues like that.

So:
If you have an external directory which already contains AutoKey scripts or phrases, make sure you back it up before telling AutoKey about it as it might get deleted.

In the past, I have renamed my external directory to a temporary name, created the directory in AutoKey with the desired name, and then copied everything from the backup directory into the one created within AutoKey. That avoids things getting deleted.

This has been discussed with the developer, but I don't remember if anything was improved...

I have kept all my phrases and scripts in an external directory sub-tree for years. It's quite handy because your package manager doesn't know about it so you can purge AutoKey as part of a reinstall, etc. and your phrases and scripts will still be there.

And, if you want to get creative, you can even have your external directory somewhere like in Dropbox where it is backed up and also available for use in other systems.

In the future, it's better to use our [support list](https://groups.google.com/forum/#!forum/autokey-users) for questions. There are more people there to help you and it doesn't make work for our developer.

**Comment by DutchPete** [comment]
Joe, many thanks for these instructions, I have bookmarked this page. It would be useful for others if this is added to the manual because it is a pretty basic requirement, IMO.

I'll use the other page in future.
Thanks again,
Peter
