### ISSUE TITLE
How to suppress normal key output?

### ISSUE THREAD

**Issue by Jont828** [autokey/autokey#291]
## Classification:

Bug/feature?

## Reproducibility:

Always

## Version

AutoKey version: 0.95.6

Used GUI (Gtk, Qt, or both):  GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: AUR

Linux Distribution: Arch

## Summary

I've remapped Caps Lock to Hyper on my current keyboard, and I've set Hyper + i/j/k/l to be the arrow keys. I've accomplished this in Autokey with commands such as `keyboard.send_keys("<left>")` with hotkey `<hyper>+j`. I've also set caps lock to toggle with both shift keys.

The problem is, however, if I turn on Caps Lock, then the Hyper + i/j/k/l don't exactly work anymore. They do still do the arrow key action, but they also have the side effect of typing a capital I, J, K, or L. Is there any way to suppress that output and have it behave just like if caps lock was off, i.e. not printing i/j/k/l and doing the arrow key function?

**Comment by josephj11** [comment]
I expect Thomas will reply when he gets a chance, but we have some issues with remapped keyboards that I don't quite understand.

**Comment by luziferius** [comment]
It is always the Caps lock. If it is remapped to something else, AutoKey breaks.
This is because AK does its own modifier detection and state tracking, which is not affected by the system configuration. So it’ll still track that caps lock is active after hitting the physical caps lock key, even if that is configured to do something different.

AutoKey has an internal list of modifier keys. What might help is adding a configuration option to the global AutoKey settings that removes Caps Lock from that list for everyone who remaps that key.

I think removing `Key.CAPSLOCK` from the `MODIFIERS` list here should be sufficient: https://github.com/autokey/autokey/blob/35decb72f286ce68cd2a1f09ace8891a520b58d1/lib/autokey/iomediator/constants.py#L8

**Comment by luziferius** [comment]
@Jont828 I just added the possibility to completely disable the internal Capslock handling. I think this should fix your issue with the remapped key.
If you wish, you can try this branch, containing the changes: https://github.com/autokey/autokey/tree/bugfix/issue_291.

You can clone the repository, `git checkout bugfix/issue_291`, and then run this version directly from the source. See here for brief steps: https://github.com/autokey/autokey#zero-installation-method. (Quit other AutoKey instances and backup your configuration file `~/.config/autokey/autokey.json` beforehand.)

Because AutoKey can’t detect whether a modifier is remapped to something else or not, I added a switch to the settings dialogue. So after you started AK from this branch, check the new `Disable handling of the Capslock key` option in the settings.

I’ll wait for feedback before merging this into the master branch.

Edit: To track and close duplicates: #95,

**Comment by sundarv85** [comment]
I have mapped caps lock to ctrl and this branch fixes the issue. Do you have timeline when this will be released as deb package.

**Comment by BlueDrink9** [comment]
No timeline for deb release because we have no debian maintainer. Install with pip if you want it now

**Comment by josephj11** [comment]
@BlueDrink9 That's true for distributions/repositories, but Thomas puts the new debs on our release page with every release so people can get them manually. So, this should be available in a deb when 0.96 is released (unless we have another minor release before that.)

**Comment by BlueDrink9** [comment]
Oh, sweet. My mistake

**Comment by luziferius** [comment]
@Jont828 @sundarv85 Version 0.95.10 allows to disable Capslock handling in the settings. You can get the archives from https://github.com/autokey/autokey/releases/tag/v0.95.10

**Comment by sundarv85** [comment]
@luziferius I have installed 0.95.10 deb package from the releases and it works as expected. Thank you.
