### ISSUE TITLE
daemon is killed when GUI closed

### ISSUE THREAD

**Issue by herrdeh** [autokey/autokey#294]
## Classification:

Usability

## Reproducibility:

Always

## Version

AutoKey version: autokey-gtk 0.95.6

Used GUI (Gtk, Qt, or both): 
gtk

Installed via: (PPA, pip3, …).
sporkwitch PPA

Linux Distribution:
ubu 18.04
## Summary
AK ist launched at system boot. That starts the daemon, but leaves the GUI closed. When I manually open the GUI, do some editing and close the GUI, the daemon is killed - no more expanding happens.
This is unexpected - I'd expect the daemon to continue working. If it needs a relaunch, I'd like AK to do that automatically.

Summary of the problem.
Not a problem - just a bit of convenience.

## Steps to Reproduce (if applicable)
see above.

**Comment by josephj11** [comment]
A few preliminary comments (Thomas will have to do the heavy lifting).

AutoKey is a utility designed to work in the background, so, by default, it does not start with the GUI open. If you invoke it with the -c option, it will start with the GUI open.

Clearly, the daemon should not terminate when you close the Main window.
But, if you close the Main window using Ctrl+Q or File->Quit, that will stop the daemon. Normally, you should close it by just closing the window with Ctrl+W or by selecting the X icon on the title bar.

Unless sporkwitch returns to the project, his PPA is frozen because we are locked out and he is not updating it. His PPA contains 0.95.1, so either you are using 0.95.1 or have obtained a newer version from our GitHub project. In any case, you should remove that PPA from your system as it provides no benefit.

The most recent version is 0.95.7, but upgrading (from 0.95.6), while recommended, will be unlikely to address your issue. New releases are available [here](github.com/autokey/autokey/releases/) and there are debs for Debian-based systems such as Ubuntu.

It might be helpful to us if you could provide a [trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide). Maybe it will give us some clues as to where AutoKey is failing.

As an aside, I don't particularly like editing scripts in the editor provided by AutoKey. I only use it for small changes and tests. (It has issues on my display.) If you go to where the scripts are stored (under $HOME/.config/autokey/data, by default), you can edit them with the text editor of your choice - which is probably quite a bit more powerful and easier to use.

**Comment by luziferius** [comment]
AutoKey does not need restarts and does not exit without being told to. (Well it actually does need restarts in some edge cases not hitting you: if you use the Qt5 GUI and the scripting API to create AutoKey Phrases, you currently have to restart AK to show the created phrases in the GUI…)

I’d need the log file or at least the excerpt containing the crash error. You can cut the log down to the few newest entries, if you wish.
To get the data, look at the log files in your home directory. It is located at `$HOME/.local/share/autokey/autokey.log`. It logs all messages with INFO and higher message level.

It should contain some messages indicating why AutoKey exits.

**Comment by herrdeh** [comment]
Hello, I tried to generate some more info. That's what I did:
- killall autokey-gtk
- launch autokey-gtk --verbose at the terminal
- open AK GUI 
- klick on AK GUI
- hit ctrl-q

Terminal output is here:
https://owncloud.trolink.de/index.php/s/cuxPkej16fMzmaw

**Comment by herrdeh** [comment]
@ Joe:
BTHW: Github start page still recommends sporkwitch PPA. 

Same behaviour with 0.95.7.

**Comment by josephj11** [comment]
I'll take a look at the start page. Thanks.

Solution:  Don't do that! :)

If you hit Ctrl+Q, that's supposed to stop AutoKey (as I said above).

Use Ctrl+W or click on the X icon in the title bar if you just want to close the window, but have AutoKey still running in the background.

I don't know if it's formalized in the free desktop standard, but most programs will pack up and go home when they receive a Ctrl+Q.

Open a few windows (not just tabs) in Firefox (for example) and type Ctrl-Q into one of them. They all close and Firefox is gone.

**Comment by luziferius** [comment]
I think those are the default. In the Qt GUI I let Qt handle it, resulting in the same:
https://github.com/autokey/autokey/blob/5e1baa3803bfc7a63ec2173c87ab21bb4397d88b/lib/autokey/qtui/configwindow.py#L146-L163

I looked around a bit:

https://www.freedesktop.org/wiki/Specifications/default-keys-spec/
https://wiki.gnome.org/Design/OS/KeyboardShortcuts

**Comment by herrdeh** [comment]
Ok. I think I can adopt to this - and could have found out myself.
Sorry for all the effort.
