### ISSUE TITLE
Can't record keyboard/mouse

### ISSUE THREAD

**Issue by janbo208** [autokey/autokey#297]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.7-1

Used GUI (Gtk, Qt, or both): both

Installed via: AUR

Linux Distribution: Manjaro

## Summary

Can't record keyboard/mouse/script

## Steps to Reproduce (if applicable)
- create and select new script
- select record keyboard keyboard/mouse (or record script in Qt)

## Expected Results

- show record dialog

## Actual Results

- nothing happens

autokey-qt --verbose doesn't return any output

output for autokey-gtk --verbose:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/gtkui/configwindow.py", line 1239, in on_record_keystrokes
    self.__getCurrentPage().record_keystrokes(widget.get_active())
  File "/usr/lib/python3.7/site-packages/autokey/gtkui/configwindow.py", line 524, in record_keystrokes
    dlg = dialogs.RecordDialog(self.ui, self.on_rec_response)
  File "/usr/lib/python3.7/site-packages/autokey/gtkui/dialogs.py", line 620, in __init__
    self.ui.set_transient_for(parent)
TypeError: argument parent: Expected Gtk.Window, but got gi.repository.Gtk.Alignment

```

**Comment by dginovker** [comment]
I found the line causing the bug. Replacing this with `if True:` allows recording actions to work, but it blows up shortly after: https://github.com/autokey/autokey/blob/master/lib/autokey/qtui/configwindow.py#L231

Edit: Here's error:
```
Traceback (most recent call last):
  File "autokey/lib/autokey/qtui/autokey_treewidget.py", line 46, in mousePressEvent
    veto = self.window().central_widget.promptToSave()
  File "autokey/lib/autokey/qtui/centralwidget.py", line 126, in promptToSave
    return self.on_save()
  File "autokey/lib/autokey/qtui/centralwidget.py", line 402, in on_save
    item = self.treeWidget.selectedItems()[0]
IndexError: list index out of range
Fatal Python error: Aborted
```

**Comment by mmhere** [comment]
Just an additional data point.  Same traceback on Ubuntu 16.04 running MATE (Python 3.5.2).

**Comment by duangsuse** [comment]
Add some related code, usage both in Qt/GTK module:

https://github.com/autokey/autokey/blob/8735c107068e3069e55a19a4a287491539e3f580/lib/autokey/qtui/configwindow.py#L269

https://github.com/autokey/autokey/blob/f138b9a4147d4109a107c7cadea5715f4749b5ef/lib/autokey/gtkui/configwindow.py#L524

**Comment by TylerRick** [comment]
I ran into this as well on Ubuntu 18.04.4 LTS (Budgie variant).

I'm seeing the exact some error/backtrace as @haonug when I run it with `autokey-gtk --verbose`.

Does anyone know how to fix this?

**Comment by sebastiansam55** [comment]
Hey so I did a thing and it seems like it fixed the macro recording function? 

https://github.com/sebastiansam55/autokey/commit/2098030939fbc1b36f53fc4035d3b9f0b8ab1617

At least on my computer it lets me use it, the keyboard and mouse functions work fine for me now!

**Comment by josephj11** [comment]
Great! We look forward to getting the development process going again with contributions from our two new developers.
Still waiting for a response from Thomas.

**Comment by dmg-gmd** [comment]
**Comment:** 
Just wanted to report I have this issue as well. I am unable to record keystrokes or mouse.

**Distro:** 
Arch Linux

**Version:**
autokey-gtk version 0.95.10

**Install Method:**
AUR

**Debug Traceback:**
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/configwindow.py", line 1239, in on_record_keystrokes
    self.__getCurrentPage().record_keystrokes(widget.get_active())
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/configwindow.py", line 524, in record_keystrokes
    dlg = dialogs.RecordDialog(self.ui, self.on_rec_response)
  File "/usr/lib/python3.9/site-packages/autokey/gtkui/dialogs.py", line 624, in __init__
    self.ui.set_transient_for(parent)
TypeError: argument parent: Expected Gtk.Window, but got gi.repository.Gtk.Alignment
```

**Refers to:**
[configwindow.py](https://github.com/autokey/autokey/blob/master/lib/autokey/gtkui/configwindow.py)

**Comment by Niekto350** [comment]
I have the same issue using latest stable and beta releases. I'll test it once again when there will be a release containing this commit https://github.com/autokey/autokey/commit/9c4f167edb0fc9e6a865f5d6a2d6119b5930b7d1.

**Comment by BlueDrink9** [comment]
Latest beta doesn't have this fix, but if you can install the git version from the beta branch, it should.

**Comment by BlueDrink9** [comment]
If it's important to you, I will release the fix as a new beta version

**Comment by Niekto350** [comment]
Thank you, for my needs it won't be necessary, however maybe someone else would need it. I've manually eddited the file on my local installation to make the same change as you've made in the commit (it get's overwritten with the same change on the update).

After the change I can start the recording and it generates some code. If I specify that I want to record mouse, the whole app crashes (I think there were a stack trace in the terminal, I can provide it if you're interested).

If I record keyboard, and play it back it does not work as intended. Looks like the special keys and key combinations does not work as intended, for example it records `<super>+w` but if I play the macro it just outputs `w` or if I record `<alt>+<tab>` it does not switch windows, just outputs tab character `	`. Also the recorded macro would likely need some manual tweaking, especially to introduce sleep times between actions. Would it be possible to record the time between the actions or just put some predefined timer between each action?

**Comment by josephj11** [comment]
@BlueDrink9  If the above behavior can be replicated, it appears that this feature still requires work. Maybe this shouldn't be closed yet. Or, maybe, playback is a separate problem.

Automatically adding a `time.sleep(0.1)` between each (or some?) generated API calls sounds like a good idea. It would probably do more good than harm. I wouldn't get into trying to measure time between actions during recording or we might add someone's coffee break into a script.

We get a lot of issues with scripting which are solved by adding delays, so making new users aware of the option and of how to do that is also a benefit.

**Comment by Niekto350** [comment]
I think it's still helpful, even if the generated script requires manual tweaking. It can create a rough skeleton of the script as a starting point. Therefore I think it should be published (if it cannot be fixed completely in a short time frame) but there also should be some text notification in the recording window that explains the situation to new users.

I don't think that recording a coffee break would be a problem. Users generally don't record long random work chunks to make a script but rather work on the script to have a small repeatable action. This means that the wait times are expected and accounted for because the whole action is planned. Anyway I think the best solution would be a configurable option (some select field) to specify how to record the macro. The choices could be something like: no delays, predefined static delay of X ms, real wait times according to the recording. The script would most likely need some manual tweaking in any of these choices which is ok, the goal is to have a best fit skeleton as a starting point.

Few more ideas:
- some visual indication of recording would be nice, maybe changing the system tray icon to a red color?
- easier way to finish the recording, maybe put it into top level context menu on the system tray icon? a button in the main window toolbar if it's opened? maybe small floating window with a button and some recording metadata?
- if the app crashes while recording, the whole script is lost, maybe saving it in some predefined interval would be useful
- maybe the recording could add some markers to the generated code to make the orientation in the code for further edits a bit easier (for example comment when an active window changes to a window class/title) because it would be a bit hard to get oriented in the generated code if all you see is keystrockes and click coordinates (everything looks the same)

PS:
The recording functionality is the 2nd most important feature of the app (1st is the actual execution of the automation) because it allows fast adoption of the software. Very few people will spend the time to manually learn the syntax and write the scripts by hand.

PS2:
I wanted to comment on something else related to this issue but forgot what it was. I'll be back if I'll remember. :)

**Comment by BlueDrink9** [comment]
This is a good idea, but is a separate feature issue. Please open a new issue with your suggestions just to keep things tidy. Might not get looked at for a long time, but I think it sounds worth implementing!

**Comment by Niekto350** [comment]
Sure, I've created a new task from this. Later we could break it up into even more subtasks if we need to.

https://github.com/autokey/autokey/issues/654
