### ISSUE TITLE
Can not start autokey

### ISSUE THREAD

**Issue by steelbrain** [autokey/autokey#30]
I've installed autokey along with the dependencies and this is what I get when I execute `autokey-gtk` in a terminal

```
Fatal error starting AutoKey.
'recordHotkey'
```

**Comment by defenestration** [comment]
I moved my old autokey config folder out of the way to resolve this.

`mv ~/.config/autokey{,.bak}`

**Comment by steelbrain** [comment]
After removing that folder, I get this error now, I am on Ubuntu 15.04 GNOME
```
Error starting interface. Keyboard monitoring will be disabled.
Check your system/configuration.
Can't connect to display ":1": No protocol specified
```

**Comment by josephj11** [comment]
I know this is really old, but I missed it until now.

First, since AutoKey is essentially an Xwindows application, are you running AutoKey under a gui which sits on top of Xwindows? I ask this because, by default, the gui virtual console uses display ":0", not ":1". If you're trying to run under another virtual console which isn't setup as a gui, then AutoKey has nowhere to hang its hat.

See also:  https://github.com/autokey/autokey/wiki/Problem-Reporting-Guide

because the more we understand about the problem, the quicker we can solve it.
