### ISSUE TITLE
Phrases not rendering correctly

### ISSUE THREAD

**Issue by CaptainDredge** [autokey/autokey#300]
## Classification:
BUG

## Reproducibility:

Sometimes

## Version

AutoKey version: v0.95.7

Used GUI (Gtk, Qt, or both): GTK

Installed via: Provided autokey release for Debian

Linux Distribution: Ubuntu

## Summary

In some applications like Browser Autokey doesn't render the phrases exactly. For eg. in sublime text it was fine but in mozilla window it was not

## Steps to Reproduce (if applicable)

- Go to the Test window of InterviewBit [here](https://www.interviewbit.com/test/a/interviewbit-demo-test/?ref=dashboard)
- Try using Autokey phrase in the editor

## Expected Results Vs Actual Results

-You can take a look at the difference [here](http://www.mergely.com/7BMxAgds/) Left one is in the browser window where the phrase was not rendered perfectly. Right one is in sublime text which is perfect

**Comment by josephj11** [comment]
Thomas will have to look at this, but:

First of all, I assume the sample output was produced using a number of phrase invocations - not by one huge phrase!

One thing that _might_ affect this is the method used for getting the text to your window.
Sometimes AutoKey types way too fast for some applications to keep up. Pasting with the clipboard may fix this.

Try opening some of your phrases in the AutoKey main window and selecting another value for the Paste Using option - especially if you are using the default which is Paste Using Keyboard. See if that makes a difference.

Another thing to watch out for:

There is/was an issue with phrases that include constructs with `<...>` in them because AutoKey uses that syntax for embedding macros in phrases. I know it was at least partly fixed.
See issues #110 and #163 and probably one or two more.

If that's what's causing the problems, you might work around it (inelegantly!) by replacing all occurrences of `<` and `>` in your phrases with tokens that do not occur in your work. Then, after using all your phrases, do a search and replace all in an editor to replace all the tokens with `<` and `>` again. (I warned you it was inelegant. ;)  )

**Comment by CaptainDredge** [comment]
@josephj11 It was actually produced using only a single phrase invocation because it is a template I want every time I code. Actually I had to use "Keyboard" option as Pasting is sometimes not an option in some platforms. As far as the inelegant solution is concerned can I replace '<' with &gt and '<' with &lt. Will the autokey recognize these symbols automatically?
Another thing to notice her is that the same key '<' and '>' are rendered correctly at some places and incorrectly at others? I couldn't guess why its like this coz if Autokey wouldn't recognize these symbols then it would have rendered it incorrectly everywhere I guess?

**Comment by josephj11** [comment]
This may be the same problem as #151 (it's a really long thread and probably won't help you.) If it is, we don't know what causes it or how to fix it, but we suspect it's something outside of AutoKey.

I suggested using paste because losing bits and pieces of a phrase looks more like a timing issue than a parsing/expansion issue. AutoKey "types" as fast as the interface will allow - which is way faster than human typing, so software designed for more modest input speeds may drop characters. If this was ever going to be a problem, a really large phrase like yours would be where it would occur.

I just wanted to mention about the macros in case that crops up later.

No, AutoKey won't recognize your tokens such as &lt, but you can always write a script that will.

Getting the text in and out of the script would be the issue. The obvious way to do that would be select, copy, modify, paste - which would run into whatever issue you already have with pasting. It takes your original problem and adds another level of difficulty for nothing.

Your text editor is designed to do such things. It just breaks your work flow if you have to leave where you are, run the text editor, and then come back. You can also use sed for something like this so you don't have to interact with an editor. If you're clever enough to get the sequence of tasks right, you can even run sed from within an AutoKey script. But, if you have to be clever to write it, you'll have to be clever to maintain it and it will probably be fragile.

Another thing you can try (also suitably inelegant) is to write a script with the text of your phrase in a string. You can then send it to the window one character at a time and experiment with the inter-character delay. I wrote a [function](https://github.com/autokey/autokey/wiki/Scripting#function-to-type-text-slowly) for this. One of the posters in #151 tried this and it still didn't fix it.

**Comment by CaptainDredge** [comment]
Hmm, it seems like a serious issue. Btw @josephj11  how do I pass the phrase as a string to your written [script](https://github.com/autokey/autokey/wiki/Scripting#function-to-type-text-slowly) ?

**Comment by josephj11** [comment]
First (just in case it's not clear), you copy my function into your new script so it's available to be invoked. (You are now working with an AutoKey script, not a phrase.)

Depends on where the string is to start with.
The simplest approach would be to assign the string to a variable as a hard coded constant:
var = "this is my code ..."
type_slow(var)
From there, you can elaborate by getting a value to put into var from somewhere else.
You could open a file and read it into var or you could build a selection menu of various content either hard coded or read from a file, etc. It becomes a normal Python3 programming issue with the possible use of our API to get user input or a call out to something like yad or Zenity for fancier input.

**Comment by CaptainDredge** [comment]
`

    import time

    var = "Hello"

    def type_slow(string=var, delay=0.1):

        if delay <= 0:

        # No delay, directly relay the whole string to the API function.

            keyboard.send_keys(string)

        else:

            for c in string:

                keyboard.send_keys(c)

                time.sleep(delay)`

This doesn't work. Even if I hardcode string inside function nothing gets typed after executing the script :(

**Comment by josephj11** [comment]
You defined the string in var. Then you defined the function. You still have to invoke it with:
type_slow(var)

**Comment by CaptainDredge** [comment]
Yep, It worked. Thank you very much @josephj11 :)
