### ISSUE TITLE
Starting a Jupyter notebook with autokey

### ISSUE THREAD

**Issue by kolibril13** [autokey/autokey#307]
I want to write a script that starts a jupyter notebook for me.
My idea is: 
1. Start terminal
2. Execute program.
In Autokey, this is one line of code to start a program from the terminal, e.g.
```python
system.exec_command(""" gnome-terminal -e "gedit" """)
```
Unfortunately, the script:
```python
system.exec_command(""" gnome-terminal -e "jupyter-notebook" """)
```
Gives the error when I run the shortcut.
![no1](https://user-images.githubusercontent.com/44469195/64212181-cb2c0c80-cea8-11e9-8049-5b3274ec0ea9.png)

However, when I open a normal new terminal and run
```bash
gnome-terminal -e "jupyter-notebook"
```
The notebook is stating.
Any ideas why this might be, or do you have any idea how to start a notebook automatically?

**Comment by josephj11** [comment]
This is a normal programming problem, not an AutoKey issue, so it would be more appropriate on our support [list](https://groups.google.com/forum/#!forum/autokey-users).

I know what the problem is, but I'm not entirely sure how to fix it.

When you run a script in a terminal, the loader looks for the programs in the script using the PATH variable.

When you run a script in Python3, it doesn't do that.

To get it to work now, just specify the absolute path to your executable.

Beyond that, there's a way to tell Python where to look for things just like PATH does for bash, but I'm not familiar with it.

Search for PYTHONPATH. I think that will get you to your answer.

**Comment by kolibril13** [comment]
Perfect!
I changed it to
```python
system.exec_command("""  gnome-terminal -e '/home/kolibril/anaconda3/bin/jupyter-notebook' """)
```
and now it's doing what it should do.
Thanks a lot!
