### ISSUE TITLE
Enhancement: window.get_active_path()

### ISSUE THREAD

**Issue by kolibril13** [autokey/autokey#308]
It would be great to automatically get the path of the current folder.
`window.get_active_title()`
and 
`window.get_active_class()`
are already great, but I often need the path of the window, so I would love to use the option
`window.get_active_path()`
Is that already possible?
Or is that difficult to implement?

**Comment by josephj11** [comment]
I'm a Python newbie, so I'm not really sure how this works, but I don't think windows have paths. They do have X11 IDs you can use to reference them. `xdotool` can be used to search for windows by various criteria and it will return the IDs of windows that match the search. (Note that there can often be more than one if you use a simple search criterion like window title.)

Other paths are the PATH that the current process uses to find executables and the PYTHONPATH that Python uses to find Python modules referenced in your scripts.

Maybe if you are more specific about what you actually want to accomplish, we can arrive at a more specific solution.

**Comment by kolibril13** [comment]
I have a working directory somewhere in my system. This path to this directory is saved on my desktop in the file
'/home/kolibril/Desktop/working_directory.txt'. 
So, anytime I want to work on a specific folder, I can just type a shortcut that triggers the script:
```python
import os
with open('/home/kolibril/Desktop/working_directory.txt') as f: 
        data = f.readlines() 
working_directory= data[0]
working_directory = working_directory[:-2]
comnand = "nautilus " + working_directory 
os.system(comnand)
```
and opens the folder for me.

When I want to work in another folder, it would be great to have the opposite script, that sets a new folder path in the text document in '/home/kolibril/Desktop/working_directory.txt'. 
At the moment I have to write it there by myself.
Thanks for your help! :)

**Comment by josephj11** [comment]
I don't see how this could work. Whatever is in '/home/kolibril/Desktop/working_directory.txt' is not maintained by Linux, so you are maintaining it yourself, so there's no way AutoKey could know about it.
You can store whatever you want in a parameter file and read it as you are already doing.

The problem is that Linux has no global concept of current directory. I'm not sure of the exact details of how it works, but it's closer to a current directory for each process.

I have a set of bash scripts (unrelated to AutoKey) that call each other. Originally, they worked fine because when run from a terminal, the current directory and PATH (set by the shell process) let them find each other easily. But when I started one of the scripts from the desktop from an icon, it couldn't find any of the others because the value of PATH was not even the the one I set in .bashrc. I had to write some special code for each script to get around this.

Probably not relevant here, but AutoKey offers stored variables that maintain values from one invocation of a particular script to the next and global stored variables which are accessible to multiple scripts. These can be useful for establishing an environment for scripts within AutoKey.

**Comment by kolibril13** [comment]
Ok, thank you!
