### ISSUE TITLE
How to bind a hot key to send its self in script 

### ISSUE THREAD

**Issue by QiangF** [autokey/autokey#31]
Hello everyone,
I want emacs keybinding for some programs. The window filter works, but I am trying a simpler way: if the program window class is in the black list, send the hot key unmodified. How can I do that?
Thank you!

my script: 

    import scripting as scrt
    black_list = ['emacs', 'Iceweasel']
    def emacs_key(key_sym):
        """key_sym : string : symboly for the key
        eg. '<up>' """
        win_class = scrt.window.get_active_class()
        if not any(win_class.find(s) for s in black_list):
            scrt.keyboard.send_keys(key_sym)
        else: # send the hot key

**Comment by josephj11** [comment]
Hi.

Since this isn't a bug (at least yet), it would probably be better (and be seen by more people) if it was posted on our Google Groups forum (https://groups.google.com/forum/#!forum/autokey-users) or directly to our listserv. Subscribe with (autokey-users+subscribe@googlegroups.com).

Your notes don't quite make sense to me. If you are using things like window filters, then you are inside of AutoKey, but if you are using the scripting module, you're outside of AutoKey. Inside AutoKey, you just say keyboard.send_keys( ... ) without importing and using the scripting module.

If you are inside AutoKey, you can only bind a macro to one (possibly multi-key) hotkey so I'm not sure where key_sym is getting a value.

All of these technicalities aside, I have no idea what AutoKey will do if a macro emits the hotkey that triggered it (or the hotkey for any other macro, for that matter). I would hope that it doesn't cause infinite recursion, but I haven't tried it. That would be the first thing to test - all by itself.

Other than that, I know X11 has a number of primitives in its API for dealing with the keyboard, but I have no idea what that would do with AutoKey running either.

Maybe what you really want is to swap keyboard layouts on the fly. I haven't experimented with this, but a good place to start looking would be man xmodmap.

Joe

**Comment by QiangF** [comment]
Thank you Joe.
I finally managed to find a solution.
https://github.com/metakermit/dotfiles/tree/master/autokey
But the window filter doesn't work as window fileter in the autokey gui, maybe it is because the hot-key calling loop.

**Comment by josephj11** [comment]
Closing. Referred to development for consideration.
