### ISSUE TITLE
Phrase Distortions in LibreOffice

### ISSUE THREAD

**Issue by vitaaliy** [autokey/autokey#320]
## Summary of the problem.
My abbreviations look like: =t ---> Testing AutoKey (Trigger on all non-word, remove typed, omit trigger character, ignore case).
In text editors (Pluma, gEdit 3.34.0) - works OK, but in LibreOffices inserted phrase distorts:
=t ---> =TestigAutonKye
## Steps to Reproduce (if applicable)
1. I created abbreviations in the top-level folder: **Abbr-Loz** and saved them. For example: **=t** ---> **Testing AutoKey** (Trigger on all non-word, remove typed, omit trigger character, ignore case).
2. Took the text editor (_Pluma, gEdit 3.34.0_) and insert: =t Enter. The result is as expected: **Testing AutoKey**
3. Using AutoKey in LibreOffice _gives distorted expansion_: **_=TestigAutonKye_**
## Actual Results: **_=TestigAutonKye_**

**Comment by luziferius** [comment]
LibreOffice is one of the applications that don’t play nicely with AutoKey.
I think this is related to the autocorrect feature in LO. LO does quite some processing on each key press. I _think_ the speed AutoKey types causes the input processing in LO to choke. The same thing happens in other CPU intensive text fields, like the URL bar in Firefox. I haven’t found a way to make this totally reliable, unfortunately.

But you can use the Clipboard pasting mode to expand your Phrases in LO. This should work well.

**Comment by vitaaliy** [comment]
In Windows I use Russian Punto Switcher and never had bugs like that...

**Comment by josephj11** [comment]
0.90.4 is almost eight years old and unmaintained. You should really upgrade if at all possible.

Unfortunately, Debian has no one assigned to updating their AutoKey package and most Debian-based distributions get AutoKey from them so you still get 0.90.4 when you use their repositories.

To upgrade:

If you have phrases and scripts, you need to save them:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.

If you are using Ubuntu 18.04 or a derivative, you can definitely use our pre-built deb files. However, since most of AutoKey is specific Debian release independent, our deb files should work in other Debian-based distros and releases.

All our current deb files are built for Ubuntu 18.04. If you are using a distro which doesn't support deb (apt) packages or installing from the deb packages fails, install using pip. See below.

AutoKey releases are available here:

https://github.com/autokey/autokey/releases/

Select the one you want and then download the common and gtk debs to a directory on your system

Change into that directory (in a terminal) then

To install it on a Debian-based system, use the following:

sudo dpkg --install autokey-common_VERSION_all.deb autokey-gtk_VERSION_all.deb

(substituting the version you downloaded for "VERSION".)

They need to be installed at the same time and dpkg will get it right while apt might not.

If you're using the QT front end, you can download and install that instead of (or in addition to) the GTK version.

Otherwise, you need to install using pip.

Follow the instructions here:
https://github.com/autokey/autokey/wiki/Installing#pip-installation
That will get you up to our current version.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by vitaaliy** [comment]
Thank you, josephj11, for detailed instructions. I am new to Linux and probably missed something important. I have Ubuntu 19.10, GNOME desktop.
sudo dpkg --install autokey-common_0.95.8-0_all.deb autokey-gtk_0.95.8-0_all.deb
/home/loz/Downloads/autokey-common_0.95.8-0_all.deb

loz@OBERON-U:~$ cd /home/loz/Downloads
loz@OBERON-U:~/Downloads$ sudo dpkg --install autokey-common_0.95.8-0_all.deb autokey-gtk_0.95.8-0_all.deb
[sudo] password for loz: 
Selecting previously unselected package autokey-common.
(Reading database ... 193406 files and directories currently installed.)
Preparing to unpack autokey-common_0.95.8-0_all.deb ...
Unpacking autokey-common (0.95.8-0) ...
Selecting previously unselected package autokey-gtk.
Preparing to unpack autokey-gtk_0.95.8-0_all.deb ...
Unpacking autokey-gtk (0.95.8-0) ...
dpkg: dependency problems prevent configuration of autokey-common:
 autokey-common depends on python3-pyinotify; however:
  Package python3-pyinotify is not installed.
 autokey-common depends on python3-xlib; however:
  Package python3-xlib is not installed.
 autokey-common depends on wmctrl; however:
  Package wmctrl is not installed.

dpkg: error processing package autokey-common (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of autokey-gtk:
 autokey-gtk depends on gir1.2-appindicator3-0.1; however:
  Package gir1.2-appindicator3-0.1 is not installed.
 autokey-gtk depends on autokey-common (= 0.95.8-0); however:
  Package autokey-common is not configured yet.

dpkg: error processing package autokey-gtk (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.7-3) ...
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu1) ...
Processing triggers for mime-support (3.63ubuntu1) ...
Errors were encountered while processing:
 autokey-common
 autokey-gtk
-------------------------------------------------
Running AutoKey gave an error... Looks like I have no Python 3 installed...

**Comment by vitaaliy** [comment]
Thank you, Joe, for your detailed reply. I installed Python 3.7 and AutoKey 0.95.8. It gives even more drastic distortions than the previous one in the LibreOffice. I have Ubuntu 19.10 GNOME desktop... In Plume text editor it handles abbreviations quite OK (as also my initial AK version).
Any further ideas and/or suggestions will be appreciated.

**Comment by josephj11** [comment]
As Thomas says, the first thing to try  is to use paste using clipboard. That may help. I spent time creating the above post awhile ago. Now, it's just a boilerplate . Unfortunately, I need to use it pretty often because people keep installing 0.90.4 because that's what Debian provides to everyone.

**Comment by vitaaliy** [comment]
What do you mean by using a clipboard? Any text from any source, including text editors, is pasted into LO correctly. Of course, with this method I can AK my abbreviation into any editor and then copy-paste it into LO... Sort of masochism... ;) - or I did not get your idea?

**Comment by josephj11** [comment]
It's an AutoKey option.
![Paste_Using_Clipboard](https://user-images.githubusercontent.com/4546046/68739375-a5149e00-05b6-11ea-9dc1-546228a007b5.png)

**Comment by vitaaliy** [comment]
Hi, Joe,
I never expected to find here mystical Plato's _Thing-in-itself_ represented by this AutoKey. Here are the results of my scientific investigation.
1. Yesss! When I used the pasting option "_Clipboard (Ctrl+V)_" LO and FireFox showed better results.
Abbreviation: **=t**
Phrase: **See results about**
Trigger: **Space and Enter or All non-word**
Using in text editor: **See results about** - as expected
In LO: **=See results about** (on Enter)
**See results about** (on Space) - excellent  but mysterious result...

Besides I never had the chance to use "**Ctrl+V**" explicitly - it behaved exactly as before excluding presented nuances...

2. When I tried to use "." as the first symbol in abbreviation (**.t** - for example) - the whole abbreviation item disappears after AutoKey's restart.

I am materialist but gradually becoming mystic during this acquaintance with AutoKey.

**Comment by josephj11** [comment]
That's funny and might sort of be a bug, I just defined a phrase called "junk" with a trigger of ".jnk" and a phrase of "JUNK". It works fine - even after quitting and restarting AutoKey.

What did you name your phrase?

I'm asking because AutoKey names the file the phrase is stored in with the name of the phrase. This works fine with most names, but if you use funny characters in your name then they can affect other things. In particular, file names that start with a period are considered hidden files by default on Linux, so if you named a phrase or script  starting with a period, it might work (I haven't tested it), but it would probably be invisible/missing in the AutoKey menu.

**Comment by vitaaliy** [comment]
OK, Joe... Now I will try to present the most transparent and detailed description of my playing with AK.

1. I declared the top-level folder: Abbr-Loz. It was placed into the file structure like: /home/loz/Abbr-Loz/ - which is already strange, because this name may conflict with another "Abbr-Loz" folder - if I decide to declare it ignoring AK actions.
Another my folder was created under "My Phrases":
/home/loz/.config/autokey/data/My Phrases/loz-AutoKey/ - and it is evident that it cannot interfere with another "loz-AutoKey" anywhere else.

2. In order to work within LO and FF I use now abbreviations starting with: "=" - for example: =vg, =t, =mloz, etc.
Trigger: all non-word
Remove typed abbreviation
Omit trigger character
Ignore case of typed abbreviations
Paste using Clipboard (Ctrl+V)
As trigger character should be used "space". "Enter" distorts the output in LO and FF and should not be used. In the text editor Pluma and gEdit - both options: "space" and "Enter" work OK.

3. I declared the following abbreviations:
,t --> Testing AK - abbreviation:       ,t
't --> Testing AK - abbreviation:       't
`t --> Testing AK - abbreviation:       `t (top left quote "`" missing here)
**.t --> Testing AK - abbreviation:       .t**
 - and they worked OK in editors, LO, FF.
Then I quit AK and started it again. Abbreviation: ".t" disappeared. All others remain in place and work correctly.

**Comment by josephj11** [comment]
Thomas is going to have to look at this.

One of our users, Andy, is using a semicolon to start his trigger phrases as a semicolon followed by non-white space is unlikely to occur in normal text. Most of the ones you are using could occur normally and inadvertently trigger an event.

Also, AutoKey has a rather simple definition of "non-word" characters and I think a trigger phrase has to be a word (although I'm not sure exactly how that works), so using most punctuation in trigger phrases isn't the best idea to start with.
So, even if this is a bug, it's one that can easily be avoided.

Do you have a use case that requires using these particular characters in trigger phrases?

**Comment by vitaaliy** [comment]
I recall with nostalgy those good old days when I sat in Windows and used _Punto Switcher_ for my abbreviations. There are no restrictions - at all - on abbreviation... And of course - it is freely used in any text program: editors, LibreOffice, MS Office, browsers... what else... It intercepts keyboard signals and substitutes defined abbreviations with the corresponding phrases. That's all! No cybernetics, no mysticism, no file name restrictions... Only the user and his/her will. Pure communist propaganda.
But what with AK... Now I define quite innocent abbreviation:   **zt** and make a simple experiment playing with it in Pluma editor and LibreOffice documents. The results are astonishing using different "**Paste using**" options.
So we have the definition: **_zt --> Testing: zt_** triggering on "_Space (1) and Enter (2)_". _Remove abbreviation, Omit trigger character._
I just tested my abbreviation with Space and Enter keys - no mystic Ctrl+v and others

**Pluma**
**Keyboard**: Testing: zt Testing: zt
**Ctrl+V**: Testing: zt Testing: zt
**Ctrl+Shift+V**: abbreviation just disappears
**Shift+Insert**: Testing: zt Testing: zt

After that I switched to LO where AK stopped to understand zt . So I defined another - analogues - abbreviation:
**_wt --> Testing: wt_**

**LibreOffice**
**Keyboard**: wtTestin: w	wt
Testin: w
**Ctrl+V**: Testing: wt		wTesting: wt
**Ctrl+Shift+V**: w - “Unformatted text”
**Shift+Insert**: Testing: wt	wTesting: wt

Here you are...
P.S. Concerning disappearing **zt** abbreviation. Incidentally I noticed that appeared its Prase settings: Always prompt... and Show in... which I never intentionally set myself. Strange. Very strange. When I dropped them, **zt** abbreviation cured.

**Comment by vitaaliy** [comment]
I recall with nostalgy those good old days when I sit in Windows and used _Punto Switcher_ for my abbreviations. There are no restrictions - at all - on abbreviation... And of course - it is freely used in any text program: editors, LibreOffice, MS Office, browsers... what else... It intercepts keyboard signals and substitutes defined abbreviations with the corresponding phrases. That's all! No cybernetics, no mysticism, no file name restrictions... Only the user and his/her will. Pure communist propaganda.
But what with AK... Now I define quite innocent abbreviation:   **zt** and make a simple experiment playing with it in Pluma editor and LibreOffice documents. The results are astonishing using different "Paste using" options.
So we have the definition: zt --> Testing: zt triggering on "Space (1) and Enter (2)". Remove abbreviation, Omit trigger character.
I just tested my abbreviation with Space and Enter keys - no mystic Ctrl+v and others

Pluma
Keyboard: Testing: zt Testing: zt
Ctrl+V: Testing: zt Testing: zt
Ctrl+Shift+V: abbreviation just disappears
Shift+Insert: Testing: zt Testing: zt

After that I switched to LO where AK stopped to understand zt . So I defined another - analogues - abbreviation:
wt --> Testing: wt

LibreOffice
Keyboard: wtTestin: w	wt
Testin: w
Ctrl+V: Testing: wt		wTesting: wt
Ctrl+Shift+V: w - “Unformatted text”
Shift+Insert: Testing: wt	wTesting: wt

Here you are...

P.S. Concerning disappearing **zt** abbreviation. Incidentally I noticed that appeared its **Prase settings**: _Always prompt_... and  _Show in_... which I never intentionally set myself. Strange. Very strange. When I dropped them, zt abbreviation cured.

**Comment by josephj11** [comment]
I can see where the Always Prompt option might get in the way with sophisticated programs such as LO and the FF address field. The Show In Toolbar Icon option shouldn't cause any problems. I use that a lot for things like AutoKey URLs that I don't need a hotkey or trigger phrase for.

As for Paste Using Ctrl+Shift+V, that's a special case for use in things like terminals that use Ctrl+V for something else. The application has to paste using the keypress sequence which AutoKey emits and AFAIK, only terminals use Ctrl+Shift+V, so that behavior is correct - just not what you want.

I'm not sure where we are now that you have explored so many options. Do we have remaining issues to solve?

Also, when worst comes to worst (with programs such as LO), sometimes you just have to feed them the characters at something more like the speed humans type. To do this, you have to use scripts instead of phrases. I have written a function, [type_slow()](https://github.com/autokey/autokey/wiki/Scripting#function-to-type-text-slowly), which emits one character at a time and then waits a little bit before emitting the next character.

**Comment by vitaaliy** [comment]
OK, Joe... I think that transparency and simplicity of _Punto Switcher_ in using abbreviations are unachievable with _AutoKey_ but I've got some experience concerning its nuances and hope to deal with them in practice. Thank you for your help. No remaining issues to solve :)

**Comment by spicedreams** [comment]
> I have written a function, [type_slow()](https://github.com/autokey/autokey/wiki/Scripting#function-to-type-text-slowly),

Joseph, is there a way to have this function somewhere 'global' so it can just be called by name from any Auotokey script, rather than having to repeat it in every script where it is needed?
Thanks
Graham

**Comment by BlueDrink9** [comment]
Devs are working on being able to import user-written scripts like this. Search issue tracker for "import"

**Comment by DoctorSubtilis** [comment]
Using the last version of autokey and paste from clipboard, as [above](https://github.com/autokey/autokey/issues/320#issuecomment-553263019) suggested, worked (so far) for me (KDE Neon 5.18).  
Thank you very, very much, Joseph.
