### ISSUE TITLE
0.95.8 version number clarification please

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#321]
On installing this latest GTK version 0.95.8, the Help\About shows version 0.95.7. 

![Screenshot from 2019-11-08 23-11-18](https://user-images.githubusercontent.com/10367016/68523085-e0932d80-0281-11ea-8e76-fafe000e667a.png)

**Comment by luziferius** [comment]
I noticed this one hour after publishing…
I forgot to update this line: https://github.com/autokey/autokey/blob/8735c107068e3069e55a19a4a287491539e3f580/lib/autokey/common.py#L43
(And it is mentioned in the release notes here: https://github.com/autokey/autokey/releases/tag/v0.95.8)
Editing published releases is a no-go, as it is a hell for distribution package maintainers. And releasing a new version (0.95.9) just for the sake of updating the version number is a bit pointless in my opinion.

This should not cause major harm, other than this shown wrong. If it indeed causes real harm, as in disrupting update procedures, I’ll release a new version.

Anyways, thank you for reporting, so that it is not forgotten.

(BTW: This is what I get for not following the instructions I literally wrote myself to not forget this…)

**Comment by ineuw** [comment]
Thanks for the reply and this is not a problem. Just wanted to let you know because I uninstalled the previous version (0.95.4) using Synaptic where it appeared as 0.95.1. So, I thought to check. Otherwise, so far everything is fine.
