### ISSUE TITLE
"Creating" an existing folder in AutoKey then deleting it deletes the existing data

### ISSUE THREAD

**Issue by wjandrea** [autokey/autokey#332]
## Classification:

Data Loss

## Reproducibility:

Always

## Version

- AutoKey version: 0.95.8
- Used GUI (Gtk, Qt, or both): GTK
- Installed via: dpkg
- Linux Distribution: Ubuntu 18.04

## Summary

"Creating" an existing folder in AutoKey then deleting it deletes the existing data. In my case it was `~/.config`.

## Steps to Reproduce (if applicable)

- Create folder outside AutoKey plus a test file: `mkdir test; touch test/foobar`
- Create "New" folder `test` inside AutoKey
- Delete folder `test` inside AutoKey

## Expected Results

- Any files created by AutoKey (i.e. hidden files) are removed, but any others are not (i.e. `test` and `test/foobar`)

## Actual Results

- All files are removed including `test` and `test/foobar`

Log was deleted along with the the rest of `~/.config`, and it wasn't recreated on relaunching AutoKey and testing reproduceability.

## Notes

Similar to #171 

My personal workaround is to uninstall AutoKey. Data loss of this magnitude is unacceptable.

**Comment by luziferius** [comment]
Sorry to hear that AutoKey caused you to lose your configuration data.

It was caused by laziness on the programming side.

This old function was used to delete the directory. I think the original developer didn’t intent that it may ever be called on unsafe paths outside of `.config/autokey`…
https://github.com/autokey/autokey/blob/8735c107068e3069e55a19a4a287491539e3f580/lib/autokey/model.py#L524-L529

I’ve replaced it with a safe version that only deletes the files created by/within AutoKey, while keeping everything AutoKey does not know:
https://github.com/autokey/autokey/blob/67f8313593f888aac229aa21af0deea552f62e5f/lib/autokey/model.py#L524-L539

The calls to `child.remove_data()` in the first loop call to https://github.com/autokey/autokey/blob/67f8313593f888aac229aa21af0deea552f62e5f/lib/autokey/model.py#L732-L737
which are safe, too.
I used a search on the code base and didn’t find any more `rmtree()` calls.

**Comment by wjandrea** [comment]
OK cool! Much respect for fixing this so fast. I'll try AutoKey again in the next release, and make sure I have more recent backups ;)

**Comment by luziferius** [comment]
I just happened to look at GitHub while you posted the issue.

I always thought that the GTK GUI prevents users from adding already existing directories to the GUI. Well, it seems that it is possible…

**Comment by luziferius** [comment]
Done. You can grab 0.95.9 from here: https://github.com/autokey/autokey/releases/tag/v0.95.9
