### ISSUE TITLE
Manually added phrases work, but do not show up in GUI

### ISSUE THREAD

**Issue by dulawcdo** [autokey/autokey#353]
## Version

AutoKey version: 0.95.9-0

Used GUI (Gtk, Qt, or both): Qt 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (deb file).

Linux Distribution: Kubuntu

## Summary

Manually created JSON and TXT files in "My Phrases" folder do not show up in GUI, BUT the phrases work.

## Steps to Reproduce (if applicable)

- In "My Phrases" I create a TXT and JSON file manually, exactly copying the code of the others, changing only relevant info to create a new phrase manually, outside the GUI.
- I restart the GUI.

## Expected Results

- This should allow me to insert a phrase via the new abbreviation I created.
- The new phrase should show up in the GUI when Autokey restarts.

## Actual Results

- While the new phrase gets inserted when I type the abbreviation I manually made, it does not show up in the GUI. 

## Notes

The purpose of this is because I am moving the phrases from my previous text-expander to Autokey, and if I can get this to work, I would be able to streamline the process of dropping the relevant info into the JSON code template for phrases.

**Comment by josephj11** [comment]
If you completely stop AutoKey and then restart it, it should rescan its folders and your new phrases and scripts should show up. Just closing and reopening the AutoKey window isn't always enough.

This is a known issue. I thought there was an open issue for it, but I don't see it.

If you're modifying files outside of AutoKey, I don't think AutoKey should "watch" for that and update itself, but it would make sense to have a manual "Rescan" menu option.

I'm not sure whether this should be classified as a bug or an enhancement request.

**Comment by BlueDrink9** [comment]
Alternatively it may be cleaner to transfer theses using the scripting api

**Comment by josephj11** [comment]
@BlueDrink9 Not sure what you're suggesting.

If I need to clone a bunch of scripts or phrases, I'm going to do that outside of AutoKey and just copy them into the appropriate folder.

I know the API includes things for creating new phrases, etc., but I have no idea how it works and it sounds like an advanced feature I'll probably never personally need.

The typical use case I've seen so far, is someone coming from another package such as AutoHotKey and needing to mass import a bunch of existing phrases. Such a user may not know Python at all, let alone be able to craft an advanced script to create/migrate new phrases..

**Comment by BlueDrink9** [comment]
I think you might have misinterpreted me, I was making this suggestion for the OP. In case it is also relevant to you, I'll respond anyway.

Doing a bunch of unsupported, undocumented  manual file operations, manually creating separate specifically-formatted jsons without any errors, copying them into the right folder, then not having them appear in tho GUI doesn't sound like a better solution than:

* GUI > create new script
* pasting in generated functions
* running it
* restarting GUI.

Maybe you are scared off by the term "scripting api"? But creating a lot of new phrases by parsing existing regular text… that sounds like a job for a script, at least to my Linux ear. The scripting api is the bulk of the most clearly-labelled "documentation" outside of the wiki, so I think should be easy enough for new users to discover. Maybe the wiki could be updated with specific examples for this use-case.

If you can automatically parse the existing eg autohotkey macros enough to create a complex multi-line json with accompanying files, using undocumented key names, why not instead create a one-line function?

I'll update this shortly with a real example, but it's basically converting `@email::bluedrink9@users.github.com` into `create_phrase("phrase @email", "bluedrink9@users.github.com", "@email")`

 Not "advanced".

We can't expect users to not be able to look up basic python function syntax, yet understand `json` formatting and get everything right just using those. Autokey advertises its python use pretty heavily, so lots of users probably start using it at least willing to learn.

**Comment by dulawcdo** [comment]
Writing to confirm that the reason it was not re-scanning was that closing the GUI window had not actually closed Autokey.

After actually closing the program and restarting it, it did the rescan and the new manually-created phrases showed up in the interface.

**Comment by josephj11** [comment]
@BlueDrink9 
This would be better on Gitter. The rest of this isn't really tied to this particular issue.

Yes, it is a job for a script. I just don't see why AutoKey would be involved. It's a one time conversion, not something I/the OP want to trigger regularly (although, I'm open to a spiffy script that really makes doing this easy.)

Not everyone knows Python (or needs to.)
I'm probably a permanent Python newbie myself. I teach bits of it to myself when trying to answer questions on our list or working with my own AutoKey scripts.

My approach was to manually let AutoKey create one phrase and .json file which I then used as templates, just replacing a few fields with tags such as TEXT, ABBREVIATION, ... That way, a simple sed or other batch editor can use them to create working phrases without knowing almost anything about json format (because I know almost nothing about it.)

I used this approach with a bash script (which I am pretty good at).

We have a bunch of users (no idea how many) who just use phrases. 
I'm rambling here, but I guess my main point is that AutoKey is a tool suitable for end users who don't know Python at all - not just for those of us with deeper programming backgrounds.

So, anything we can do to make the package more useful for these basic users will really help.

**Comment by Elliria** [comment]
It seems that this issue can be closed, since the OP was able to successfully achieve the goal by fully shutting down and restarting AutoKey, but I thought I'd jump in on the conversation that went on beyond that by suggesting that perhaps an AutoKey script could be created that uses the [create_phrase](https://autokey.github.io/api/engine.html#autokey.scripting.Engine.create_phrase) API call in a script that loops through the files in a specified directory to get all of their filenames and contents and puts them into a dictionary as keys and values and then loops through the dictionary and uses the keys as the phrase names and the values as the contents for each generated phrase.

**Comment by josephj11** [comment]
@Elliria I will close this. Thanks.

AHK puts all its phrases in one big parameter file, so you have to parse it to extract the necessary information to create AutoKey phrases. Long ago and far away, I wrote a proof of concept bash script that does this. It's useful, but has severe shortcomings because it only handles phrases with texts that are one line and only converts a couple of AHK's many attributes. This script is available upon request to any one who asks. Support from me for enhancing it is negotiable (depending mainly on whether I have time).

Since this issue was opened, AutoKey has been enhanced to watch its config directories for changes and update itself when they occur. This still doesn't (and probably shouldn't) work for folders outside of the AutoKey config directory tree, but quitting and restarting AutoKey rescans them as well.

**Comment by Elliria** [comment]
> AHK puts all its phrases in one big parameter file, so you have to parse it to extract the necessary information to create AutoKey phrases.

I didn't realize that.

You might want to put your script into the wiki with a disclaimer about the shortcomings so that the next person can come along and alter it if they like.

By the way, this one ended up on the radar thanks to CodeTriage. It really is helping us out even if it's usually getting us to help ourselves.

**Comment by josephj11** [comment]
We have had two new people inquire about development who appear to have gotten here through Code Triage. :)

**Comment by Elliria** [comment]
Yeah, I noticed that and am loving it. The more, the merrier, and I hope they choose to stay.
