### ISSUE TITLE
autokey-qt is not in the repositories

### ISSUE THREAD

**Issue by Lonniebiz** [autokey/autokey#362]
I'm having to use autokey-gtk in Kubuntu 19.10, because autokey-qt is not in the repository.

On my 4K monitors, autokey-gtk's font-sizes are so small that I have to use the desktop's accessibility zoom features while using the application. Autokey-gtk doesn't seem to honor the desktop-level font settings provided by KDE:
![2020-02-08 09_28_11 415](https://user-images.githubusercontent.com/151919/74087869-cbcb5f00-4a55-11ea-8459-896dee887b11.png)

So I was hoping that autokey-qt might honor those settings, but I see no way to install it.

Please advise.

**Comment by luziferius** [comment]
The Debian/Ubuntu packages are unmaintained, because their maintainer vanished years ago. They purged the Qt interface, because it depended on outdated and removed PyKDE4. The newest versions resolved those issues and work fine on 19.10. (I’m using them on Kubuntu 19.10.)

Until https://github.com/autokey/autokey/issues/269 gets resolved eventually, grab both the `autokey-common` and `autokey-qt` package attached to the releases from here https://github.com/autokey/autokey/releases or build your own packages (https://github.com/autokey/autokey/wiki/Packaging).

Because we had about 3 PPAs that popped up and then vanished again, we currently have no official repository for Debian with automatic updates. You can use GitHub and watch the project in "Releases only" mode, which should send you a notification on new releases.

Installing the packages: https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives

**Comment by luziferius** [comment]
@Lonniebiz Debian accepted 0.95.9 in their unstable repositories, including the Qt5 interface: https://tracker.debian.org/pkg/autokey.
Because (K)Ubuntu lends many of the Debian Packages, it is just a matter of time until they hit Ubuntu.
I hope they make it in time for the next LTS release in April.

Closing this, because it is fixed on the Debian side and will only take time to reach everyone.

**Comment by Lonniebiz** [comment]
In the meantime, I was able to get autokey-gtk's font-size to a normal level in Kubuntu on my 4K monitors by forcing a higher DPI of 192 : 
![GTKfontSize](https://user-images.githubusercontent.com/151919/74240679-1a6c3980-4ca0-11ea-866c-caaf43456d4c.png)

This also fixed font-size issues I was having in other GTK apps that were hard to read on my 4K monitors in Kubuntu (KDE).

**Comment by luziferius** [comment]
@Lonniebiz https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=autokey
autokey-qt 0.95.9 was uploaded to the Ubuntu 20.04 repositories and will be in the next LTS.

Our package has a lower build number, so if you don’t update to 0.95.10, you’ll automatically migrate to the Ubuntu packages when you update to 20.04.
