### ISSUE TITLE
Lintian warning: icon-size-and-directory-name-mismatch autokey.png 92x91

### ISSUE THREAD

**Issue by anthonyfok** [autokey/autokey#369]
## Classification

Bug or UI?

## Summary

Before I forget to report: Debian’s Lintian tool reports the following warning:

> W: autokey-qt: icon-size-and-directory-name-mismatch usr/share/icons/hicolor/96x96/apps/autokey.png 92x91
N:
N:   The icon has a size that differs from the size specified by the name
N:   of the directory under which it was installed. The icon was probably
N:   mistakenly installed into the wrong directory.
N:   
N:   Severity: normal, Certainty: certain
N:   
N:   Check: desktop/icons, Type: binary, udeb
N:

## Notes

I noticed that config/autokey.svg is 96×96, so perhaps regenerating its PNG counterpart making sure it is 96×96 instead of 92×91 would do the trick?

**Comment by luziferius** [comment]
Re-rendering it should fix it. I think it is 92x91, because the SVG contains a transparent border, which got cropped during the export of that PNG file.
The PNG icon was previously put into the _scalable_ directory (in 0.90.4), and I moved it to the best-fitting size directory. I’ve put this issue onto the TODO list for the next bugfix release (0.95.11)

When working with the SVG, please take note of issue #160. Qt5 can’t properly render our icon, because it does not conform to the SVG Tiny 1.2 specification. (See the linked issue for images showing the problem.) This affects all Qt-based applications.

I’ve re-rendered it to 96x96. You can take this, if you want to fix it right now and carry a patch:
![autokey](https://user-images.githubusercontent.com/2143820/75028642-e9121b80-54a0-11ea-8088-a09d2f6ba803.png)

**Comment by luziferius** [comment]
@anthonyfok Done. The warning will be fixed in the next version.
