### ISSUE TITLE
Assign "<alt>+q" to "<alt>+<f4>" seem does not work for most applications.

### ISSUE THREAD

**Issue by lewtran** [autokey/autokey#376]
## Classification:

Bug

## Reproducibility:

Unable

## Version

AutoKey version: 0.95.10

both

Installed via: pacman aur

Linux Distribution: Manjaro Gnome 19.0

## Summary

Assign "<alt> + q" to "<alt> + <f4>" seem does not work for most applications.
Tested work on: Chrome
Tested not work on: vscode, terminal, nautilus, telegram, whatsapp...

**Comment by luziferius** [comment]
This should probably go into the "Known limitations" section in the wiki.

`<alt>+<F4>` is interpreted by your window manager or the global background daemon that handles those global shortcuts. AutoKey directly sends input to the window holding the input focus. So your window manager won’t see the events, as they are directly sent to the application. Or the window manager ignores programmatically generated key inputs.

I assume it works on Chrome, because the browser internally interprets `<alt>+<F4>` and quits on it’s own.

**Comment by lewtran** [comment]
Thank you so much for your reply. I will try another method

**Comment by luziferius** [comment]
(Just as a note, here is `<Alt>+<F4>` assigned to "close window" on KDE (disregard the partial German locale, i can’t force the full English translation somehow):
![kwin_alt_f4](https://user-images.githubusercontent.com/2143820/75375959-7c978200-58cf-11ea-97a7-8bd7dd4607f4.png)

It should work, if you trigger the application-handled shortcut (`<Ctrl>+Q`).

Or use a Script and send a command to the window manager using the `dbus-send` CLI tool. It may be worth exploring the DBus interface, if your window manager exposes one. You can use the `qdbusviewer` GUI to explore the available interfaces.

**Comment by lewtran** [comment]
I can easily did it in Gnome Keyboard hotkey, no need to bind the key.
Thank you so much for your help! @luziferius
