### ISSUE TITLE
Dont delete external folders

### ISSUE THREAD

**Issue by morganrallen** [autokey/autokey#388]
When the drop-down menu is used to add an external Folder, removing it from the tree view should *never* delete the directory from disk, especially not recursively. This is a dangerous design, thankfully nothing too critical from my devel directory was blown away and that I hadn't added my home directory by mistake.

**Comment by luziferius** [comment]
Which version do you use?

The latest version 0.95.10 is safe as it won't delete unkown user files.

Offering the choice to keep things sounds like a nice enhancement, though.

**Comment by morganrallen** [comment]
Ah yep, classic Ubuntu shipping 0.90.4

**Comment by luziferius** [comment]
Fortunately, 20.04 will ship the newest version.

**Comment by josephj11** [comment]
I can't wait until 20.04 and all the related distros start getting the new version of AutoKey instead of the almost 8 year old dead version they have been providing! So many unnecessary problems will go away. We didn't have a maintainer for our Debian package for a long time, but we just got a new one. If you don't want to wait or upgrade your distro right away, you can easily install the new version by following the instructions here: https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives
