### ISSUE TITLE
which is the official repo?

### ISSUE THREAD

**Issue by MBuchaus** [autokey/autokey#39]
I've opened https://github.com/guoci/autokey-py3/issues/19  which is the official Looks like this one  but arch is pulling from guoci I think?

**Comment by josephj11** [comment]
This is the "original" version of AutoKey. It's currently based on Python 2.7. The other one is a branch of this which was converted to Python 3.x.

We went through a long spell with no developers and a new one has just started helping us. Getting our distribution chain back up to speed is a top priority.

I have not used the other branch, but AFAIK, it's a valid, maintained project as well.

We also maintain a support list at https://groups.google.com/forum/#!forum/autokey-users

If we can help in any way, post there. I don't check here as frequently.

**Comment by josephj11** [comment]
Just took a very brief look at your link. Since it's on the other project, I won't try to get into any detail. But ...

Depending on what you're trying to do, there are a few gui routines in our API for getting user input, etc. which might be sufficient so that using easygui might not be necessary. Again, I just glanced at your issue, so I can't say for sure.

We're in the process of porting our documentation from code.google to GitHub, but for now, you can look at
https://autokey.googlecode.com/svn/trunk/doc/scripting/index.html

It has stuff for GTK and for QT - depending on which front end you are using. If it doesn't display correctly, try a different browser.

If you choose to install our version of AutoKey, then you can post on our list and we'll see if we can help you to get it working. I know just a little Python. (I'm not trying to be territorial, etc. It's just that I only have this version installed, so that's all I can test against in developing a solution.)
