### ISSUE TITLE
how to make a hotkey triggered everywhere exclude a certain window?

### ISSUE THREAD

**Issue by OriLiMu** [autokey/autokey#400]
I check the option of the hotkey only have the option about trigger key under a certain window.
What I want is opposite how to make a hotkey triggered everywhere exclude a certain window

**Comment by josephj11** [comment]
We appreciate  and support usage questions, but they should be made on our [Gitter](https://gitter.im/autokey/autokey) account or [support list](https://groups.google.com/forum/#!forum/autokey-users).

Theoretically, you would handle this by using negative patterns in the regex used to specify the window filter. In practice, this does not currently work because the window filter regex is applied to both the window title and the window class and it's almost impossible to not match both. See #305.
