### ISSUE TITLE
Abbreviations not really saved

### ISSUE THREAD

**Issue by snoopy48** [autokey/autokey#41]
Hello!

I have my system  (Linux 13 Maya, Cinnamon) newly installed because of problems with Autokey. Now Autokey runs with one small problem: I can't define anymore abbreviations.
- the old imported abbreviations work!
- newly created abbr. are first shown but they are shown equally for all other items (until I reopen AK)
- when I open the respective .json file I see that there is no abbr. stored
- when I insert the abbr. manually in the .json file it does not work also

Enclosed the report, apparently a problem of the "dbus". But how to resolve? Why does it not work when I manually define the abbr. in the .json file?

`2016-04-10 12:52:47,563 DEBUG - root - AutoKey is already running as pid 3035
2016-04-10 12:52:47,575 ERROR - root - Error communicating with Dbus service
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autokey/gtkapp.py", line 106, in __verifyNotRunning
    dbusService = bus.get_object("org.autokey.Service", "/AppService")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.autokey.Service was not provided by any .service files
`

**Comment by josephj11** [comment]
We've had several issues recently which involve dbus error messages (but not this particular one). The underlying cause has not been determined yet.

First, let's eliminate the obvious.

After you added a new phrase, did you click on the  Save button?

What do you mean by "shown equally"?

Did you check for directory/file permission problems? (probably OK, but let's be sure.)

By default, AutoKey stores phrases in `$HOME/.config/autokey/data/My Phrases`. Each phrase will have two files, `phrase_name.txt` and `.phrase_name.json` (hidden because its name starts with a dot). Your user should own and have 775 permissions for all directories in this path and 664 permissions for all the macro and phrase definition files.

As far as manually editing json files, that shouldn't be necessary. If you create (in any way) a pair of files (`name.txt` and `.name.json`) as described above) for a new phrase and save them in the `My Phrases` directory, AutoKey will find them automatically the next time it starts (if not sooner) and make them available.

**Comment by snoopy48** [comment]
Hi Joe!

Thanks for your hints. Now it works again ;-)

Short additional question because I can't find it: with which command can I
open a certain site (for example google.com) in the browser and switch to
it ?

best regards
Bernhard

2016-04-20 19:02 GMT+02:00 Joe <notifications@github.com>:

**Comment by josephj11** [comment]
Do you know what you did which eliminated the issue for you?

Your new question is not an AutoKey "issue", so it would be better to discuss it on our support list
[](https://groups.google.com/forum/#!forum/autokey-users01)

Briefly, Python has system commands for running any command from within a script. They could be used to start your browser. The issues beyond that would be to figure out if it was already running, to find the window (and, possibly, the correct tab), and switch to it. All doable in Python, I'm sure, but beyond what I know how to do.
