### ISSUE TITLE
Autokey writes intensively to log file, how to disable it?

### ISSUE THREAD

**Issue by ReneFroger** [autokey/autokey#43]
Thanks for sharing this nice addition, it's appreciated! I have the following Autokey script:

```
 # Enter script code
 keyboard.send_key("<right>")
```

It's bounded to the key Alt+ l (that's a lowercase L there). I use it regular. But I see tenthousands of these logs in autokey.log:

```
 2016-06-03 22:11:58,291 INFO - service - Matched hotkey phrase/script with prompt=False
```

Is there any way to turn off logging in Autokey? It's not available in the preferences menu.

**Comment by josephj11** [comment]
Hi. Well that's a new one. I always have to ask people to turn tracing on! Generally AutoKey tracing is off. It is enabled by running autokey-gtk -l (that's an elll too), but there should be no connection - and that produces logging output on the terminal, not in the log.

So, where did you get your copy of AutoKey? Take a look at [this](https://github.com/autokey/autokey/wiki/Problem-Reporting-Guide(url)) and give us some more information.

I'm keeping this project alive, but I don't know much Python or any AutoKey internals. We have a new developer, but he hasn't had time to actually do anything yet.

I had never looked at my autokey.log  file before. Mine is 20,000 lines long (really needs truncating!), but only the last few are  from today. I'm running Kubuntu 12.04 with autokey 0.90.4 - slightly behind 0.90.4-1 which is what we have on GitHub (and seems to be in use in some distros) .

I'm wondering if that log event was somehow accidentally enabled in 0.90.4-1 - which was never really totally ready for prime time. The developer we had then quit before a release could be tested.

All I can suggest is to look through the source code if you are capable to try to find the origin of the message. If not, just truncate your log file periodically or try the Python 3 branch of [AutoKey](https://github.com/guoci/autokey-py3) and see if it works any better for you. That branch had an active developer last I checked.

**Comment by ReneFroger** [comment]
Hi there! Thanks for your friendly response! 
I use Xubuntu 16.04 with Debian package manager, and I installed autokey with `apt install autokey-gtk`. There is further no logging enabled in all setups and on multiple desktops. I will give the Python 3 branch of Autokey a try, if it might help. Thanks for the suggestion, it's appreciated.

**Comment by Disclosure** [comment]
Can confirm the issue, it exists both in the official 16.04 repository, as well as the experimental ppa. Autokey logs every key press which should not be necessary.

**Comment by xrat** [comment]
I don't know Python, but `gtkapp.py` here has the same code as https://github.com/autokey-py3/autokey/blob/master/lib/autokey/gtkapp.py#L65 and this looks like there is no way to disable the logging. It can only be made more verbose. Changing `LOG_FILE` in `common.py` to `"/dev/null"` could be a workaround.

**Comment by Disclosure** [comment]
Found where the logging happens: https://github.com/autokey-py3/autokey/blob/master/lib/autokey/service.py#L136

Lines 136 through 140 deal with with logging of the key press matches. The easiest solution may be simply to nuke those lines. That really should be on debug level logging, not info, but I wouldn't be bothered enough to figure out how to implement that.

**Comment by Disclosure** [comment]
I tried setting those lines to logger.debug rather than logger.info, that appears to have worked, the log file is not littered with key presses any more. I'll pull the repo, make an update and send a pull request for it.

**Comment by josephj11** [comment]
I don't know a lot of Python or AutoKey internals.
I did a comparison between service.py in autokey and in autokey-py3. The logger.info settings are identical in both versions, so while changing that may eliminate the symptom. It probably does not address the underlying issue.

Since the AutoKey trace is an invaluable tool for debugging macros and other issues, you should run a few traces and make sure that this change doesn't make them harder to read, etc..

This (main) branch of AutoKey no longer has a developer, so if this is a bug, it's not likely to get fixed here.

I highly recommend that new users and current users with any issues switch to using the Python 3 branch of the project because it:

- has an active developer who can address issues
- is based on Python 3 which has much improved handling of multibyte character sets
- has numerous bug fixes
- has a few very useful extensions including the ability to move the mouse to locations on the screen
  based on simple image pattern searches so you can position to fields and buttons that are not 
  accessible via keyboard key sequences

Also, as always, feel free to join us on the [support](https://groups.google.com/forum/#!forum/autokey-users) list where we attempt to support users of both branches.
