### ISSUE TITLE
App wont start

### ISSUE THREAD

**Issue by QQ-88** [autokey/autokey#433]
## Classification:

Crash/Hang/Data Loss

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10-1

Used GUI (Gtk, Qt, or both): Qt

Installed via: Pamac

Linux Distribution: Manjaro

## Summary
After over a year of usage the app won't start anymore, might be related to a recent update.
Tried to reinstall, still the same. Running it in terminal results in this: https://pastebin.com/Pj1jjU8U

**Comment by josephj11** [comment]
Can you figure out what was updated on your system since the last time AutoKey worked?

I don't know Arch (which Manjaro is based on,) so I'm probably going to bungle this explanation.

We had a similar problem before. It involved Arch naming updated packages with the version number as part of the name. AutoKey was looking for the old version name of something and couldn't find it.

Based on this (which might be wrong), I would try uninstalling then reinstalling AutoKey after first making a backup of your config directory which normally contains all your phrases and scripts. Be sure you backup includes all the hidden files. By default it should be the directory tree starting at $HOME/.config/autokey/

Either the reinstall will fix it or perhaps it will complain about a specific missing dependency so you'll know what needs fixing. It couldn't find 'Qsci' from 'PyQt5', so maybe the PyQt5 module has been updated.

Don't invoke autokey-run. It's a special purpose tool for running AutoKey scripts from the CLI instead of from within AutoKey.

**Comment by josephj11** [comment]
If the above doesn't fix it and one of our developers doesn't chime in with a better answer, you could try temporarily creating a new user account and installing AutoKey there to see if it works. If it does, you can look for what's different.

Since it's complaining about something related to Qt, you could also try installing and running autokey-gtk. The two front ends can coexist as long as you only run one at a time and they both rely on autokey-common to do all the non-GUI work. In the unlikely case that your system doesn't already use any GTK applications, this will pull in a bunch of libraries.

See also #199. It's a little different, but might give you some clues.

**Comment by QQ-88** [comment]
The issue was me setting the time format from US to my local format as I prefer 24hrs. Seems it was set to US during a recent update.
Setting it back fixed it. Seems to be a KDE issue based on what I read.

Thanks for looking into this.

**Comment by kreezxil** [comment]
so i had to reloaded my base operating system after experimenting with it too much and upon reinstalling autokey i could not longer use autokey-qt, gtk was fine.

After much poking around turned out that installing qscintilla-qt5 and python-qscintilla-qt5 resolved the issue for me. I don't know what i had before in the system. I am going to assume that some other package that i don't remember installed those dependencies.

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.4.64-1-MANJARO
OS Type: 64-bit
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: GeForce GTX 750 Ti/PCIe/SSE2
```

**Comment by josephj11** [comment]
So, if this is resolved, you can close this issue. I'm glad it works for you now. We have a number of Arch/Manjaro users.
