### ISSUE TITLE
ImportError: No module named pytz

### ISSUE THREAD

**Issue by godspeedyou** [autokey/autokey#443]
## Classification:

Feature

## Reproducibility:

Always

## Version

AutoKey version: 0.90.4

Used GUI (Gtk, Qt, or both): gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: PPA

Linux Distribution: Ubuntu 18.04.5

## Summary

I want to use the pytz lib to be able to transform datetimes into different time zones.

## Steps to Reproduce (if applicable)

`import pytz`

## Expected Results

No error, but usage of pytz.

## Actual Results
ImportError: No module named pytz

## Notes

-

**Comment by josephj11** [comment]
Please upgrade to 0.95.10 and see if the problem persists. 0.95.10 is based on Python 3, so the availability of modules will definitely be affected.

----
0.90.4 is almost eight years old and unmaintained. You should really upgrade if at all possible.

Unfortunately, Debian had no one assigned to updating their AutoKey package and most Debian-based distributions get AutoKey from them so you still get 0.90.4 when you use their repositories prior to 20.04.

To upgrade:

If you have phrases and scripts, you need to save them:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.

If you are using Ubuntu 18.04 or a derivative, you can definitely use our pre-built deb files. However, since most of AutoKey is specific Debian release independent, our deb files should work in other Debian-based distros and releases.

All our current deb files are built for Ubuntu 18.04. If you are using a distro which doesn't support deb (apt) packages or installing from the deb packages fails, install using pip. See below.

AutoKey releases are available here:

https://github.com/autokey/autokey/releases/

Select the one you want and then download the common and gtk debs to a directory on your system

Change into that directory (in a terminal) then

To install it on a Debian-based system, use the following:

sudo dpkg --install autokey-common_VERSION_all.deb autokey-gtk_VERSION_all.deb

(substituting the version you downloaded for "VERSION".)

They need to be installed at the same time and dpkg will get it right while apt might not.

If you're using the QT front end, you can download and install that instead of (or in addition to) the GTK version.

Otherwise, you need to install using pip.

Follow the instructions here:
https://github.com/autokey/autokey/wiki/Installing#pip-installation
That will get you up to our current version.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.
