### ISSUE TITLE
Python script not getting triggered automatically via abbreviation

### ISSUE THREAD

**Issue by physicophilic** [autokey/autokey#446]
## Reproducibility: Always

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Gtk  

Installed via: package manager

Linux Distribution: Ubuntu 20.04

## Summary

Script does not execute unless button in GUI is pressed.

## Steps to Reproduce (if applicable)

Use a subroutine.run in the script to call a sed command.
Set the script to run immediately after entering abbreviation.

To be specific, I was using
sed -i '/\$\$/!b;n;s/\(.*\)\([a-zA-Z]\)hat/\1\\hat{\2}/' /home/manish/a.md
which replaces ahat with \hat{a} for any a in file a.md. That might not be important however.

## Expected Results
Script should run, like it runs when called externally. 

## Actual Results
Two possibilities:
(a) either you'll see a popup "file has changed, load file again" - but nothing would be different
(b) no change at all, with no pop up.

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
020-09-30 22:08:15,134 DEBUG - service - Raw key: 'a', modifiers: [], Key: a
2020-09-30 22:08:15,135 DEBUG - service - Window visible title: 'Untitled• - Typora', Window class: 'typora.Typora'
2020-09-30 22:08:15,135 DEBUG - service - Input queue at end of handle_keypress: deque(['a'], maxlen=150)
2020-09-30 22:08:15,575 DEBUG - service - Raw key: 'h', modifiers: [], Key: h
2020-09-30 22:08:15,576 DEBUG - service - Window visible title: 'Untitled• - Typora', Window class: 'typora.Typora'
2020-09-30 22:08:15,576 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'h'], maxlen=150)
2020-09-30 22:08:15,736 DEBUG - service - Raw key: 'a', modifiers: [], Key: a
2020-09-30 22:08:15,736 DEBUG - service - Window visible title: 'Untitled• - Typora', Window class: 'typora.Typora'
2020-09-30 22:08:15,737 DEBUG - service - Input queue at end of handle_keypress: deque(['a', 'h', 'a'], maxlen=150)
2020-09-30 22:08:15,885 DEBUG - service - Raw key: 't', modifiers: [], Key: t
2020-09-30 22:08:15,885 DEBUG - service - Window visible title: 'Untitled• - Typora', Window class: 'typora.Typora'
2020-09-30 22:08:15,886 INFO - service - Matched Script "hat_regex" having abbreviations "['hat']" against current input
2020-09-30 22:08:15,886 DEBUG - service - Script runner executing: Script('hat_regex')
2020-09-30 22:08:15,886 DEBUG - service - Input queue at end of handle_keypress: deque([], maxlen=150)
2020-09-30 22:08:15,886 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-09-30 22:08:21,232 DEBUG - iomediator - Key.ALT pressed
2020-09-30 22:08:21,273 DEBUG - service - Raw key: <Key.TAB: '<tab>'>, modifiers: [<Key.ALT: '<alt>'>], Key: Key.TAB
2020-09-30 22:08:21,273 DEBUG - service - Window visible title: 'Untitled• - Typora', Window class: 'typora.Typora'
2020-09-30 22:08:21,375 DEBUG - iomediator - Key.ALT released

```

## Notes

hat_regex is the script name.

I confirm that the python script is executing properly on the abbreviation if I use something like "touch a.md" in the bash script. 
Problem seems to be related to the sed command.

I don't have any workaround.

**Comment by josephj11** [comment]
I'm not adept in Python, so keep that in mind...

As you note, AutoKey is running your script and, standalone, the script works - just not from within AutoKey.

I would like to see the actual script code or a small script that just recreates the problem. sed is very touchy about syntax and not very helpful when errors occur, so maybe something in the way you are invoking it from within Python is messing things up.

I am not familiar with anything called a "subroutine" in Python. I do know about "functions."

While it's fine, your script (at least the part you are describing) is unusual because it does not interact with the currently active window. It works directly on a file.

Normally, when I need to run external code from within AutoKey (Python), I use the subprocess module. e.g.:

If I need the output of the command, I use something like:
`cmd = subprocess.check_output(["fh", "Hello World!"])`

If I don't need the output, I use something like:
`subprocess.call(["xdotool", "click", "1"])`

If there is a reasonable chance that the external program can return a non-zero exit status, I run it from within a 
try: ... except: ... block to handle that possibility.

**Comment by physicophilic** [comment]
**I got the issue**

> While it's fine, your script (at least the part you are describing) is unusual because it does not interact with the currently active window. It works directly on a file.

You are right. This helped me understand the issue.

Please let me explain. I was running the script given below very naively in the currently active file itself - a.md, opened in Typora. I wanted to trigger sed to make a replacement as I would type a keyword within a.md. 

My desire was to get a phrase which would take regex as abbreviation, here for example a LaTeX code for ahat -> \hat{a}, bhat -> \hat{b}, etc. but I couldn't see how autokey could do that, hence I used sed, which when called externally did the job.

Problem was that it was running only when the focus was on some other window - whether I would call it from shell, or autokey-gtk button. Even a gnome shortcut to execute the same bash script wouldn't work within a.md.

This was my mistake. I should close this issue, but I would request help on how I can achieve my regex abbrv goal if possible.




**More details if they are still relevant:**

>I would like to see the actual script code or a small script that just recreates the problem. sed is very touchy about syntax and not very helpful when errors occur, so maybe something in the way you are invoking it from within Python is messing things up.

>I am not familiar with anything called a "subroutine" in Python. I do know about "functions."

Sorry, it was subprocess, I am not familiar with this module; just been googling. Here's the script I am using now.

```
import subprocess as sub
sub.call(['/bin/bash', '/home/manish/hat.sh'])
```

Contents of hat.sh:
```
#!/bin/bash
sed -i '/\$\$/!b;n;s/\(.*\)\([a-zA-Z]\)hat/\1\\hat{\2}/' /home/manish/a.md 
```

Contents of a.md
```
$$
ahat
$$
```

**Comment by josephj11** [comment]
Glad you figured out what you were doing wrong ... However, that doesn't help with doing it right. :)

First, a side note: To do something like you were trying to do, you don't need bash. You can just call sed directly.

On to the actual issue.

Your solution lies in a script, not a phrase, because doing it with a phrase is more convoluted.

You want to take any character you supply and surround it with a LaTeX construct. (I ignore typing the "hat", because it's probably unnecessary unless your source file already has these things in it.) This is a bit tricky because it requires providing variable input to your script and surrounding it.

The clunky, but simple approach would be to have your script pop-up an input dialog box where you could type the letter to be surrounded and use that to build the output string and then paste it.

A better approach might be to type the letter in question and then trigger your script with a hotkey. The script would:
type a Shift+Left to select the character you just typed
type a Crtl+x to cut it to the clipboard
get the contents of the clipboard into a variable
create the new string of LaTeX using the contents of the variable
paste the new string into your document

This would work for any character which is a double edged sword. It makes it easy and flexible to use, but
it would work just fine for characters for which adding a diacritical mark is not defined
and, if some text was selected prior to running the script, the Ctrl+Left would add to that selection instead of starting a new one as desired. So, once you got it to work, it would require some stepwise refinement to make it production ready.

Whenever you need help figuring out something like the above, feel free to come over to our [support list](https://groups.google.com/forum/#!forum/autokey-users) and ask away.

Finally, it would be good to close this issue because it's not a problem with AutoKey.

**Comment by physicophilic** [comment]
Good to know about the pop-up approach, but it isn't what I am looking for as you guessed.

The script idea however is really good. I will try implementing that. Thanks a lot for your help!

Closing this issue.
