### ISSUE TITLE
PayPal Donations link does not work

### ISSUE THREAD

**Issue by CoolSpot** [autokey/autokey#45]
Wneh I click "PayPal" button [here](https://github.com/autokey/autokey/wiki) or on Google code, PayPal shows this message:

> PayPal cannot process this transaction because of a problem with the seller's website. Please contact the seller directly to resolve this problem.

**Comment by josephj11** [comment]
Wow! That's not a problem I expected to run into. Thanks for your intention.

On code.google, the link was to Chris Deckter who originally wrote AutoKey,
but left the project around two years ago. I don't have any idea where the
link here points to. (I'll find out.)

Right now, we don't have any way to use donations unless they're large
enough to hire a Python programmer because we don't have an active
developer. If you know anyone who actually has time to help, please send
them our way!

I'm doing most of the work on the project, but that consists of answering
questions here and on our support list. I also try to keep the project
going.

I'll fix the link here. Then, I'll just have to figure out what to do with
any money that gets donated.

Thanks again.

Joe
