### ISSUE TITLE
Request - Would like to have option for a custom default folder

### ISSUE THREAD

**Issue by phd21** [autokey/autokey#47]
Dear Autokey,

Absolutely wonderful application. 

Is anyone maintaining it ?

Request - Would like to have option for a custom default folder. In my Linux Mint KDE (17.3) system, all my Autokey configurations are store in a hidden folder. It would be great if users could specify their own default folder which makes backing it up easier. Thanks.

**Comment by josephj11** [comment]
Thank you.

Well, sorta... I'm the current chief, cook, and bottle washer since our main developer quit around 2 years ago. We have since moved to GitHub and are working on documentation. We have had several short-term developers assist us - which is where 0.90.4.1 came from.

If you know of any Python developers with some time to donate to a very good cause, please send them our way.

As for your immediate need, I think we already have that covered if you look at it a bit differently.

In the main AutoKey window,  select File->New->Folder. This should allow you to crate a new top level folder (or sub-folder) anywhere you like in your file system (e.g. your hidden folder).. Under that, you can create a sub-tree to your liking - perhaps with a folder for scripts and another for phrases, but you can do anything you like. Each user would have to do this or you can distribute an autokey config sub-tree to each of them with this already configured. As long as the directory is under the user's home directory, it will be unique to each user. 

I keep all my scripts in $HOME/autokey_scripts which works quite nicely and does in fact make backups a lot easier (and prevents accidents caused by package managers doing things like purges from deleting all your hard work).

That should cover it (unless I missed what you really need).

If you need to get fancier, you can even build multiple configs for the same user and make the main AutoKey configuration directory a symlink to one of them. Then, you can switch configurations by changing the symlink. I would terminate AutoKey before doing that and then restart it afterwards.

BTW, when you first have a problem or an idea for an enhancement, you'll almost always get better and faster support by posting on our [support list](https://groups.google.com/forum/#!forum/autokey-users) . 

There are a number of users there who can help while there are only two of us here. Also, this doesn't add new project issues for things which can be resolved more informally.
