### ISSUE TITLE
Autokey seems not to be working in Elementary OS (Hera)

### ISSUE THREAD

**Issue by codewithpatelo** [autokey/autokey#490]
## Classification:

 UI/Usability

## Reproducibility:

Install Autokey in elementary OS 5.1.4 Hera (apt install)

## Version

AutoKey version: 0.90.4-1.1 

Used GUI (Gtk, Qt, or both): Gtk

Unsure

Installed via: (PPA, pip3, …). apt install

Linux Distribution: elementary OS 5.1.4 Hera (Ubuntu-Debian based but with a different desktop system called pantheom)

## Summary

I installed autokey-gtk, opened it and tried sample scripts by running them, most of them didn't do anything. When I try to set hotkeys to them, it prompts me with "insert a key to continue" but I press a key and nothing happens.

## Expected Results

Autokey executing desktop automation tasks and setting up hotkeys without problems.

## Actual Results

It simply hangs up there, nothing happening even if I press a key:
![image](https://user-images.githubusercontent.com/16574952/101587134-46d90b00-39c2-11eb-8a06-290f8acb6c82.png)

**Comment by josephj11** [comment]
Welcome to AutoKey. The first step is to upgrade from the version that was buried in the pyramids with the Pharaohs. :)
0.95.10 is the current release.

If any problems remain after that, then post on our [support list](https://groups.google.com/forum/#!forum/autokey-users) and we'll get it sorted.

----

0.90.4 is almost eight years old and unmaintained. You should really upgrade if at all possible.

Unfortunately, Debian had no one assigned to updating their AutoKey package and most Debian-based distributions get AutoKey from them so you still get 0.90.4 when you use their repositories prior to 20.04.

To upgrade:

If you have phrases and scripts, you need to save them:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.

If you are using Ubuntu 18.04 or a derivative, you can definitely use our pre-built deb files. However, since most of AutoKey is specific Debian release independent, our deb files should work in other Debian-based distros and releases.

All our current deb files are built for Ubuntu 18.04. If you are using a distro which doesn't support deb (apt) packages or installing from the deb packages fails, install using pip. See below.

AutoKey releases are available here:

https://github.com/autokey/autokey/releases/

Select the one you want and then download the common and gtk debs to a directory on your system

Change into that directory (in a terminal) then

To install it on a Debian-based system, use the following:

sudo dpkg --install autokey-common_VERSION_all.deb autokey-gtk_VERSION_all.deb

(substituting the version you downloaded for "VERSION".)

They need to be installed at the same time and dpkg will get it right while apt might not.

If you're using the Qt front end, you can download and install that instead of (or in addition to) the GTK version.

Otherwise, you need to install using pip.

Follow the instructions here:
https://github.com/autokey/autokey/wiki/Installing#pip-installation
That will get you up to our current version.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by codewithpatelo** [comment]
Alright. I installed autokey 0.95 and, effectively, now it seems to be working. Thanks!
