### ISSUE TITLE
Possible to achieve LEAP functionality?

### ISSUE THREAD

**Issue by probonopd** [autokey/autokey#497]
## Classification:

Question

## Reproducibility:

I Didn't Try

## Version

AutoKey version: Any

Used GUI (Gtk, Qt, or both): Both

## Summary

is it possible to achieve LEAP functionality as known from the Canon Cat by Macintosh inventor Jef Raskin?

## Details

The Canon Cat had "LEAP", a function to quickly nagivate text.

It is explained in https://youtu.be/o_TlE_U_X3c?t=212.

![image](https://user-images.githubusercontent.com/2480569/101240049-fe34ff80-36ec-11eb-9759-4fa1c8aced31.png)

(On today's keyboards, we could e.g., use the Meta key or another key combination instead of the dedicated LEAP keys.)

According to https://patents.google.com/patent/US4806916A/ the patent on LEAP keys by Jef Raskin has expired in 2006. Could we implement it system-wide, e.g., in a Qt plugin?

The patent describes the LEAP keys in a somewhat long-winded way, but in principle it is quite simple: You can move the cursor by pressing the LEAP key (combination) and then typing some characters of the text location you would like to jump, or "leap" to. Similar to searching with Alt-F, but limited to the text field you are currently in, and not selecting the "found" text. Result: You do not need the mouse nor cursor keys to jump, or "leap", around in a text entry widget.

I assume the patent has expired, so this could be implemented in Open Source nowadays.

**Comment by josephj11** [comment]
This sounds like interesting functionality. I don't have time to research it, however:

When you associate a hotkey with a script, that script is written in full, native Python 3 which means it can do virtually anything, limited only by your creativity and skills as a programmer. So, yes, you can implement Leap functionality if you want to.

As for software patents (which are evil!), IANAL, but, if you implement something for your own personal use (not as part of a commercial product), no one is probably ever going to notice or care. Just don't rub it in their faces by using their name for it ("Leap"), etc.

Specifics
This functionality will require some finesse. You should write simpler scripts first to get used to how AutoKey works and how your system responds to it.

Your script would have to get subsequent keyboard input after it was activated to know where to leap to and it would have to deal with the issue of shorter targets being matched while you're still typing the search string.

Getting additional keyboard input in a running script is tricky if you want to do anything more elegant than popping up an input dialog box. It's doable, but a bit advanced.

If you approach it a bit differently and type the thing you want to find and then press the hotkey to activate your script, the code will be simpler, but you still have the problem of figuring out how many characters were typed and need to be selected, copied, and deleted from the text. That's easy if you can guarantee that the "word" to the left of the cursor is the search string. If that's not possible, then it's harder.

Once you capture the search string, you can just issue keyboard events using our API to find the text in the same way you would do it manually. Since AutoKey events often outpace an application's ability to process keyboard input, you would probably have to add delays after one or more of your keyboard event API calls.

If you save the search string in an AutoKey global stored variable, it would be available for use with "leap again" - presumably activated by a different hotkey/script.

----

Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by probonopd** [comment]
Thank you for your detailed answer.
Please allow for a short follow-up question:

> When you associate a hotkey with a script, that script is written in full, native Python 3 which means it can do virtually anything

Does this mean that the Python script has access to the text in the text field in which the cursor is positioned? The LEAP function requires the text surrounding the cursor to be searched, and the cursor moved to a certain position, and optionally text to be selected.

Maybe you can point me to an existing script which does a similar thing?

Thanks.

---

Will ask on list/Gitter next time.

**Comment by josephj11** [comment]
Not directly. You figure out how to do it manually using your keyboard and/or anything in Python or external that can be invoked using subprocess(), then you code that into an AutoKey script.

When possible, it's better to code and test as much as possible as standalone Python first where you can use IDEs and print() statements, etc. to debug the logic before putting it into the more opaque AutoKey environment. (You can dummy up the API calls with fixed responses until the rest works.)

I don't know about effective access to the text data, but to give you an idea, here's one inelegant way that might work.
Assume the text cursor is already in the text field (or do something to get it there.)
Issue a Ctrl+A to select all text
Get the selected text into a variable using an API call
Examine/process said text in your script - e.g. find the target
(If you modified the text, it's still selected and you can use an API call to paste it back into the field if you want to.)
Somehow figure out the offset from where the text cursor is now to where the target string is
  (I don't know how to figure out where the text cursor is to start with, but I'm relatively sure it's possible.)
Issue a number of left or right arrow key keypresses to traverse the offset or
Issue an application search forward/back command to move to the target

**Comment by probonopd** [comment]
Why was it closed? Not interested? Not technically possible?

**Comment by BlueDrink9** [comment]
A combination. The request isn't for autokey functionality. Autokey just runs scripts. This request is for a particular script, and hence is outside our scope. It is a support request if anything, and we prefer to keep those confined to platforms like gitter.

In addition, this would require access to the text in whatever context the user is in, which is gui framework dependent and _certainly_ outside autokey's scope

**Comment by probonopd** [comment]
Thanks for the clarification. So you think this would need to be implemented in each of the various GUI frameworks such as Qt, WxWidgets, Gtk, and so on?

**Comment by BlueDrink9** [comment]
Not implemented *in*, but definitely implemented *for*. You could possibly do it *with* autokey, but it isn't something that should be part of the core of autokey. It should be a user script
