### ISSUE TITLE
Assistance with simple keypress loop

### ISSUE THREAD

**Issue by zefrs** [autokey/autokey#504]
## Classification:

UI/Usability

## Reproducibility:

Unable

## Version

AutoKey version: 0.95.10

Gtk

Installed via: deb

Linux Distribution: Debian

## Summary

Noob question just need some assistance.

I have been using Keyboard Maestro on MacOS and would like to see if AutoKey can do the same.
I would like to press a key and simulate a keypress every 40ms (in a loop)

EDIT:
This is for a game key spam, so when i i hold down key X is spams key Y every 40ms until i release key X

**Comment by josephj11** [comment]
This is a bit tricky, but should be doable.

First, you have to launch your script by pressing and releasing a hotkey assigned to it.
A simple design for such a script would be to have it start emitting keypresses by itself in a loop with a delay between them and break out of that loop and terminate when something else like another keypress is detected.

You could get fancier and have the script keep running indefinitely, turning its behavior on and off, but you might run into trouble because multithreading works, but isn't used much and probably has bugs.

Here's a starting point:

```
while (true):
    retCode = keyboard.wait_for_keypress('d',modifiers=['<ctrl>'],timeOut=0.04)
    if retCode:
        break

    keyboard.send_keys("a")
````

This untested script should run indefinitely, emitting an "a" key every 40ms. When Ctrl+d is pressed, it will exit.
I have never used that API call, so I'm not sure if timeOut  takes a float.
I am not sure what it will do with keypresses other than Ctrl+d.
Try it and see. :)

While debugging this, you may find our [trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide) useful.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by brndd** [comment]
That script doesn't really do what was originally asked for. What's needed is a script like this (in pseudocode):

```
while holding key "a":
    send KeyDownEvent "a"    
    sleep 40ms
    send KeyUpEvent "a"
```

A script like this would ideally also "catch" the original keypress so it does not get handled by anything else. It would activate when you press and hold "a" and deactivate as soon as you release it.

It's possible to create script like this using AutoHotKey and eg. the Logitech Control Panel software on Windows, but I don't think this is currently possible with AutoKey (or any other off-the-shelf Linux/X11 tool for that matter).

**Comment by josephj11** [comment]
@brndd  Your pseudocode has a problem from AutoKey's perspective. AutoKey doesn't replace the keyboard, it works with it, so, it may be impossible to do this. If you are pressing a physical key, it's still going to be pressed while you do anything else. You could try separating the holding key (a) from the pressing key (b), but I suspect you and X11 would then see key a+b.

A way to workaround this (and add a whole other dimension of functionality) would be to insert a single card computer (possibly wirelessly) between the keyboard and the computer. Then, you can do almost anything because X11 (and AutoKey) only sees what you want it to see. All the hardware for this is available and some of the "drivers" exist (in other projects), but we haven't heard of anyone attempting it yet. Seems like a product some gamers would want to buy if it didn't impact keyboard latency much.

**Comment by brndd** [comment]
Yeah, it seems this would be possible using libevdev (it can apparently capture keystrokes like this, which would be necessary for this functionality), but I don't know what AutoKey is using under the hood.
