### ISSUE TITLE
Documentation to manage multiple monitor layout

### ISSUE THREAD

**Issue by fgarcia** [autokey/autokey#510]
NOTE: The issue template does not seem to serve well this issue (not related to a release). I hope it is OK to ignore it this time

## Problem

I have some scripts to manage the layout of apps in my monitor. Following the current documentation on the [API](https://github.com/autokey/autokey/wiki) I could create some scripts to manage the position and dimension of apps

However whenever I connect to an external monitor, the screen dimensions and scaling change, breaking my scripts. To solve that I would need to know the dimensions of the screen which is not mentioned on the wiki (currently just mentions how to get the window dimensions, not its screen). 

## Solution

Provide an example about getting the screen dimensions related to an app window

## Notes

- There can be multiple displays. I can query them with `xrandr --query` but that does not tell me in which one an app is rendered
- I think the Wiki is not a full list of API calls, just some code examples. Is there a link for the whole list? I think once I saw the native GTK (non python) docs

**Comment by josephj11** [comment]
Several pieces to this.
* Why do you need AutoKey for this? You can write scripts in your favorite language (I have some in bash) and trigger them from a terminal CLI or from a desktop or panel icon. If you're a rocket scientist (I'm not!), you can even trigger them using dbus events when hardware changes state (e.g. a monitor becomes active,) etc.

* AutoKey's claim to fame is being able to trigger actions based on keyboard inputs. Any advanced actions end up being Python 3 scripts that AutoKey invokes. So, you have to figure out how to get Python to do what you want and then, if it helps, AutoKey can invoke that Python code for you. Python has tons of special purpose modules you can use to add all sorts of functionality to it. You just have to find them and know enough Python to use them effectively. Of course, you can also use subprocess() to call out from Python to just about anything else that can run on your system.

If you need user interaction, you can also directly invoke a dialog manager such as Zenity, Kdialog, or yad. I'm a yad fan. (AutoKey uses Zenity (GTK) or Kdialog (Qt), depending on which front end you are using, but doesn't support all the available features/options.) 

This also means that when you're doing anything intricate, you can usually first write it as standalone Python code and run and debug it outside of AutoKey where you have full access to development tools such as IDEs and can add things like print() statements to see intermediate results. When doing this, you can usually replace calls to the AutoKey API with code that just returns fixed results that are good enough for testing. 

If you want to see what I have or discuss this aspect further, ask on our [support list](https://groups.google.com/forum/#!forum/autokey-users) and we'll probably take it to direct email since it's off topic for AutoKey itself.

* Look into using xdotool and wmctrl directly. They provide information about windows and some information about desktops.  xdotool is particularly powerful once you begin to understand how its command chaining works. As you string together arguments on its command line, they are executed left to right with the results of one step available to subsequent steps in a stack. The downside to this is that it tends to be a black box so when things don't work as expected it can be difficult to figure out why.

* Our API examples are great (and a welcomed recent addition to the project), but they are not complete. Please contribute more!
The documentation, such as it is, is [here](https://autokey.github.io/index.html). That's not complete either and is gradually getting outdated. It needs to be regenerated and one of our devs has looked into it, but it's not done yet. It also does not include our Xautomation API which is somewhat documented [here](https://github.com/autokey/autokey/blob/master/new_features.rst). This definitely needs improvement and I think work is being done on it in our develop branch which includes or will include an enhanced Xautomation API among other things.

* The issue template is just a guide. It makes it less likely that we have to ask a bunch of questions before beginning to address an actual issue. One size does not fit all.

**Comment by fgarcia** [comment]
I've just noticed how spoiled I am coming from the Windows equivalent app AutoHotKey. That was the only scripting source and reference I needed to automate desktop actions. Maybe I was greedy expecting AutoKey to do the same for me, but still, I am discovering a lot just by reading other issues around here. So I am using this project unofficially to learn how to automate more my desktop.

Well, even so I was not paying attention enough because the documentation link you sent me was exactly what I needed. That links appears in the first wiki page, but in the index, if I click the wiki titled "API" I am taken to a page with just examples. It was my fault thinking that was the most obvious place to find the actual API documentation. I saw it before but could not find it again. 

Am I too naive thinking it would be a great UX having that link commented out in every new python script?? If most users are like me, we would rarely write/review scripts to remember the API

That being said, with the API I could already position and resize windows. So I thought that was one goal / potential of the app. However I could not find how to retrieve the information about the workspace to be able to calculate the right dimensions/positions when using external monitors.

I saw some `wmctrl -l` and I've just found out that I needed a `wmctrl -d` along understanding that with external displays either the workspace gets extended or a new one is created.

Closing the issue since now I understand I can launch a subprocess call to wmctrl
