### ISSUE TITLE
Is there a way to press ALT + SPACEBAR with autokey ?

### ISSUE THREAD

**Issue by andrehtgti2** [autokey/autokey#522]
I tried to do

keyboard.send_keys("<alt>+<space>")

keyboard.send_keys("<alt>+<spacebar>")

but none works

There another way ?

**Comment by josephj11** [comment]
Try `keyboard.send_keys("<alt>+ ")`.

See our [wiki](https://github.com/autokey/autokey/wiki/Special-Keys).

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.
