### ISSUE TITLE
Running a script that creates dialog box with a hotkey will cause AutoKey to crash 

### ISSUE THREAD

**Issue by Raytle** [autokey/autokey#530]
## Classification:

Crash

## Reproducibility:

Very regularly (usually after running the script 1 or 2 or 3 times).

## Version

AutoKey version: **0.95.10**

Used GUI (Gtk, Qt, or both): **Gtk**

Installed via: (PPA, pip3, …). **Muon Package Manager**

Linux Distribution: **Lubuntu 20.04lts**

## Summary

If I run the following script with a hotkey (such as, for example, `Ctrl+Shift+Alt+9`) it will run a few times but then it will cause AutoKey to crash ...

```
import tkinter as tk

class Application(tk.Frame):
    def __init__(self, master=None):
        super().__init__(master)
        self.master = master
        self.pack()
        self.create_widgets()

    def create_widgets(self):
        self.hi_there = tk.Button(self)
        self.hi_there["text"] = "Hello World\n(click me)"
        self.hi_there["command"] = self.say_hi
        self.hi_there.pack(side="top")

        self.quit = tk.Button(self, text="QUIT", fg="red",
                              command=self.master.destroy)
        self.quit.pack(side="bottom")

    def say_hi(self):
        print("hi there, everyone!")

root = tk.Tk()
app = Application(master=root)
app.mainloop()

```

I have the same problem with...

`pyautogui.alert('This displays some text with an OK button.')`

**Comment by josephj11** [comment]
There might be some conflicts between tkinter and AutoKey. IDK.

There are several ways forward.

First, to address this directly, we will need a more complete [problem report](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide) including a trace.

Since that might not yield results any time soon (we have no lead developers to create new production releases), finding a workaround would probably be the most practical approach.

Some ideas:

Unless you need something only tkinter can do, try using our dialog APIs which are based on Zenity, They do a lot, but not everything that even Zenity can do.

If that's not sufficient, then use something like `subprocess()` to call out to the dialog manager of your choice as a separate process. If you do this, you can use any tool you like, even Qt or GTK directly and, maybe, tkinter will work if it's outside of AutoKey.

Various forms of subprocess invocation allow retrieval of results from stdout as well as the the exit code/status of the process, and since AutoKey scripts are native Python 3, you can interact with the rest of your system limited only by your imagination and programming skills.

I'm a fan of yad and have used `subprocess()` to call it successfully from within AutoKey.

You might also want to try our Qt front end. (Both front ends can be installed on the same system without  conflict.) Maybe the problem is specific to the GTK front end.

**Comment by Raytle** [comment]
> Since that might not yield results any time soon (we have no lead developers to create new production releases), finding a workaround would probably be the most practical approach.

Thanks for your help.

I actually found a workaround . And yes, unsurprisingly I used subprocess ( )

```
import subprocess 
subprocess.Popen(["/bin/bash", "/home/a_bash_script_that_opens_my_python_script"])
```

**Comment by josephj11** [comment]
Great. Since you know enough to use subprocess ... 
FYI
There's a bug in 0.95.10 which will throw an exception if you use the version of subprocess that returns the stdout results with a command that generates no output. This is already fixed in the devel branch.

**Comment by Raytle** [comment]
> Great. Since you know enough to use subprocess ...

I know enough to get myself into trouble.


> FYI
There's a bug in 0.95.10 which will throw an exception if you use the version of subprocess that returns the stdout results with a command that generates no output. This is already fixed in the devel branch.

Thanks for letting me know. I appreciate that.
