### ISSUE TITLE
How can I make one python script run another python script?

### ISSUE THREAD

**Issue by Raytle** [autokey/autokey#531]
### Classification:
Bug

### Reproducibility:
Always

### Version
AutoKey version: **0.95.10**
Used GUI: **Gtk**
Installed via: **Muon Package Manager**
Linux Distribution: **Lubuntu 20.04 LTS**

### Summary
In a nutshell: I want to cause one python script to run another python script.

### Verbose Explanation
Although I'm running Python 3.8.5 on Lubuntu 20.04 LTS [Get one python file to run another, using python 2.7.3 and Ubuntu 12.10](https://stackoverflow.com/a/20457045) works properly for me when I run `main.py` from a terminal. In other words, when I run `main.py` from a terminal, then the word "hello" is displayed in my terminal.

But when I try to run `main.py` with AutoKey the following error message. "The script 'main' encountered an error" pops up on my screen.

**Comment by josephj11** [comment]
IDK. But ...
Doesn't AutoKey already have  main() function/module? That might be a problem. Ask on Gitter.

Generally, there are three ways to run other Python scripts from within AutoKey.

1) Use them purely externally with subprocess()

2) *If* they don't include any AutoKey API calls, you can add them to your Modules directory as Python modules and then import them into your scripts

3) There's this AutoKey API run_script thing I don't understand.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by Raytle** [comment]
I found an answer that works for me at [What is the best way to call a script from another script?]( https://stackoverflow.com/a/58857320)

I like the following because it is very simple and works with AutoKey.

```
import runpy

runpy.run_path(path_name='script-01.py')
runpy.run_path(path_name='script-02.py')
runpy.run_path(path_name='script-03.py')
```
