### ISSUE TITLE
Esperanto letters are not shown

### ISSUE THREAD

**Issue by J-Metsis** [autokey/autokey#532]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Gtk 

If the problem is known to be present in more than one version, please list all of those.

Installed via: Package Manager Installation / [Debian and Derivatives ](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives)

Linux Distribution: Ubuntu 20.04.2 LTS 

## Summary

Using the so called x-system to convert letter combinations to diacritical Esperanto letters fails to produce the diacritical letter.

## Steps to Reproduce (if applicable)

- Create a Phrase with any name, the content "Ĉ" (between the parenthesis) and 
- Define the abbreviation "Cx" with settings "Remove typed abbreviation", "Match phrase case to typed abbreviation", "Trigger when typed as part of a word" and "Trigger immediately"

## Expected Results

The letter combination "Cx" should get replaced with "Ĉ".

## Actual Results

The letter combination "Cx" gets erased without being replaced.

## Notes

The Esperanto letters are listed on [Wikipedia](https://simple.wikipedia.org/wiki/Esperanto_alphabet).

**Comment by josephj11** [comment]
Welcome to AutoKey!

Have you tried selecting the Paste using clipboard (Ctrl-V) option for your phrases?

If that doesn't work, there are some more convoluted approaches for sending Unicode strings and using `<code>` macros.

Paste using keyboard is not very capable and probably can't be enhanced without fully replacing it with something else.

**Comment by J-Metsis** [comment]
Yes, I copied the letters from another source. I do not understand this. Those Esperanto letters are normal Unicode letters (e.g. Ĉ is U+0108), so why do not they appear? Is AutoKey not Unicode aware?

Pointers to a code-based solution appreciated.

**Comment by josephj11** [comment]
Our keyboard module does not do Unicode. Pasting should work.

Just to clarify, I'm not referring to where/how you got the Unicode code points. I'm referring to the options you selected when defining your phrase. When you select a phrase in the AutoKey Main window, it is displayed with options on the panels to the right. In the middle, there is the Paste using option (which currently defaults to keyboard). You need to change that to Clipboard (Ctrl+V). It's not clear from your response whether you did that or not.

If that doesn't fix it, then you can try using a `<code>` macro.  I couldn't immediately find an example of this. I will edit this post when I find one.

Also, read through issues #29 and #241. There are some scripting examples in the responses.

Adding to this as I find things:

Scripting example:

This one uses the numeric value of the code point. I don't understand why it needs the suffix.

```
char = "2014"
unikeys = "<ctrl>+<shift>+u"
ctrl = "<ctrl>"
keyboard.send_keys(unikeys + char + ctrl + " ")

```

This one uses the Unicode character directly and saves and restores the original contents of the clipboard.

```
OldClipboard=clipboard.get_clipboard()
clipboard.fill_clipboard("—")
keyboard.send_keys("<ctrl>+v")
time.sleep(0.2)
clipboard.fill_clipboard(OldClipboard)
```

**Comment by Elliria** [comment]
There's a bit of a trick to using Unicode characters in AutoKey scripts and phrases without first putting them onto the clipboard. The syntax varies slightly depending on whether you're printing one or more Unicode characters or interspersing the Unicode characters with single characters. Below are some examples.

### IN SCRIPTS:

### Important rules to keep in mind:
- You should use `keyboard.send_keys()` for these, because they're multi-byte characters.
- You cannot use `keyboard.send_key()` for these, because they're not technically single characters.
- This will only work on Unicode character-codes that contain **all digits and no letters**.
- This will display any Unicode character that has **only four digits in its Unicode character-code**.
- This will **not display the result in color** even if an actual character or emote is in color.
- If a Unicode character will be the **last or only character** you print, **an additional key-press is required to get rid of the tooltip**. In the examples, I inserted a space or a plus sign at the end of each string. Note that neither the space nor the plus sign will be printed, but are simply a way to communicate with AutoKey that you're done creating the character. If a space or plus sign is desired after the Unicode character, an additional space or plus sign must be inserted.
- You can insert as many Unicode characters as you like into a string that contains just Unicode characters. In that case, you have two choices: You can put a space or plus sign after each of the characters or just put one space or plus sign at the end of all of the characters.
- If you create a string that's a mixture of single characters and Unicode characters, each Unicode character must end with a space or plus sign.

### To print a single Unicode character:

Add a space after the Unicode character:

`keyboard.send_keys("<ctrl>+<shift>+u+0108 ")`

Or add a plus sign after the Unicode character:

`keyboard.send_keys("<ctrl>+<shift>+u+0108+")`

Result:

Ĉ

### To print several Unicode characters:

Add a space after the **last** Unicode character:

`keyboard.send_keys("<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+2742<ctrl>+<shift>+u+2663<ctrl>+<shift>+u+2740 ")`

Or add a plus sign after the **last** Unicode character:

`keyboard.send_keys("<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+2742<ctrl>+<shift>+u+2663<ctrl>+<shift>+u+2740+")`

Or add a space after **each** Unicode character:

`keyboard.send_keys("<ctrl>+<shift>+u+0108 <ctrl>+<shift>+u+2742 <ctrl>+<shift>+u+2663 <ctrl>+<shift>+u+2740 ")`

Or add a plus sign after **each** Unicode character:

`keyboard.send_keys("<ctrl>+<shift>+u+0108+<ctrl>+<shift>+u+2742+<ctrl>+<shift>+u+2663+<ctrl>+<shift>+u+2740+")`

Result:

Ĉ❂♣❀

### To print a mixture of single characters and Unicode characters:

Add a space after **each** Unicode character:

`keyboard.send_keys("foo<ctrl>+<shift>+u+0108 foo<ctrl>+<shift>+u+0108 foo")`

Or add a plus sign after **each** Unicode character:

`keyboard.send_keys("foo<ctrl>+<shift>+u+0108+foo<ctrl>+<shift>+u+0108+foo")`

Result:

fooĈfooĈfoo

### IN PHRASES:
You can use the key-combination that creates a Unicode character inside of a phrase and it will be converted to a Unicode character. No quotes are needed around it and spaces or plus signs should be used after the key-combinations.

### Important rules to keep in mind:
- You should use the key-combination that creates a Unicode character for these (a press of the Ctrl key, Shift key, u, and the Unicode character-code done by stringing them together with plus signs).
- This will only work on Unicode character-codes that contain **all digits and no letters**.
- This will display any Unicode character that has **only four digits in its Unicode character-code**.
- This will **not display the result in color** even if an actual character or emote is in color.
- If a Unicode character will be the **last or only character** you print, **an additional key-press is required to get rid of the tooltip**. In the examples, I inserted a space or a plus sign at the end of each string. Note that neither the space nor the plus sign will be printed, but are simply a way to communicate with AutoKey that you're done creating the character. If a space or plus sign is desired after the Unicode character, an additional space or plus sign must be inserted.
- You can insert as many Unicode characters as you like into a string that contains just Unicode characters. In that case, you have two choices: You can put a space or plus sign after each key-combination or just put one space or plus sign at the end of all of the key-combination.
- If you create a string that's a mixture of single characters and Unicode characters, each key-combination must end with a space or plus sign.

### To print a single Unicode character:

Add a space after the key-combination:

`<ctrl>+<shift>+u+0108 `

Or add a plus after the key-combination:

`<ctrl>+<shift>+u+0108+`

Result:

Ĉ

### To print several Unicode characters:

Add a space after the **last** key-combination:

`<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+0108 `

Or add a plus sign after the **last** key-combination:

`<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+0108<ctrl>+<shift>+u+0108+`

Result:

Ĉ❂♣❀

### To print a mixture of single characters and Unicode characters:

Add a space after **each** key-combination:

`foo<ctrl>+<shift>+u+0108 foo<ctrl>+<shift>+u+0108 foo`

Or add a plus sign after **each** key-combination:

`foo<ctrl>+<shift>+u+0108+foo<ctrl>+<shift>+u+0108+foo`

Result:

fooĈfooĈfoo

**Comment by josephj11** [comment]
Aren't your code points decimal, not hexadecimal?

One of us should make this a Wiki page. It looks pretty perfect as is.

**Comment by Elliria** [comment]
You're right that I had it wrong. I ended up going with **Unicode character-code** since the research I just did shows that you can create these in several ways.

I also edited the example a bit to make it more user-friendly and added a section that explains how to handle them when mixing single characters with Unicode characters, since that doesn't offer quite as much freedom as the other two ways of printing these characters.

**Comment by J-Metsis** [comment]
> Our keyboard module does not do Unicode. Pasting should work.
> 
> Just to clarify, I'm not referring to where/how you got the Unicode code points. I'm referring to the options you selected when defining your phrase. When you select a phrase in the AutoKey Main window, it is displayed with options on the panels to the right. In the middle, there is the Paste using option (which currently defaults to keyboard). You need to change that to Clipboard (Ctrl+V). It's not clear from your response whether you did that or not.

That worked. Initially I did not even pay attention to those options as I followed the principle "the default is good" and since I thought the basic functionality is to replace text. Then I took a look but thought that "clipboard" overwrites what I have on the clipboard, so I did not try. Now it turned that the alternative "clipboard" does not use the clipboard, at least does not overwrite its content, so I think it is a misnomer.

Anyway I seem to have achieved my goal: to write "Cx" anywhere (email, browser, text editor and so on) and have it replaced by "ĉ". Since this works I can forget AutoKey :-)

Thank you!

**Comment by josephj11** [comment]
@J-Metsis  In 0.96, the default for phrases will *finally* be changed to Paste using clipboard (ctrl+v). I've been lobbying for that for quite some time. We get tons of questions/issues about this.

Maybe you don't need AutoKey now, but it's kind of like the remote control on a TV. You don't actually need it, but once you get used to using it, you'll find it hard to imagine doing without it.

@Elliria Very nice piece of work. I'll look for it in the Wiki when you get a chance to put it there. It will get linked to a lot!

I think we can safely close this issue.

**Comment by J-Metsis** [comment]
> Maybe you don't need AutoKey now, but it's kind of like the remote control on a TV. You don't actually need it, but once you get used to using it, you'll find it hard to imagine doing without it.

I see that I expressed myself a bit unclearly. For a macro like this I want it just to work, so I do not actively need to think about it and I can concentrate on my writing. With your tips I was able to achieve that state, thank you. 

> I think we can safely close this issue.

Yes, please.
