### ISSUE TITLE
Unable to Set Abbreviation

### ISSUE THREAD

**Issue by happycoffeebean** [autokey/autokey#539]
## Classification:  

UI/Usability

## Reproducibility:  

Always

## Version:  

AutoKey version:  0.95.10

Used GUI (Gtk, Qt, or both):  GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).  Pop Shop, then apt-get install

Linux Distribution:  Pop_OS! 20.10

## Summary

Unable to set abbreviation

## Steps to Reproduce (if applicable)

- New / Phrase
- Type phrase
- In lower right, click "Set" for abbreviation

## Expected Results

- Abbreviation gets set for phrase
- 
## Actual Results

- The abbreviation goes away, the app tells me I must enter an abbreviation.
- 
If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Originally installed via Pop! Shop (Pop_OS) on a new build.  The abbreviation problem was noticed on first run.  Then I removed via terminal (apt-get remove) and reinstalled the same way.  There was no change in behavior.   

I've atached  a screen recording of the behavor.

https://user-images.githubusercontent.com/8798898/116445848-54354b80-a824-11eb-94f6-a41333600acc.mp4

**Comment by josephj11** [comment]
This is a UI/UX failure that I believe will be fixed in 0.96.

After you type a new abbreviation, you have to press Enter to make it stick, but there is nothing to indicate that you need to do that.

See if that fixes it for you.

**Comment by happycoffeebean** [comment]
You would think I'd have tried that!  That works, thank you!

**Comment by josephj11** [comment]
Well, it got you to say "Hi" to us, so it's not all bad. :)

Join us on our support forums whenever you have any other questions  or suggestions.

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.
