### ISSUE TITLE
Is there a way to quick set the abbreviation? 

### ISSUE THREAD

**Issue by woshichuanqilz** [autokey/autokey#54]
I get so many abbreviation to set in the autokey about 500. It is impossible for me to set them one by one, so I want to find some quick method to get it done.

**Comment by josephj11** [comment]
If you had defined them in AutoKey before, you could copy them to a new install.

If not, then you have to either do it manually or write a program/script to generate them.
If they are all just phrases and almost identical as far as the way they are configured, then scripting is not too bad. I'm not sure how "quick" it will be though unless you are a quick coder.

if you have that many of them, I would highly recommend first going into AutoKey and creating a new folder for them. Tell it to put the folder somewhere outside of AutoKey - e.g. $HOME/Autokey/Phrases.
That way, whatever you put there will be safe even if you uninstall and purge AutoKey later. It makes life easier.

Generate two phrases manually, one to use as a template and the second one to compare with the first one to see what is constant and what changes. Remember that each phrase is defined by two files:
some_name.txt and .some_name.json. You have to generate both files.
Once you see what has to be done, you can manually generate a text parameter file with several fields per record:
name:abbreviation:replacement text:anything else that changes.
You may also want to edit your template file to make the variable fields easy to find and change in a automated way e.g. [field_1] ... or [name] [shortcut] ... so you'll know what's going on when you come back to it after some time.
Your script would:
Read a record from the parameter file
Copy the two templates to name.txt  and .name.json (using name from the record you just read)
Edit name.txt and .name.json with something like sed to replace the variable fields in the templates with the values from the current record
Save the files in a temporary directory
Rinse and repeat.
Review everything and make sure it worked as desired.
Quit AutoKey.
Copy all the new files from your temporary directory to the new phrases directory you created in the first step.
Start AutoKey
Test your phrases
Post a copy of your scripts to our [support](https://groups.google.com/forum/#!forum/autokey-users) list so others can use them. Also tell us how you organized/manage the whole thing so you can actually have that many phrases and still be able to remember and use them.

This is probably easier than it sounds if you are somewhat fluent in  bash or another language.

If you decide to pursue this, and want to discuss it further, please do so on the support list so everyone can benefit from the effort and help with the solution.

Here, it's just me and sometimes one other person.

And, since you will be using AutoKey extensively (or it wouldn't be worth the effort to do all this), I would highly suggest that you consider switching from this (original) branch of AutoKey to the newer and improved [branch](https://github.com/guoci/autokey-py3). It has a few very useful new features, a bunch of bug fixes, and was converted to Python 3. In particular, if you are using any language other than English, Python 3 has greatly improved handling of multibyte character sets. The original branch of AutoKey (this one) has some difficulties with this.

**Comment by woshichuanqilz** [comment]
@josephj11  tnx a lot for your reply, I will try the autokey in py3 version
