### ISSUE TITLE
Update autokey-qt frontend to PyQt5

### ISSUE THREAD

**Issue by troxor** [autokey/autokey#56]
PyQt4 is being deprecated in some distributions (notably Archlinux).

**Comment by troxor** [comment]
Suspending work on this for now due to the quantity of changes and limitations on time. I also don't run Qt-based desktop environments. Pull requests are welcome.

**Comment by xuzhao9** [comment]
Hello @troxor  I am interested in porting the Qt app to Qt5.
However I found PyKDE5 is in pretty bad shape and is not usable.
Is it acceptable that I remove the PyKDE dependency and make it a pure Qt5 app?

**Comment by troxor** [comment]
Hi @xuzhao9, that would be awesome. I'm sure there are many users that would appreciate an updated Qt5 interface!

**Comment by supagu** [comment]
great, would love to see a qt5 interface so i can use this app!

**Comment by xuzhao9** [comment]
Hi guys, how's everything going? I have finished porting a simple but runnable autokey-qt5 interface without PyKDE dependency. However, I have to write a middle-layer to translate the PyKDE related code to the PyQt so it may lose some of the original features. The translation layer code is in lib/autokey/qt5ui/qt5helper.py under the repo root.

You guys can go to my [forked repo](https://github.com/xuzhao9/autokey) to give it a try. Just run the autokey-qt5 script!
Remaining TODOs:
- Use QIcon to replace KIcon (some of the KDE global icons may not reachable?)
- I didn't implement KXmlGuiWindow, so setAutoSaveSettings doesn't work for now. Not sure if other things doesn't workout though.


Here is a [screenshot](https://ibb.co/k0AY7G) of my port, please give my comments and feedbacks before I can submit a PR.

**Comment by troxor** [comment]
Thanks @xuzhao9 ! I think it looks good so far, but feedback from those who use the current autokey-qt would be valuable. We can replace anything Qt4/PyKDE-related with your port, and make it the only Qt interface if you agree that this would simplify things.

**Comment by xuzhao9** [comment]
@troxor Hello! I met a problem when porting the app. At the starting of the autokey-qt5, the following error message is printed:
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 666, sequence_number = 27, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 666, sequence_number = 28, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 666, sequence_number = 29, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 666, sequence_number = 30, major_opcode = 33, minor_opcode = 0

It seems that X_GrayKey request fails because the key is captured by some other client? Not familiar with xlib programming so I am not sure.
After some inspection, I found they are printed by the first line in  XRecordInterface.initialise() function:
 self.recordDisplay = display.Display()

Any ideas on how to resolve this error?

**Comment by troxor** [comment]
@xuzhao9 these BadAccess errors have been reported and seen a number of times in the past, but historically they haven't seemed to cause fatal errors. Unfortunately, the last time I looked into them, I didn't get very far. My xlib experience is fairly minimal as well.

**Comment by Lillian-Violet** [comment]
I would have posted this on @xuzhao9 's own github page, but there doesn't seem to be an issue tracker there so I'll try here. I've tried to run the pyqt5 application you made, but it keeps telling me there's no dbus.mainloop.pyqt5, do you have any idea what may be causing this? I have the pyqt5 and dbus library installed, and they seem to be working correctly, but this method is nowhere to be found.

This is what pycharm tells me:
[https://i.imgur.com/gI7SppM.png](https://i.imgur.com/gI7SppM.png)


This is the trace of what happens when I try to run the qt5 appilcation:
/home/jari/.virtualenvs/qt5app.py/bin/python /home/jari/autokey/autokey-qt5
Traceback (most recent call last):
  File "/home/jari/autokey/autokey-qt5", line 5, in <module>
    from autokey.qt5app import Application
  File "/home/jari/autokey/lib/autokey/qt5app.py", line 27, in <module>
    from dbus.mainloop.pyqt5 import DBusQtMainLoop
ModuleNotFoundError: No module named 'dbus.mainloop.pyqt5'

Process finished with exit code 1

**Comment by xuzhao9** [comment]
@GLaDTheresCake  My dbus pyqt5 module locates in "/usr/lib/python3.6/site-packages/dbus/mainloop/pyqt5.so". Please check if this so file is in your Python module search path.
If successful, you should be able to run "import dubs.mainloop.pyqt5" under Python REPL directly.
P.S. I have opened the issue page for my autokey repo.
