### ISSUE TITLE
How to swap super and alt keys

### ISSUE THREAD

**Issue by harshitazilen** [autokey/autokey#560]
Kindly guide me to swap super key with both the alt keys ( left alt and right alt keys ). 

Thanks for super useful tool.

**Comment by josephj11** [comment]
I believe what you want is `xmodmap` or `xkb` which are separate Linux utilities for remapping your keyboard.
Here are a bunch of useful links.

Here's a ton of stuff, courtesy of Sven, which relates to modifying the keyboard. I'd look at the xkb stuff first.

https://www.linux.com/learn/tutorials/769644-hacking-your-linux-keyboard-with-xkb
https://help.ubuntu.com/community/Custom%20keyboard%20layout%20definitions
https://wiki.archlinux.org/index.php/Keyboard_configuration_in_Xorg
https://wiki.archlinux.org/index.php/Xorg#Configuration
 
https://help.ubuntu.com/community/ComposeKey
http://en.wikipedia.org/wiki/Compose_key
http://fsymbols.com/keyboard/linux/compose/
https://cyberborean.wordpress.com/2008/01/06/compose-key-magic/

Once you figure out how to do what you want outside of AutoKey, you can call out to that script/utility from within an AutoKey script using the subprocess module if you want to change your layout on the fly by pressing a hotkey, etc.

If you do that, you may have to experiment with the exact sequence of events/timing required, because I'm not sure when or how fast such modifications take effect.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.
