### ISSUE TITLE
autokey-gtk doesn't start

### ISSUE THREAD

**Issue by mdeberts** [autokey/autokey#561]
## Classification:

Crash/Hang/Data Loss

## Reproducibility:

Always

## Version

AutoKey version: 
0.95.10-1_all

Used GUI (Gtk): 

Installed via: (sudo apt install autokey-gtk).

Linux Distribution:
Ubuntu 20.04 LTS
## Summary

If I run autokey-gtk in my terminal it will just freeze and do nothing.

## Steps to Reproduce (if applicable)

enter autokey-gtk in terminal
freeze

## Expected Results

 autokey-gtk should open

## Actual Results

freeze

debug verbose:
https://justpaste.it/3ig0x

**Comment by josephj11** [comment]
This should definitely work. We'd have lots of reports if it didn't, so the most likely scenario is that something local to your system isn't right.

AutoKey does start and is running or there would be no trace output. There is nothing visible in the trace that indicates that AutoKey has stopped working. That doesn't prove anything, but it's a bit odd.

The trace looks pretty strange. It looks like you're typing quite a bit, but I can't tell if any of it is actually doing any work in your terminal. AutoKey is not complaining about anything. It appears to be mostly just passing keystroke events to your application as it should. Try to do the minimum to recreate your issue.

One thing that looks particularly weird is that it says:

    2021-06-17 12:46:28,754 DEBUG - service - Undoing last phrase expansion requested. Can undo last expansion: 
    False

after you pressed backspace, but I don't see any phrase being activated prior to that.

I just very briefly tried AutoKey in gnome-terminal in kubuntu 18.04 and it appears to work fine.

Can you try AutoKey anywhere else - like in a text editor window?

Since you knew enough to run a trace, I assume that you have been using AutoKey for some time. When did it last work for you and what have you changed since then?

Would it be possible to try running autokey-qt so we can see if the problem relates to the GTK front end or to AutoKey's common core? You can have both front ends installed with no conflicts in Ubuntu.

If you don't have any other Qt apps installed, installing the Qt front end will bring in a bunch of dependencies, but they should be installed as automatic and if you later uninstall autokey-qt, apt should tell you it can delete (autoremove) them for you.

From your window title, it looks like you're running as a normal user - good, because AutoKey is not designed to be run as root.

Let's see if any of your answers to the above questions give us any clues as to what the issue is.

**Comment by josephj11** [comment]
One more thought. When AutoKey starts, it normally starts in the background without displaying its main window. If you want its main menu to display, you can either start it by running `autokey-gtk -c` or by right clicking on the AutoKey panel icon (after it is running) and selecting Show Main window. Maybe everything is fine, but you just can't see it because no menu has appeared.

**Comment by mdeberts** [comment]
Ok thx sorry was as simple as autokey-gtk -c to get the window I was expecting.
Sorry and thx for the help
