### ISSUE TITLE
Regex hotkeys

### ISSUE THREAD

**Issue by aleksy** [autokey/autokey#570]
## Classification: Feature (New)

We would like to use regex as hotkeys.
Its use will enable the autokey to be used as text substitution program.

**Comment by josephj11** [comment]
What you're asking for doesn't make any sense to me. Please elaborate to explain it a bit more.

However, AutoKey already offers phrases which are a very powerful tool for text substitution. The target text becomes the trigger abbreviation for the new phrase. The substitution text is usually constant text, but it is possible to embed one or more AutoKey [macros](https://github.com/autokey/autokey/wiki/Dynamic-Phrases,-Using-Macros-as-placeholders-in-Phrases) in that text to make it arbitrarily more flexible/complex.

You can assign more than one trigger abbreviation to one phrase, but if you need the target to be generic, one way to do that would be to select the target with your keyboard or mouse before launching a script with a hotkey. Then, in the script, copy the selection into the clipboard and then assign the contents of the clipboard to a Python variable.

Once the target string is in a Python variable, you can apply the full power of Python to manipulating it - including the strings and regex modules. When you have the desired result, you load it back into the clipboard and paste it back into your application. A slight enhancement of this would be to first save the current contents of the clipboard and when you're done, restore it to the clipboard.

If you want to accomplish larger changes, you can use the exact same approach as above but start by selecting a larger block of text instead of just a word or a few characters.

If you would like to explore these options or any other usage questions, please join our support list and ask there.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by BlueDrink9** [comment]
Closed due to vague question and no follow-up activity

**Comment by BlueDrink9** [comment]
@josephj11 Brilliant response/answer, but be careful not to spend all your time and energy on [help vampires](https://slash7.com/2006/12/22/vampires/)
