### ISSUE TITLE
Running freshly-installed autokey fails with the error "Namespace AppIndicator3 not available"

### ISSUE THREAD

**Issue by tt-cclear** [autokey/autokey#577]
## Classification:

Bug

## Reproducibility:

I Didn't Try

## Version

AutoKey version: 0.96.0-beta.2

Used GUI (Gtk, Qt, or both):  GTK

Installed via: Source

Linux Distribution: Kali Linux

## Summary

Running freshly-installed autokey fails with the error "Namespace AppIndicator3 not available"

## Steps to Reproduce

- Download the source .zip and extract
- Run 
```
dpkg-buildpackage -us -uc
cd ../
sudo dpkg --install autokey-gtk_<version>.deb autokey-common_<version>.deb
sudo apt-get install -f
autokey-gtk // just 'autokey' yields the same result
```

## Expected Results

- AutoKey GUI opens

## Actual Results

- AutoKey crashed with the error message:
`Namespace AppIndicator3 not available`

## Notes

Googling the namespace error leads me to [this result](https://stackoverflow.com/questions/58409989/how-can-i-find-out-which-dependency-is-missing-for-a-pip-package) and issue #129. Both seems to show that the error is caused by the package `gir1.2-appindicator3-0.1` being not installed - this package is described as "Typelib files for `libappindicator3-1`". 

`libappindicator3-1` itself has been [deprecated](https://github.com/jgraph/drawio-desktop/issues/504) and removed from the Debian repositories (and, consequently, also removed from Kali Linux repositories since the distro is Debian-based), and replaced with the package `libayatana-appindicator3`. So `sudo apt-get install gir1.2-appindicator3-0.1` won't work.

AutoKey, according to [this](https://bugs.debian.org/956762), has already switched to `libayatana-appindicator3` at version 0.95.10 - yet the error somehow persists on 0.96.beta2. But I specifically want to install the beta version for the sake of the new mouse functionality...

Somewhat stumped at this point, maybe I'm missing something?

Things I've tried:
- Ran `sudo apt-get update`
- Attempted to `sudo apt-get install gir1.2-appindicator3-0.1` (which failed since the package isn't in the repository anymore)
- Verified that `libayatana-appindicator` is installed.
- Verified that the equivalent of `gir1.2-appindicator3-0.1` for `libayatana` (`gir1.2-ayatanaappindicator3-0.1`) has already been installed and is already the latest version according to apt.

**Comment by tt-cclear** [comment]
My bad. Just realized that I've got my installation method mixed up - apparently I cloned the repository with Git instead of using the release .zip file, stupidly assuming that the repo will contain the source code of that release (which, I now realized, is beta and released on May, while the master branch is last updated on January). I apologize for the confusion, and will close this now. I'll try again with the release .zip file soon.

**Comment by tt-cclear** [comment]
Hi, just reinstalled AutoKey via `pip install https://github.com/autokey/autokey/archive/v0.96.0-beta.5.zip` following issue #578 and getting the same error message as above again.

Full error message (I forgot to add it in before):

```
kali@kali:~$ cd .local/bin
kali@kali:~/.local/bin$ ./autokey-gtk --verbose
Traceback (most recent call last):
  File "/home/kali/.local/bin/./autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/kali/.local/lib/python3.9/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/kali/.local/lib/python3.9/site-packages/autokey/gtkapp.py", line 40, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/home/kali/.local/lib/python3.9/site-packages/autokey/gtkui/notifier.py", line 26, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

Any help would really be appreciated.

**EDIT:** Just found this [patch](https://salsa.debian.org/python-team/packages/autokey/-/commit/67b72e9f398be28e8963e6ec641f4f801fd2650d) to `/lib/autokey/gtkui/notifier.py` that's supposed to do the switch. The `notifier.py` file on my `python3.9/site-packages/autokey` apparently hasn't had this patch applied to it - still shows the old version before the patch. There's only one file involved in the patch so I'd try patching it up myself and post again here

**EDIT2:**Just patched up the file. I don't get the Namespace error in this issue anymore - but am still getting the error in issue #578.

**Comment by BlueDrink9** [comment]
Thank you for finding that patch! Frustratingly, it seems that patch never got submitted, or at least not merged, upstream (i.e. to this repo). I will fix that now and get it merged into develop, assuming that non-ubuntu repos have also switched to anataya

**Comment by tt-cclear** [comment]
Sounds good, thanks for your concern!

**Comment by DevMehta** [comment]
installed via: pip3 install autokey
version: autokey==0.96.0

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkui/notifier.py", line 29, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkapp.py", line 40, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkui/notifier.py", line 31, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

after running sudo apt-get install gir1.2-appindicator3-0.1 that issue was resolve but now i got a new issue

Traceback (most recent call last):
  File "/home/user/.local/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkapp.py", line 42, in <module>
    from autokey.gtkui.configwindow import ConfigWindow
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkui/configwindow.py", line 32, in <module>
    require_version('GtkSource', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 3.0

In Ubuntu 20.04, the installed version is by default 4

tried to change require_version('GtkSource', '4.0') in the file /home/user/.local/lib/python3.10/site-packages/autokey/gtkui/configwindow.py
and got:
Traceback (most recent call last):
  File "/home/user/.local/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkapp.py", line 42, in <module>
    from autokey.gtkui.configwindow import ConfigWindow
  File "/home/user/.local/lib/python3.10/site-packages/autokey/gtkui/configwindow.py", line 32, in <module>
    require_version('GtkSource', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 4.0

also tried: sudo apt-get install -y libwebkit2gtk-4.0-dev
but the issue persist.

please help.

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @DevMehta !!

I don't think pip installs our dependencies.

Not sure what your ultimate goal/configuration is, but since you have apt you should remove AutoKey or move all the files out of the way and then install from debs. That should handle all your dependencies... After that, if you need to use pip in a VM, etc. you'll have a working system to refer to.

[debs](github.com/autokey/autokey/releases/)  [instructions](https://github.com/autokey/autokey/wiki/Installing)

**Comment by Devesh-Mehta** [comment]
> Welcome to the AutoKey community, @DevMehta !!
> 
> I don't think pip installs our dependencies.
> 
> Not sure what your ultimate goal/configuration is, but since you have apt you should remove AutoKey or move all the files out of the way and then install from debs. That should handle all your dependencies... After that, if you need to use pip in a VM, etc. you'll have a working system to refer to.
> 
> [debs](github.com/autokey/autokey/releases/) [instructions](https://github.com/autokey/autokey/wiki/Installing)

Thanks a lot, it did work for me
