### ISSUE TITLE
When you clone something, the original is still highlighted instead of the clone

### ISSUE THREAD

**Issue by KeronCyst** [autokey/autokey#585]
## Classification:

UI/Usability

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): GTK

Installed via: Mint's Software Manager

Linux Distribution: Mint Cinnamon

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

1. Right-click on a phrase or script in the left sidebar
2. Click "Clone Item"

## Expected Results

The clone should be instantly highlighted to start doing stuff to

## Actual Results

The original remains highlighted

## Notes

Sorry I suck at programming or else I'd try to help!

**Comment by bjohas** [comment]
+1 from me!

**Comment by nevarek** [comment]
I made a pull request: #604

~~However, there's a runtime issue with cloning an item that I recommend handling. I don't see an open issue with it, but a cloned object should be renamed so that it does not overwrite the original object (because it has the same name). The bug arises because each "page" uses a text buffer to identify items.~~

~~The simplest solution would be to increment the file's name with a number (as convention with other applications) immediately after this line: https://github.com/autokey/autokey/blob/develop/lib/autokey/gtkui/configwindow.py#L1194~~

~~I could open a second PR to fix the issue or I can include it in my current PR. Please advise.~~

**Comment by sebastiansam55** [comment]
It already does this on the back end/file system portion tho no? When I clone an item the newer item has the same name in the autokey window but has a 1 appended to the end of the file names;
![Screenshot from 2021-08-31 08-05-55](https://user-images.githubusercontent.com/1707320/131499567-969b27c8-3295-410b-a29b-e74b49ecce17.png)

**Comment by nevarek** [comment]
Aha, the other part needs to be updated as well

**Comment by nevarek** [comment]
I've updated the commit to include the config window to update its selected item, so the new cloned item is the one you are editing.
