### ISSUE TITLE
Error in X event loop thread

### ISSUE THREAD

**Issue by rssw** [autokey/autokey#591]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Gtk

If the problem is known to be present in more than one version, please list all of those.

PPA

Linux Distribution: Ubuntu 21.04

## Summary
Just updated to Ubuntu 21.04 from 20.10. None of the configured macros work anymore.

## Steps to Reproduce (if applicable)

Press the key combination to run a simple send-keys() line

## Expected Results

Keys should be sent

## Actual Results

 Any macro triggered generates this:

```
ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 242, in __eventLoop
    method(*args)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 674, in __grab_keyboard
    focus.grab_keyboard(True, X.GrabModeAsync, X.GrabModeAsync, X.CurrentTime)
AttributeError: 'int' object has no attribute 'grab_keyboard'
2021-08-03 11:48:57,828 DEBUG - interface - Sending string: 'YTAxYTBkNDQ5MTRlZThlMDY4MTRmZmIz'
2021-08-03 11:48:57,829 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 242, in __eventLoop
    method(*args)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 701, in __sendString
    self.__checkWorkaroundNeeded()
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1000, in __checkWorkaroundNeeded
    window_info = self.get_window_info(focus)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
AttributeError: 'int' object has no attribute 'get_property'
```
## Notes

n/a

**Comment by bjohas** [comment]
I wonder whether this is because Ubuntu 21.04 now uses Wayland rather than X11?  According to  https://github.com/autokey/autokey/issues/87 this might mean that autokey only works on certain windows.

(https://medium.com/@bugaevc/how-to-easily-determine-if-an-app-runs-on-xwayland-or-on-wayland-natively-8191b506ab9a https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277, https://itectec.com/ubuntu/ubuntu-xorg-applications-not-working-on-wayland-after-update-to-ubuntu-20-10/)

I'm on Ubuntu 20.04 LTS and haven't upgraded because I don't want to be an early adopter of Wayland :) I have nothing against it as such, but I'm wary of the reported issues, esp. with productivity tools like autokey...

**Comment by rssw** [comment]
Yes, that could definitely be.  I would love to know what the fix is, though.

**Comment by bjohas** [comment]
I would love to know that too - unfortunately I have now idea whether there is one 🤷

**Comment by josephj11** [comment]
Looks like (maybe) the window module (upstream of AutoKey) doesn't have a get_propery function() in it. If this worked before (as I'm sure it must have), then it's one of two possible problems.

* There's a new version of the window module that we have to figure out how to adapt to
* You are using Wayland instead of native X11

If it's the latter, you should try to configure Ubuntu to use native X11 - at least on the user account you want to use with AutoKey.

Last we looked (quite some time ago), Wayland's code to emulate X11 for X11 apps such as AutoKey was lacking some features that AutoKey requires. There was some thought that Wayland's security design might be incompatible with AutoKey's requirements, but we don't have any devs who are sufficiently versed in Wayland to be sure.

**Comment by josephj11** [comment]
As a workaround, see if you have any better luck with autokey-qt (if it works at all). Both front ends can be installed at the same time with no issues (as long as you're not using Arch or an Arch derivative such as Manjaro).

Installing autokey-qt will add a bunch of dependencies if you don't have any other Qt apps that already required them. However, they will be installed by apt as "automatic", so if you later uninstall autokey-qt, any dependencies it added will show up as no longer needed and you can tell apt to autoremove them.

We have another similar new issue with autokey-qt and newer distros. We'll have to research both of these to find a way forward.

**Comment by rssw** [comment]
Yip, it's Wayland.  Looks like I'm screwed.  If anyone can recommend an alternative to send-keys() under Wayland, or let me know if autokey ever manages to find a way to work with it, please post here.

I may just look into reverting back to X11...

**Comment by rssw** [comment]
Figured out how to revert to Xorg.  Autokey 1 : Wayland 0
