### ISSUE TITLE
python3-xlib not found

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#60]
Hi, after the most recent update 0.93.8-1 (from 0.93.7-1), autokey-gtk will no longer run.  This is under Linux Mint 18.1/Ubuntu 16.04.  Source is ppa:troxor/autokey 

Autokey is a tremendous resource.  Thank you for any help.

 Traceback follows:

Traceback (most recent call last):
  File "/usr/bin/autokey", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python3-xlib' distribution was not found and is required by autokey

**Comment by troxor** [comment]
That was fast! Yeah, I think reintroducing install_requires= to setuptools messed up the dependencies on the package. I'm looking into it.

**Comment by ghost** [comment]
Thank you!  I'm not experienced with Python beyond basic autokey scripting.  Trying to recompile the previous version caused errors on my system related to /usr/local/lib/python2.7/dist-packages/.  For now I'll have to wait for the PPA package...

**Comment by troxor** [comment]
A new package has been pushed to the PPA that should fix this. Sorry for the regression! A second PPA (ppa:troxor/autokey-testing) has been created with the aim of keeping the main one stable.

**Comment by ghost** [comment]
Thanks for the quick response.  Autokey 0.93.7 installed from the ppa and is running under Linux Mint 18.1.

When running from the terminal it is throwing an error, below.  However, it seems to have no impact on functioning.

Autokey (now autokey-py3) is one of the first utilities I install on a new computer.  Thanks again.   -Alec
 
~ $ autokey-gtk

(autokey-gtk:6682): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7fe447bf3e48>, b'\x00\x03H\x03\x03\x00\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7fe447bf3e48>, b'\x00\x03I\x03\x03\x00\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')

**Comment by godlike64** [comment]
Hello,

Sorry for reviving this, but I am having this issue with the latest ebuild (also with the ebuild modified for tarballs later than 0.93.7). I do have python-xlib installed, via portage:

$ eix python-xlib
[I] dev-python/python-xlib
     Available versions:  0.15_rc1-r2 (~)0.19 {doc PYTHON_TARGETS="pypy python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  0.19(06:23:08 PM 01/16/2018)(-doc PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6 -pypy")
     Homepage:            https://github.com/python-xlib/python-xlib
     Description:         A fully functional X client library for Python, written in Python


However, the way it's listed in setup.py:

$ grep install_requires setup.py 
    install_requires=['dbus-python', 'pyinotify', 'python3-xlib'],

in Gentoo, it makes it so that the python3-xlib dependency will be checked at runtime, via pkg_resources. More info on how this works here:

https://wiki.gentoo.org/wiki/Project:Python/Dependencies#Reading_setuptools_setup.py_files

Furthermore, it appears the proper package name is python-xlib:

$ pip search python-xlib|grep xlib
python-xlib (0.21)                                       - Python X Library
python3-xlib (0.15)                                      - Python3 X Library
xlib (0.21)                                              - Python X Library

https://pypi.python.org/pypi/python-xlib

Are there any plans to change this in setup.py? Once this is done, I can make some corrections to the ebuild and probably even do a -9999 one (to fetch the latest code from the current master branch here).
