### ISSUE TITLE
please add mouse.press_button release_button and set_location

### ISSUE THREAD

**Issue by MrOtto47** [autokey/autokey#622]
suggestion for mouse button up and down functionality without referencing a location (uses current location). and also set location without a button event.

(i am using a trackpad and would like to be able to simulate holding the middle button down while moving the cursor).

Thanks,

**Comment by boredofnames** [comment]
Hey, I needed this feature too, so I was going to attempt to code it. 
However, it seems it's already in the [code](https://github.com/autokey/autokey/blob/master/lib/autokey/scripting/mouse.py), just not documented. 

Tested with 
```
import time
mouse.press_button(1)
time.sleep(5)
mouse.release_button(1)
```

and it works 😄

Edit: 
There's move_mouse as well, but seems buggy on qt. 

Edit 2: 
Apologies, I meant move_cursor

**Comment by josephj11** [comment]
@boredofnames Thanks for pointing this out.

The new improved documentation lives [here](http://autokey.github.io/autokey/api/mouse.html). It is automatically generated from the code, so it includes these calls.

If you'd like to provide more information on problems with mouse_move, feel free to open an issue about it.
I believe these calls were added in 0.96.0, so they are new and may have some rough edges.

FYI: The time module is exposed by default, so you don't need to import it.

If you have Python skills, we would very much appreciate any contributions to the code that you may want to implement. We are very low on developer resources. You can join us over on [Gitter](https://gitter.im/autokey/autokey) if you want to discuss things or get feedback/assistance.

@BlueDrink9 Can this issue be closed?

**Comment by boredofnames** [comment]
@josephj11 Thanks for the tips. At risk of going off topic here, in that case the README seems to be missing a link to that documentation. Also the examples in qt ui show time being imported, so I was following suit. I could create a PR for these minor issues if you'd like.

**Comment by josephj11** [comment]
@boredofnames Technical stuff such as PRs is @BlueDrink9 's domain, but cleanup of our code/documentation is always a good thing and something simple like that is a great way to get acclimated to our development process.

However, discussions like this work much better on [Gitter](https://gitter.im/autokey/autokey) rather than being lost in an unrelated issue. And, for anything more general, there are more participants over there who can chime in. If needed, you can also have private chats on Gitter to go over details that the rest of the community may not need to see or that are sensitive in any way.
