### ISSUE TITLE
Autokey fails to launch since recent update of Manjaro.

### ISSUE THREAD

**Issue by Git-Forked** [autokey/autokey#649]
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 33, in <module>
    sys.exit(load_entry_point('autokey==0.95.10', 'console_scripts', 'autokey-gtk')())
  File "/usr/bin/autokey-gtk", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for autokey

**Comment by josephj11** [comment]
It would help if you filled out our new issue questionnaire, so we know more about your installation.

What can you tell us about what changed since AutoKey last worked for you?

I don't know anything about the intricacies of the Arch/Manjaro packaging system and dependency handling, but this looks like an error outside of AutoKey itself.

This is the first time I have seen a reference to Python 3.10, but I don't know if that makes a difference.

We have a number of Arch/Manjaro users and someone built packages for aur, so perhaps you should first ask on a support forum for your distribution.

Our lead developer, @BlueDrink9  runs Arch, so maybe he will have something to say.

**Comment by BlueDrink9** [comment]
Reproduced on my arch. Seems to be a python 10 issue

**Comment by BlueDrink9** [comment]
Instructions [here](https://forum.manjaro.org/t/no-package-metadata-was-found-for-powerline-shell/97178/2) suggest we should re-build any python packages we haven't installed through pacman. In other words, uninstall and reinstall autokey and dependencies if done through pip or aur?
`yay -S $(pacman -Qoq /usr/lib/python3.9) --answerclean All` should do aur packages apparently.

**Comment by BlueDrink9** [comment]
Reinstalling autokey fixes this for me.

**Comment by Git-Forked** [comment]
> Reinstalling autokey fixes this for me.

Uninstalling and reinstalling autokey from AUR did in fact solve the issue.
Thanks for the suggestion BlueDrink9.
