### ISSUE TITLE
Update man pages

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#682]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

UI/Usability

### Which Linux distribution did you use?

N/A

### Which AutoKey version did you use?

0.96.0 Beta 10

### Can you briefly describe the issue?

Man file does not list `--version` option.

Not sure if anything else is needed.

### Anything else?

Add --version option.

Check if anything else has changed.

**Comment by Elliria** [comment]
We have three man pages in the [/autokey/doc/man](https://github.com/autokey/autokey/tree/develop/doc/man) directory. From what I can see, this is what's needed, but I'd love some feedback:

1. Correct the punctuation.
2. Correct the spelling.
3. Make the author reference identical in all three files.
4. Change **configuration window** to **main window** to make it obvious what will happen and since that's what that window is called in all other documentation.
5. Add missing single-character command-line switch to the **--help** switch.
6. Add these new command-line switches with these definitions to the **OPTIONS** section:
   * [--cutelog-integration](https://github.com/autokey/autokey/blob/master/lib/autokey/argument_parser.py#L57-L62)
     * Connect to a locally-running **cutelog** instance with default settings to display the full program log. See the **cutelog** GitHub page at [https://github.com/busimus/cutelog](https://github.com/busimus/cutelog) for more information.
   * [-m, --mouse](https://github.com/autokey/autokey/blob/develop/lib/autokey/argument_parser.py#L63-L68)
     * Enable verbose (debug) logging and include mouse-button events.
   * [-V, --version](https://github.com/autokey/autokey/blob/develop/lib/autokey/argument_parser.py#L52-L56)
     * Print the current AutoKey version to standard output and then exit.
7. Alphabetize the **OPTIONS** section.
8. Update the date.

*Note that I don't see anything else in [the list of what's new in AutoKey 0.96.0](https://github.com/autokey/autokey/releases/tag/v0.96.0) that belongs in a man page. The rest will go nicely into the [new_features.rst](https://github.com/autokey/autokey/blob/develop/new_features.rst) file, which will also be getting an update. I did, however, find some more goodies not mentioned there when I looked through the [argument_parser.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/argument_parser.py) file, so those have been added above.*

**Comment by Elliria** [comment]
Oh, and I forgot to add: @josephj11, can you please change the name of this issue to **Update man pages**? I almost didn't find it, because I was searching for **man pages** and **man page**. It wasn't until it occurred to me to try just part of it that I found my way here.

**Comment by josephj11** [comment]
> 4\. Add the new `--version` command line switch with this definition: "**Print the current AutoKey version as standard output and then exit.**"

It's a tiny nit, but I would say "to standard output" instead of "as standard output". Not worth fixing unless it's part of other changes as the meaning is still clear.

I just ran a `man autokey` from my CLI (I have the Qt version active).

I am unclear as to why the man page talks about Qt (or GTK if the other version does that). Also there are a few extra spaces in the text between some words.

These things are inconsequential, but if you're already in there ...

**Comment by Elliria** [comment]
I'll change **as** to **to**.

When you run `man autokey` in a terminal window, it should detect whether you're using QT or GTK and show you the appropriate man page. The reason for the difference is in the **NAME** section at the top of the page that references either **KDE and QT** or **GNOME and GTK**.

If you check [the man page source files](https://github.com/autokey/autokey/tree/develop/doc/man) in the /doc/man directory and do a search for two consecutive spaces, the only ones you'll find are used for strategically positioning some of the text, but there are no accidental double spaces anywhere within the text. I did a `man autokey` here and I see what you're talking about, but that odd spacing (and the insertion of dashes to split words) is being done by the man command and isn't hard-coded into the file, so I don't think we have any control over it.

No worries about how trivial any correction might be. These files haven't been edited in years and we're trying to do them up right, so anything goes.

**Comment by Elliria** [comment]
Thank you for renaming this issue.

**Comment by Elliria** [comment]
I found some more goodies by looking through the [argument_parser.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/argument_parser.py) file, so I'm adding those as well. See the updated list above.

**Comment by Elliria** [comment]
While looking these over, I couldn't help but notice that the single-character command-line switch that's used to display [the AutoKey version](https://github.com/autokey/autokey/blob/develop/lib/autokey/argument_parser.py#L52-L56) requires an **upper-case** **V** instead of a lower-case **v**. That's different from the other command-line switches and seems to be counter-intuitive (at least for me). It would also be an easy fix that I could do. Should I open an issue for that and ask for feedback to find out if anyone would object to that being done?

**Comment by Elliria** [comment]
This can be closed, @josephj11. I'll start a new issue for the command-line switches that we discussed in Discussion #840 and make that change.
