### ISSUE TITLE
Revoked.

### ISSUE THREAD

**Issue by Git-Forked** [autokey/autokey#694]

**Comment by josephj11** [comment]
While having this as a global option is a valid request, doing it now on a per script basis is pretty easy in most cases.

Use semaphores.

Code the original script to set an AutoKey global variable to some value which represents "keep running" when it starts. Retrieve this variable in your loop and if its value is not "keep running", break the loop. Code a second script (triggered by a different hotkey) that sets that AutoKey global variable to some other value and then exits. See this [example](https://github.com/autokey/autokey/wiki/Contributed-Scripts-2#toggle-a-looped-script) for one way to do this.

There are many variations on this theme. If you are careful, you might be able to do it all in one script with a single hotkey. The trick is making sure it works correctly the first time when the global variable (or the per script AutoKey local saved variable) has not been defined yet and on a subsequent invocation you are able to test the variable before setting it to true.

You could also use something else as a semaphore such as a value stored in an external file (or just the existence of a file) or some condition that you can test in your operating system environment, but those are a bit more work.

If your script is doing something that runs a "long" time per iteration or doesn't loop, then the above approaches won't work. In that case, if you share the specific details of what it needs to do (on [Gitter](https://gitter.im/autokey/autokey)), maybe we can come up with  other options.

This last case illustrates why it would be problematical to implement such a feature within AutoKey itself. Given that our scripts are written in full Python and can do almost anything, it would be impossible to guarantee that whatever we did to stop the script would actually work and would not have (possibly unintended) external consequences.

If you, as an intelligent user, consider all such conditions and consequences on a per script basis, such issues can be anticipated and avoided.

**Comment by Git-Forked** [comment]
I still think the feature request I suggested would be beneficial to my self as well as others, if it is possible it could be implemented.  Thank you for reading my request, and I hope it will be considered.

**Comment by Elliria** [comment]
AutoKey gives you the power to write any script that you can ever possibly dream up, limited only by your ability to code. As a result, it wouldn't know what your scripts could or would do or how far-reaching or serious their effects could be so that it could gauge how to smoothly and safely stop them.

A complex "dead man's switch" could be tied to a default global variable with two values, like "on" and "off" and a default starting value of "off". If the switch was enabled, each press of the hotkey would change the global variable's value. If it was "off" when the hotkey was pressed, it would change the value to "on". If it was "on" when the hotkey was pressed, it would change the value to "off" and kill the AutoKey process and any/all child processes that it had spawned.

Such a thing could be problematic. It would stop any other scripts that AutoKey might currently be running. As Joe pointed out, if an AutoKey script is in the process of doing something lengthy and/or complex, it may not be possible to instantly halt it or harm might be done if it's halted and leaves files/folders/settings, etc. in an incomplete or partially-altered state. The dead man's switch would have to recognize that for any or all scripts that it's about to kill and to know which additional steps it needs to take to help each script to recover safely from the interruption or to restore whatever they were in the process of altering. Last, but not least, you'd need to (remember to) relaunch AutoKey after the switch was triggered.

The scope of what may be encountered and have to be dealt with is pretty well beyond imagining and seems like it would be a daunting prospect for anyone to try to code.

An alternative would be a simple hard-core dead man's switch that just does the killing without concerning itself with what any script it kills might be busy with. The only cautionary action such a switch would take would happen when it's enabled and that would be a huge annoying "Are you sure?" pop-up followed by another huge annoying "Are you absolutely sure?" pop-up to give the user one final chance to back out.

It's an intriguing idea, though.

**Comment by Git-Forked** [comment]
> AutoKey gives you the power to write any script that you can ever possibly dream up, limited only by your ability to code. 

Actually it does not.  Sometimes even simple things do not work in AutoKey, for example, a print() statement.

**Comment by Git-Forked** [comment]
AutoKey does not need to know anything about the script for this to function.  As I stated, it should be a checkbox option whether or not to enable this feature.  If someone has a script that is not suitable for this feature, then they should certainly leave the option to use this feature disabled.  For those who know there script won't cause issues killing it outright, then the option should be available.  The user must decide based on their script whether or not using this feature is a wise choice.  AutoKey does not need to know anything about the script, as long as the user knows the scripts they wrote, and the choice will be the users, so if something goes wrong, AutoKey is not to blame.

**Comment by ineuw** [comment]
Does a running script have a Process ID?

**Comment by josephj11** [comment]
@Git-Forked The fact that print statements do not work is not an AutoKey issue. The problem is that when AutoKey runs, it runs from a GUI environment where stdin and stdout both effectively point to /dev/null. Running a bash script in a GUI environment exhibits the same behavior.

I haven't tried it, but I suspect print() will work fine if you use it with the file object option. If you know the name of your   output device (something like /dev/tty) and use that for the file name, it should work like a default print() does if the current application window (such as a terminal or text editor) is listening for stdin input. It's worth trying...

**Comment by josephj11** [comment]
@ineuw You can get the process ID of the script, but there are a few issues.

First, if you run an external command to get the process ID that uses a subshell to run, then you have to get the parent process ID (the thing that ran the subshell). 

Second, you have to see what that process is. If it's independent, you could send it a sigint signal (what typing Ctrl+C in a terminal does) and that would usually kill it in an orderly fashion. But if the (parent) process is part of AutoKey itself, then killing it might cause problems.

Third, some processes ignore sigint and others may terminate without cleaning up after themselves. You would find this out on a case by case basis. Using sigkill (kill -9) would definitely work, but stops the task immediately with no cleanup. Doing this might work, but it is generally asking for problems with things like buffered output getting discarded, files corrupted or left open, etc. There's no generic way to know what the results/consequences will be.

So, while it's not rocket science, each situation has to be carefully analysed and handled appropriately.

**Comment by josephj11** [comment]
@Git-Forked While you are technically correct that the effects of using such an option would be the user's responsibility, offering it up as a general option gives the impression that it is safe to use.

As someone who does a lot of support for AutoKey, I am not inclined to give unsuspecting users another way to shoot themselves in the foot. If you know enough to handle this correctly, then the burden of adding a kill semaphore into your scripts is very small and will make you much more likely to consider the exact placement of the kill code in your script and what consequences, if any, there are in doing so.

This could possibly be made a bit more convenient by writing a kill on semaphore function (that doesn't use any AutoKey API calls) and placing it in your Modules directory. You could then import it into your other scripts as needed without having to maintain duplicated code. (You can also get it to work using AutoKey API calls, but it's more work to expose the API to your script.)

**Comment by Elliria** [comment]
As frustrating as it can sometimes be, part of coding is figuring out the environment you're coding in and coming up with ways to get around any obstacles that may present themselves. Luckily, AutoKey provides the keyboard.send_key() and keyboard.send_keys() statements to get around that particular obstacle. There are others, but all we can do is tackle them one at a time and see what we can come up with for each one.

**Comment by Git-Forked** [comment]
> @Git-Forked While you are technically correct that the effects of using such an option would be the user's responsibility, offering it up as a general option gives the impression that it is safe to use.  

So, if it makes you feel better, include a notice that it may not be safe for all scripts, use at your own risk.

> 
> As someone who does a lot of support for AutoKey, I am not inclined to give unsuspecting users another way to shoot themselves in the foot.  

Perhaps pillows should stop being sold too then, because a pillow can be used to smother someone to death.

**Comment by Git-Forked** [comment]
Pyautogui has no issues killing a script when the mouse is pointed to coordinates 0,0. 
So, I'm not sure why you folks have so many issues with it.

**Comment by Git-Forked** [comment]
![Auto_Key_feature_request](https://user-images.githubusercontent.com/66106762/169886601-2bb630fc-38ed-4558-aff8-aca37de1e58c.png)

**Comment by Elliria** [comment]
We're not developers. You may yet get your wish. Meanwhile, thank you for your feature request.

**Comment by josephj11** [comment]
Let me clear up some things. The opinions I express are my own and do not represent the project as a whole. I did not add a won't fix label to the issue or close it. If the developers want to implement it, I would not oppose it. I'm just expressing how I feel about it. It's not a big deal to me either way. 

I do feel that a lot of other issues would be more valuable to tackle first, especially since our developers currently have very little time to devote to the project for any purpose. (But I did not assign the low priority label to this issue.) 

Developers have always been a scarce resource for this project although a few have done a lot of work. We usually have one who keeps things going and one or two who occasionally make significant contributions.

**Comment by ineuw** [comment]
How long does this script running that it needs to be suspended? 1 min? 5min? If it's for analysis, would not a MsgBox with a pause pause suffice?

**Comment by Git-Forked** [comment]
> How long does this script running that it needs to be suspended? 1 min? 5min? If it's for analysis, would not a MsgBox with a pause pause suffice?

Your question is irrelevant.  I would not make a feature request were it only good for one script.

**Comment by Elliria** [comment]
That sort of response is not at all helpful, Git-Forked, and can even be taken as downright rude. We're all trying to help you and ineuw is a valued, contributing member of this community. As has been mentioned, you can code it yourself or maybe one of the developers will code it for you if they decide it's a feature they can implement. If you code it yourself and run into any trouble, feel free to reach out to us here or in [AutoKey's Gitter chat room](https://gitter.im/autokey/autokey) or both and we'll try to help figure it out.

**Comment by Git-Forked** [comment]
> That sort of response is not at all helpful, Git-Forked, and can even be taken as downright rude. 

Your response is not helpful and is downright rude.

**Comment by ineuw** [comment]
I find this conversation hilarious. At this point, I believe that @Git-Forked is doing this on purpose.  I vote to close this topic.

**Comment by Git-Forked** [comment]
> I find this conversation hilarious. At this point, I believe that @Git-Forked is doing this on purpose. I vote to close this topic.

This isn't the place to vent your feelings. If your feelings are hurt, simply stop replying and get off my post.

**Comment by josephj11** [comment]
This is your issue, but it's our project. If you insist on being antisocial, we'll have to consider our options.

Why would you think that being rude would increase your prospects of getting your enhancement implemented?

This started out as a valid feature request, but when some of us expressed our opinions (and that's what they were stated as - not as won't fix or invalid request) that it might not be the best idea or best use of very scarce developer resources, you apparently felt offended. I am sorry if anything we said seemed like a personal attack. It was certainly not intended that way.

I have been supporting this project for over ten years and I cannot recall another issue which became personal/antagonistic. We are all friends here (however distant) and want to keep it that way. This is not Twitter.

As for some of the specific suggestions: I have been asking questions here and elsewhere for a very long time. Getting an answer that misses the point of the question (sometimes to the point of wondering if the poster even read the whole question) is a relatively frequent occurrence. It can be very frustrating, but without specific  evidence, I always assume that the poster was acting in good faith and trying (however unsuccessfully) to be helpful. I try to make an additional effort to politely clarify my question and address why the suggestion doesn't meet my needs.

This is just part of the territory. It's what it takes to communicate effectively and to increase the likelihood of a desired outcome. It's basic human respect.

**Comment by BlueDrink9** [comment]
This is a request for a convenience feature (i.e., saves you implementing the workaround Joe mentioned). It also wouldn't be a trivial fix.

Given the very limited dev resources, unless we get a lot of other (and more polite) users chiming in requesting this, I've set this as low-priority.
