### ISSUE TITLE
The hotkey '<super>+k' is already in use by the AutoKey global hotkeys.

### ISSUE THREAD

**Issue by michaelmoreno** [autokey/autokey#705]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### Which Linux distribution did you use?

Arch 5.15.48-1-lts

### Which AutoKey GUI did you use?

Qt

### Which AutoKey version did you use?

0.95.10-4

### How did you install AutoKey?

pacman -S autokey-qt

### Can you briefly describe the issue?

I am trying to set a script that executes `keyboard.send_keys("<down>")` when `super`+`k` is pressed. It appears Autokey has already reserved `super`+`k` for it's own global shortcut to open autokey-qt (a shortcut I have never use).

I need `super`+`k` to be available, as my `super` key is the easiest modifier for me to press, and `k` is the most natural key for acting as `ArrowDown` - a modifier that I use constantly. No other chord will be satisfying.

How can I disable or change the autokey global keybinding to something else?

### What are the steps to reproduce the issue?

1. Install autokey-qt
2. Try to set a script whose hotkey is `super+k`

### What should have happened?

There should be some option to disable the global hotkey or set it to something use to unreserve the desired hotkey.

### Do you have screenshots?

![autokey](https://user-images.githubusercontent.com/72640530/174893393-00bc1308-124f-4046-baca-b3817096d545.png)

**Comment by michaelmoreno** [comment]
Update: You can edit global hotkeys by going to Settings->Configure AutoKey->Special Hotkeys

**Comment by josephj11** [comment]
BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.
