### ISSUE TITLE
updated libnotify 0.8.0-1 breaks autokey-gtk on arch linux

### ISSUE THREAD

**Issue by iamringobingo** [autokey/autokey#713]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Crash/Hang/Data loss

### Which Linux distribution did you use?

OS: EndeavourOS Linux x86_64
Kernel: 5.15.54-1-lts
Packages: 1569 (pacman)
Shell: zsh 5.9
Resolution: 1920x1080
WM: bspwm
CPU: Intel Core 2 Duo P8700 (2) @ 2.534GHz
GPU: AMD ATI Mobility Radeon HD 4650/5165
Memory: 1242MiB / 3892MiB

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.96.0-beta.10

### How did you install AutoKey?

yay -S autokey (or autokey-git)

### Can you briefly describe the issue?

simply crashing

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. have autokey installed
2. have libnotify 0.7.12-1 installed
3. sudo pacman -Suy (thus getting upgraded libnotify (0.7.12-1 -> 0.8.0-1)
4. reboot

### What should have happened?

autokey-gtk should load normally

### What actually happened?

autokey-gtk crashed

### Do you have screenshots?

Not any longer, because I've fixed it by downgrading libnotify 0.7.12-1 from 0.8.0-1 back to 0.7.12-1

### Can you provide the output of the AutoKey command?

```bash
Not any longer, because I've fixed it by downgrading libnotify 0.7.12-1 from 0.8.0-1 back to 0.7.12-1
```

### Anything else?

My (hopefully temporary) solution has been 
$ sudo downgrade libnotify
from 0.8.0-1 back to 0.7.12-1

**Comment by 0x7969** [comment]
Same here. The AUR maintainer just provided a quick fix though, which works for me.

**Comment by josephj11** [comment]
Can someone clarify this issue for me? Is this a packaging bug, etc. or is this a bug that will spread to other distros as they upgrade libnotify. Arch is ahead on most upgrades, so I would guess that this problem will probably spread as other distros upgrade later.

If someone wants to try it, it would be good to know if this also affects our Qt front end. (I know it's a bit of trouble to install it on Arch because of the way they package AutoKey.) I don't know our code base, but libnotify sounds like something both front ends would use.

This could easily transition from a minor annoyance to a critical bug.

**Comment by seanjseymour** [comment]
Apparently this was actually an issue with libnotify, see similar issue [here](https://github.com/varietywalls/variety/pull/546#issuecomment-1186564283) that affected variety. Arch now has libnotify-0.8.1-1 with the fix.

**Comment by josephj11** [comment]
Thanks! I was worried that we would have to patch something on our end.

Can you close this now?

**Comment by seanjseymour** [comment]
I'm not sure that I can, I think @pierostrada may have to since they opened it?

**Comment by josephj11** [comment]
@seanjseymour  Oops. My error.

@pierostrada If this is resolved externally to AutoKey, it would be good for you to close this issue.

**Comment by iamringobingo** [comment]
It's not 'resolved', at all: I've just downgraded my libnotify from 8 to 7, and prevented its update.
Not a problem for me at the time being, but I won't consider one temporary path as a global solution.

BTW, I don't really need autokey any longer, since for my needs I can use its dataset with a bash script.

Anyway, pls feel free to close the case - or tell me explicitly to close it, if I'm the one who shall do it.

Peace

**Comment by iamringobingo** [comment]
Ok - just updated to libnotify-0.8.1-1 : it's ok. As far as I'm concered, this issue is solved.
Thanks you all, peace

**Comment by josephj11** [comment]
@pierostrada Glad it's resolved.

If you are doing anything interesting with bash even though it's not AutoKey, I'd be interested in hearing about it. I do a lot with bash and have some experience with xdotool.

If you are so inclined, you can join us on [Gitter](https://gitter.im/autokey/autokey) or I can invite you to my personal Gitter page.

**Comment by iamringobingo** [comment]
:blush: [josephj11](https://github.com/josephj11) !
Honoured, and pleased to - but hey, I'm just a common old-school linux dude... not a guru at all :D 

So, I'm happy to share my little 'rofi-autokey' script with you and anybody who may be interested:
[rofi-autokey.txt](https://github.com/autokey/autokey/files/9148132/rofi-autokey.txt) - hope the link works - in case pls let me know.

And of course yes, please: Im elated to accept your invitation to [Gitter](https://gitter.im/autokey/autokey)

Thank you all, again
Piero

**Comment by josephj11** [comment]
It's  a common misconception to think everybody knows more than you do - especially in Linux. My only advantages are having been an AutoKey user forever, so I've seen most of its ins and outs, but I only know a little Python, so I don't contribute to the code base. I was also a professional programmer, but mostly in languages that aren't mainstream any more. The only language I'm fluent in now is bash. I also know a fair amount about configuring KDE at the user level because I've also been using that forever.

Your link did not work. I think you made a common mistake that I just ran into recently. If you don't prefix your link with something like `https://`, GitHub assumes that the URL is relative to the current repository, so it doesn't do what you'd expect. Let's get that fixed and go from there.

The main Gitter link I already gave you is public and you're welcome to lurk or contribute there. We only need my private one if we get too far off topic for AutoKey. I'm also "old school" and still do a lot with email. Whatever works best. Places like Gitter use markdown. so they're better for sharing any structured text such as code.

**Comment by iamringobingo** [comment]
Here we are, Mr. [josephj11](https://github.com/josephj11).

_> It's a common misconception to think everybody knows more than you do - especially in Linux._ 
No misconception, sorry - I think it's just true: after all each of us is somebody else's "everybody". LOL

First of all: the broken link.
Yes I was suspecting my first time here could me a bit messy: so I prepared a pastebin, and here you have it, Gentlemen:
**[https://pastebin.com/7qCJw7UF](https://pastebin.com/7qCJw7UF)**

Then, just to introduce myself a little bit: Italian, born 1960, began with studying (not necessarily learning) Ansi-Cobol in 1981; then Sinclair's ZX80/Spectrum, Atari 1020... 

Saw my first *nix light at work in the mid '90ies (slackware on 3.5" floppies), stuck to Cobol + mysql & Unix/Linux on a side and MS-DOS cmd +  Clipper/Visual Basic + Jet on the other... Guess you can get the idea.

Today... can somewhat curse and customize a DWM in C++,  and/or do some basic Python tricks... even Rust if needed - but really not my piece of cake: definitely a shell-guy here.

And, since you mention it, I'm not a markdown-wizard, but I'm happy with my neovim+vimwiki/vimdiary skills.

Officially, I earn my living playing the bush-doctor: the one who revives ppl's Win PCs, giving those old ladies-machines their renewed, virus-free, mostly FOSS Linux lives - and the kids simply their data toys.

BTW, people seem to see me more comfortably as some kind of weird, supernatural being than a simple, boring old hacker - in it's most technical meaning: but thank God, I'm an atheist.

On my own front, I simply love to learn, and I'm happy with my Arch + BSPWM + zsh workflows,  but above all to I love to be and feel free - and anarchist.
So XX century, I know.

On the social/communications side: Nokia 3330-> Oki ->Motorola Vip->iPhone->Android, and today also a proudly de-googled LineageOS. And I am 100% Meta-free, and I still use SMS, and even email.

Enough said for now? Maybe too much - and I apologize if so.

Once again, thanks & peace.
