### ISSUE TITLE
Autokey GTK & QT 0.69.0 & 0.69.0-beta.10 no longer run scripts using pyautogui

### ISSUE THREAD

**Issue by Git-Forked** [autokey/autokey#719]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

Manjaro

### Which AutoKey GUI did you use?

Both

### Which AutoKey version did you use?

0.69.0 & 0.69.0-beta.10

### How did you install AutoKey?

distribution repository & git

### Can you briefly describe the issue?

Autokey GTk & QT 0.69.0 & 0.69.0-beta.10 no longer run scripts using pyautogui, so, any script using pyautogui is now effectively broken.  Launching autokey with the -l option shows in the terminal that the script was executed, however nothing happens. It seems the script is never processed.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

Make a script using pyautogui,
run the script,
nothing happens and there is not even an error displayed.

### What should have happened?

The script should have ran.

### What actually happened?

Absolutely nothing.

### Can you provide the output of the AutoKey command?

```bash
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 958, sequence_number = 67, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 958, sequence_number = 68, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 958, sequence_number = 69, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 958, sequence_number = 70, major_opcode = 33, minor_opcode = 0
2022-07-30 15:59:26,073 INFO - autokey.interface - XRecord interface thread starting
2022-07-30 15:59:26,073 INFO - autokey.service - Service now marked as running
2022-07-30 15:59:26,078 DEBUG - autokey.gtkui.popupmenu - Sorting phrase menu by item name/title
2022-07-30 15:59:26,080 DEBUG - autokey.dbus_service - Created DBus service
2022-07-30 15:59:26,080 INFO - autokey.gtkapp - Entering main()
2022-07-30 15:59:32,303 DEBUG - autokey.service - Raw key: <Key.F9: '<f9>'>, modifiers: [], Key: Key.F9
2022-07-30 15:59:32,304 DEBUG - autokey.service - Window visible title: '~ : autokey-gtk — Konsole', Window class: 'konsole.konsole'
2022-07-30 15:59:32,304 INFO - autokey.service - Matched Script "Test" with hotkey and prompt=False
2022-07-30 15:59:32,305 DEBUG - autokey.service - Script runner executing: Script('Test')
```

**Comment by Git-Forked** [comment]
Solved: 
Pyautogui requires tkinter which Manjaro has renamed to 'tk', and it was not installed as a dependency through Manjaro package manager, probably due to being renamed. 
So, this is an issue with Manjaro and not with Autokey. 
I will close this issue.

**Comment by josephj11** [comment]
I was writing this before you posted your solution.

We have had a lot of reports with Xlib errors. We never fully figured out what that's about, but there were some indications that it was related to using a hotkey that something else was already using.

The first thing I would try is selecting the option to Show in notification icon menu and run it from there. This will show us if the Xlib errors go away and if your script runs without any possible triggering problems.

If it still runs and does nothing, then this will require advanced debugging skills (strace...) to figure out.

Providing a copy of the script that fails will help the developers recreate the issue.

 Do you have any information about what changed on your system since the last time your script worked? It would really help narrow down the problem.

Since Manjaro is an Arch fork, it gets updated packages very early and can reveal problems before they reach other distributions.

BTW, the current releases are 0.96...
