### ISSUE TITLE
keyboard.send_keys("<enter>") not working in terminal

### ISSUE THREAD

**Issue by cycloss** [autokey/autokey#733]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

Ubuntu 20.04.4

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.95.10

### How did you install AutoKey?

apt

### Can you briefly describe the issue?

I use a vim like keyboard configuration to navigate text. Part of this involves binding the enter key to the shortcut 'ctrl+;'.
I've achieved this by setting those keys as the hotkey for the following script:

```python
keyboard.send_keys("<enter>")
```

This works great and presses the enter key in all programs apart from the terminal. The terminal just sounds the error bell and nothing happens when pressing the shortcut. I have a feeling this is something to do with how the terminal interprets the enter key. Any ideas as to why this might be happening?

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. bind ctrl + ;  to `keyboard.send_keys("<enter>")` 
2. Attempt to use the binding in the terminal

### What should have happened?

The terminal should accept the simulated enter key and execute the current command.

### What actually happened?

The error bell rings

### Do you have screenshots?

No

### Can you provide the output of the AutoKey command?

```bash
No
```

### Anything else?

No

**Comment by Elliria** [comment]
First, a couple of questions:

- What happens if you open the terminal window and press **Ctrl** + **;** when AutoKey isn't running? You may be experiencing a conflict with another hotkey combination set by your terminal window or the operating system or some other running program.

- What happens if you open the terminal window and manually press the **Enter** key?

Now for a possible work-around:

Does ```keyboard.send_key("<code104>")``` give you a press of the **Enter** key? I got that keycode by following an example in the [Customized special keys](https://github.com/autokey/autokey/wiki/Special-Keys#customized-special-keys) section of the [Special Keys](https://github.com/autokey/autokey/wiki/Special-Keys) page and the [Using special keys](https://github.com/autokey/autokey/wiki/Special-Keys#using-special-keys) section shows various ways to use them. The keycode may be different for you, so you might want to try to follow one of those examples to see which keycode your **Enter** key uses.

**Comment by cycloss** [comment]
@Elliria thanks for your comments. Your suggestion that I send the key code put me on the right track. I used `xev` to check which key code was being sent when the raw enter key was pressed which turned out to be 36 on my machine, so I put in `<code36>` and it worked perfectly. Strange that it didn't work with `<enter>` as I found that it did work in the integrated vscode terminal, but not with the gnome terminal. Must be something to do with a difference in how they interpret the key presses.

**Comment by josephj11** [comment]
@cycloss Your original script should have worked. I'm curious as to why it didn't.

How did you implement your "vim like keyboard configuration"?

If it involved a secondary keyboard layout or some remapped keys (especially the Enter key), AutoKey tends to ignore such mappings which often results in unexpected behavior.

Since you have a solution to your issue, nothing further is needed now, but ...

Whenever AutoKey appears to be misbehaving and staring at your code doesn't reveal the solution, it can be quite helpful to run an AutoKey [trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide) to see things from AutoKey's point of view. If you end up filing an issue, including trace output can sometimes make diagnosing the problem much easier.

Another possibility would be to place an Enter in the clipboard and paste it with a Ctrl+v. You can do this in a script, but a simple phrase will do if you select the Paste using clipboard (Ctrl+V) option (which is the new default option starting with our current release, 0.96.0).

**Comment by Elliria** [comment]
I'm glad it all ended up working out. It sure is strange that it was an issue at all, though, considering it's a default terminal and not some wild piece of software that you installed after the fact.
