### ISSUE TITLE
unicode chracter

### ISSUE THREAD

**Issue by GuShaocheng** [autokey/autokey#745]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Which Linux distribution did you use?

ubuntu

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.95.10

### How did you install AutoKey?

pip3

### Can you briefly describe the issue?

only ASCII characters are able to output via send_keys(), how about Unicode characters? 

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

content="ascll_unicode:茾_ascll"
keyboard.send_keys(content)

### What should have happened?

the output should include the Unicode character in the string.

### What actually happened?

Unicode characters are ignored

**Comment by josephj11** [comment]
This is a perennial issue. Basically, we can't fix it without a major rewrite and it still might not work.

This is one reason the new default for phrases is Paste using Ctrl+V.

However, there are several ways to emit them.

Take a look [here](https://github.com/autokey/autokey/wiki/Unicode-Characters) and [here](https://github.com/autokey/autokey/wiki/Emitting-Keyboard-Events).

----

We recommend that you upgrade to our current release. It has lots of bug fixes and several new features. See the Changelog for details.

If you are using Ubuntu 20.04 or newer, you can upgrade to our current release 0.96.0 directly in your package manager.

If you are using an older version of Ubuntu, you can upgrade AutoKey from [GitHub](https://github.com/autokey/autokey/releases/) following these [instructions](https://github.com/autokey/autokey/wiki/Installing).

AutoKey is available already packaged in debs, so upgrading is very easy for Debian and its derivatives (such as Ubuntu).

Always make a backup of your scripts and phrases before upgrading. In particular, the metadata sidecar files that accompany each phrase and script will be automatically renamed by 0.96.0 so they are no longer hidden files. This is not backward compatible, so in the unlikely event that you want to revert to an older version, you will need to undo that manually or restore them from your backup.

**Comment by josephj11** [comment]
When you run into issues with AutoKey, we're glad to help. Generally, it's best to ask for support before filing an issue.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.
