### ISSUE TITLE
loop doesn't loop

### ISSUE THREAD

**Issue by sl5net** [autokey/autokey#748]
my mistake, pls close it

**Comment by sl5net** [comment]
my mistake

**Comment by josephj11** [comment]
@sl5net  Thanks for closing this.

We're happy to help users with all aspects of AutoKey. When you first encounter an issue (that's not already filed here) or want to discuss anything related to AutoKey, come over and post on our support forums. See boiler plate below.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by josephj11** [comment]
@sl5net I briefly scanned through your script from the original post. It looks like you know a fair amount about Python. If you're interested, we would value your participation on Gitter in the future.

If you're doing any more scripting like this, you really should consider upgrading to our current release 0.96.0. It has a lot of bug fixes and a few new features. It's available in the standard repos for Debian and Ubuntu 20.04 and newer. Or you can get the debs or source from us [here](https://github.com/autokey/autokey/releases/). Instructions [here](https://github.com/autokey/autokey/wiki/Installing).
