### ISSUE TITLE
[BUG] [ahk_x11] Click and MouseClick problem

### ISSUE THREAD

**Issue by Splarkszter** [autokey/autokey#756]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

Operating System: Linux Mint 21.1 Cinnamon
Cinnamon version: 5.6.5
Linux Kernel: 5.15.0-56-generic

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.96.0

### How did you install AutoKey?

GitHub

autokey-common_0.96.0_all.deb
autokey-gtk_0.96.0_all.deb

### Can you briefly describe the issue?

Part of my code is this:

Click 680, 550
Sleep 15000
Click 100, 290
Sleep 100
Click 680, 325
Sleep 100

And when i try to run the script it says: Command 'Click' not found

If i use MouseClick, it does nothing, the IconTray flickers a lot until i manually move the mouse.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

Issue1:

Click 680, 550

- Execute script (make sure to it be .ahk)

- It trows you the error.

Issue2:
- Replace 'Click' with 'MouseClick' and the mouse won't move, the icontray will flicker until you move the mouse (at least that's what happens to me).

Extra: I just noted that when i write Send, {LButton, Down} the key name 'LButton' is not found too.

### What should have happened?

Mouse should have moved to the specified coordinates (in my script set to 'CoordMode, Mouse, screen') and click when it reached it.

### What actually happened?

[Already described]

### Do you have screenshots?

'Click' command not found:
![image](https://user-images.githubusercontent.com/90066319/210474372-0e3942a2-5369-403e-83e3-828126aeb8e4.png)
Key name 'LButton' not found:
![image](https://user-images.githubusercontent.com/90066319/210474465-e3e0309a-9958-461b-ab9f-c4d6cab7534f.png)

### Anything else?

Tried to do:

MouseMove, 1255, 123
send, {LButton, Down}
sleep 50
send, {LButton, Up}

But hence LButton is not recognized it doesn't work either.

MouseMove, 1255, 123
sleep 1000
send, {LButton}
Return

Doesn't click either and it closes itself instead of doing what The 'Return' tells it to do

**Comment by sebastiansam55** [comment]
Autokey is not a dropin replacement for ahk unless I have missed some serious changes.

It uses python, not whatever scripting language you have here.

I think this documentation is still the only place the new mouse methods are documented
https://samuelsebastian.dev/autokey/api/mouse.html

So
```
mouse.click_absolute(1255, 123)
```

Is more what you want/need to do

**Comment by josephj11** [comment]
@Splarkszter Welcome to AutoKey!

What Sam said.

Our scripts are written in Python and there is no conversion tool  for AutoHotKey or other scripts (although we'd be happy to consider one if someone wants to write one.)

However, for many purposes, it is relatively easy to manually construct a new script that will do the same thing your AHK script did. Until you get into advanced use cases with decision making and external resource access, coding most scripts requires very little knowledge of Python. And when you do need help with Python, the web is loaded with examples and tutorials.

See our newer [documentation](http://autokey.github.io/autokey/api/mouse.html) and read through our [wiki](https://github.com/autokey/autokey/wiki) which contains a lot of useful information and many example scripts.

These are not native Python commands. Our API functions are provided by Python modules, so you have to reference the module to let Python know where to find them.

That's why you need syntax like `mouse.click(...)` rather than `click(...)`.

The same goes for `sleep()`. You need to use `time.sleep()`.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by Splarkszter** [comment]
I remember reading that you can execute .ahk scripts (the script i was referring to is on the AHK language) using ahk_x11 to execute them and as long as it had the .ahk extension.

This script for example worked kind of perfectly out of the box, only problem is that the tooltip doesn't follow the mouse when the tooltip is updated, probably a limitation or thing with linux more than nothing.

``#singleinstance force
#Persistent

coord = screen

tooltip, %coord%
sleep, 1000

CoordMode, ToolTip, %coord%
CoordMode, Pixel, %coord%
CoordMode, Mouse, %coord%

SetTimer, WatchCursor, 100
return

WatchCursor:
MouseGetPos,xpos , ypos

ToolTip, xpos: %xpos%`nypos: %ypos%

p::exitapp``

For some reason i can't find where it was but i did read it in this GitHub while i was exploring it. But i swear it said somethinf like this:

You can execute AHK scripts using 'ahk_x11' as long as it's written on the AHK language and the script file has the '.ahk' extension although your script may need some modifications for it to work properly.

**Comment by Splarkszter** [comment]
**Wait, i think i had a confusion here. I'm very sorry.**

Seems that i didn't notice i obtained ahk_x11 from another source(don't remember how i installed it), and i believed it was from the instalation files from here.

**Comment by josephj11** [comment]
Glad that's sorted. I would encourage you to explore AutoKey anyway. The learning curve isn't very steep to get good enough to do most things and it will go far beyond what AHK can do when more complex needs arise.

**Comment by Splarkszter** [comment]
I will try, thanks!

I will need to learn python for the future too, so i guess this will be good practice.

**Comment by josephj11** [comment]
@Splarkszter If you are learning Python, it is much easier to just start Python. It's an interpreter, so you can type your statements directly into it and get immediate feedback on what they do. You can also print variable values, etc. for debugging.

To start with, you can add fake API calls that just produce fixed results to make debugging easier. Once you have the Python part of your script working, you can add our API calls and run it in AutoKey.

If you start out in AutoKey, it's kind of like being blindfolded because you don't see any errors, etc. until after your script runs and you have to do more steps to see them...
