### ISSUE TITLE
autokey does on Ubuntu 22.04 no longer allow to set hotkeys. What can I do? 

### ISSUE THREAD

**Issue by hsc57** [autokey/autokey#757]
## Classification:
(Pick one: Bug, Crash/Hang/Data loss, Enhancement, Feature (new), Performance, UI/Usability)

## Reproducibility:
(Pick one: Always, Sometimes, Rarely, Unable, I didn't try)

## AutoKey version:
(Paste in your AutoKey version and, if the problem is known to be present in more than one version, please list them all.)

## Used GUI:
(Pick one: Gtk, Qt, Both):

## Installed via:
(Pick one: PPA, pip3, Git, package manager, etc.)

## Linux distribution:
(Provide information about your Linux distribution and its release or version number.)

## Summary:
(Provide a brief summary of the problem.)

## Steps to reproduce:
- I do this.
- Then I do that.

## Expected result:
(Explain what should happen.)

## Actual result:
(Explain what actually happens.)

## Screenshot (if applicable):
(Include one or more screenshots of the issue by dragging the image file(s) here to help with debugging.)

## Verbose output (if applicable):
(Include the output from launching AutoKey via the `autokey-gtk --verbose` or `autokey-qt --verbose` command to help with debugging. Please upload the output somewhere accessible or paste it into a code block here, enclosing it in triple backticks.)
```
Example code block. Replace this with your output content.
```

## Notes:
(Describe debugging steps you've taken, a workaround you've figured out, or any other information you think we might need.)

**Comment by josephj11** [comment]
First, make sure you're running X11 and not Wayland. There's an option to choose X11 on your login screen. Ubuntu 22.04 defaults to Wayland and AutoKey isn't compatible with that (we're looking into how to fix that).

If that's not the issue, see below.

Please don't file issues to ask questions. We have two forums where we are happy to provide support. See boiler plate below. If you do post on our forums, please provide more information like that requested on our new issue form so we can resolve any issues you are having more quickly.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by hsc57** [comment]
many thanks,  runing xorg on Ubuntu solved the problem to set the 
hotkey, but unfortnately it does still not work. Pushing the set hotkey 
does not reproduce the phrase....




Am 07.01.23 um 01:09 schrieb Joe:

**Comment by josephj11** [comment]
The next thing to check is that your choice of hotkey isn't already in use by some superseding software such as your desktop manager. KDE in 22.04 uses more than 20 hotkeys for some very obscure purposes.

Try another hotkey such as super+a or something else that is unlikely to be used elsewhere. If that fixes it, we can explore why your desired hotkey doesn't work.

Whenever AutoKey seems to be misbehaving and staring at your code doesn't reveal the answer, running an [AutoKey trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide) allows you to see things from AutoKey's perspective and will be useful in documenting any actual bugs that are discovered. 

I expect a lot of AutoKey users have migrated to 22.04 or a derivative of it, so if this was a general problem, we probably would have received a number of reports already.

When you report a problem to us, providing more information to start with can greatly speed our response and a possible resolution. The linked Problem Reporting Guide details the basics. Each situation may have additional factors that will be helpful to know.
