### ISSUE TITLE
Access API from imported code

### ISSUE THREAD

**Issue by Pistos** [autokey/autokey#758]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

UI/Usability

### Which Linux distribution did you use?

Gentoo, kernel version 5.10.52

### Which AutoKey GUI did you use?

Qt

### Which AutoKey version did you use?

`master` @ fbcc72b8d9b6d87c0c49520eef7e0abef3750177

### How did you install AutoKey?

Running directly from git checkout, `python -m autokey.qtui -c`

### Can you briefly describe the issue?

Although the API is accessible just fine from a normal, single-file script, when I try to access a globals like `keyboard` from a module file instead of the script being run, then it is not found

`NameError: name 'keyboard' is not defined`

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. Settings | Configure AutoKey | Script Engine | Browse
2. Choose a directory, such as `~/.config/autokey/lib`
3. Create a Python module under that lib dir, such as in subdir `foo/`, with `__init__.py`, etc.
4. In that module file, reference `keyboard` in a function, such as `keyboard.send_keys(...)`
5. Create a new script in the AutoKey GUI
6. In that script, `from foo import some_function`, and call `some_function`

### What should have happened?

`keyboard` should be accessible from module code

### What actually happened?

`NameError: name 'keyboard' is not defined`

### Anything else?

Things work fine if I copy-paste the functions out of the module, and just inline them at the top of the script file.

I'm guessing that `keyboard` is defined or populated in a special way by the runner. Perhaps this code:

https://github.com/autokey/autokey/blob/fbcc72b8d9b6d87c0c49520eef7e0abef3750177/lib/autokey/service.py#L467-L484

**Comment by Elliria** [comment]
For the moment, you should be able to find some hopefully useful information in [this AutoKey discussion](https://github.com/autokey/autokey/discussions/743), which I'll turn into an AutoKey wiki page. I've just been putting it off because converting it to Markdown isn't pleasant and I can usually come up with lots of other things to do, so it goes onto the back burner.

**Comment by josephj11** [comment]
Welcome to AutoKey, @Pistos .

Please see #248.

This is a known issue. I've been trying to get it fixed forever, but the devs don't quite see how to do it correctly.

There are a couple of workarounds in the issue referenced above.

If you have any ideas, let us know.

**Comment by Pistos** [comment]
Thank you. This does seem to be a duplicate of #248 , so I will close this issue. I'm fine with the proposed workaround, for now.

(I apologize for creating a duplicate issue. Honestly, I did search the issues first, but I guess 248 was so deep (page 4 or 5) that I missed it.)

**Comment by josephj11** [comment]
I've been here forever, so I know most of the old issues. Searching always works better when you already know the answer. ;)

I haven't seen anyone using this feature, so please keep in touch about your progress. You can join us on [Gitter](https://gitter.im/autokey/autokey) and/or add examples to our [wiki](https://github.com/autokey/autokey/wiki/Example-Scripts).

Our [Community](https://github.com/autokey/autokey/wiki/Community) page shows all the ways to communicate with us and the [Gitter](https://github.com/autokey/autokey/wiki/Gitter) section has a bunch of tips for working with Gitter that I just added.

**Comment by Pistos** [comment]
> please keep in touch about your progress

I'm able to do what I need to do by passing the Autokey handles, like this:

```python
# music.py
class Music:
    def __init__(self, keyboard):
        self.keyboard = keyboard

# script.py
from music import Music

m = Music(keyboard)

m.play_8d(1)
```

I would like to join a chat room, but I saw that Gitter requires that the github email address be surrendered. I'm not willing to give that. Perhaps you can consider running a Gitter-IRC bridge or something, or some other chat system which is less invasive.

Thanks for welcoming me to the community, though.

**Comment by josephj11** [comment]
We do have IRC (#autokey on Freenode).

Posting there causes the posts to show up on Gitter somehow. I'm not an IRC fan, so I don't use it. The issue with it is that people check into Gitter or the IRC asynchronously, so it may be a while till you see a reply.

IDK if it helps at all, but you can also access Gitter using  the Matrix web interface or the Element_desktop app.

**Comment by Pistos** [comment]
Oh yes, I recall now seeing that you had a Freenode channel. However, I left Freenode after that big fiasco (for Libranet). Anyway, I appreciate your help.

Re, the Gitter app(s): It looks like you still have to sign in, if I read things correctly: https://gitlab.com/gitterHQ/desktop

**Comment by Elliria** [comment]
When you sign in to Gitter with GitHub, GitLab, or Twitter, you're using a [personal access token](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) that's within your full control. What I do is log in to GitHub and then open the AutoKey Gitter page. I then log in to the AutoKey Gitter page with GitHub. The first time I did it, I was prompted by GitHub to grant the access and to customize it. From then on, it just logs you in without having to set it up each time. You can make the personal access token very restricted and they're only getting access via that token and not with your full GitHub or GitLab or Twitter account. You can also delete the token at any time (or cause it to expire automatically) if you like.

Also, I just looked back up at your first comment about this and realized that it was the email address that was a concern (I agree with that, since we all get enough spam as it is and it's never a good idea to risk more). You can log into GitHub with either your email address or your username. I use my username. If you do that, I'm hoping it doesn't share your email address. Either way, I figured I'd jump in here and say that I've been logging into that Gitter chat room for years now and have not received any spam email messages from them.

Last, but not least, if you decide not to go for it, you can read any/all of the Gitter chat without logging in, which can still make it a useful resource.

**Comment by josephj11** [comment]
@Pistos That doesn't ring any bells for me. Do you have a link about Libranet so I can read about it? I did a search and all I saw were references to a very old Linux distro.

**Comment by Pistos** [comment]
@josephj11 My mistake. I remembered the name wrong. [Libera](https://libera.chat/) is the name of the IRC network.

If you websearch for the words `freenode` and `libera`, you'll find a lot.

**Comment by josephj11** [comment]
@Pistos Thanks. I looked it up and posted on Gitter that maybe we should consider moving our IRC. What a mess!

Some last ideas:

If you are so inclined, you can join us on our Google [forum](https://groups.google.com/forum/#!forum/autokey-users). It's pretty easy to get a new Gmail account that is separate from the rest of your online activity. That group usually deals with more basic support, but you can reach us there.

Another alternative would be to start or join one of our [discussions](https://github.com/autokey/autokey/discussions) on GitHub.

We're also on Discord and Reddit although we're less active there. See [this](https://github.com/autokey/autokey/wiki/Community).

**Comment by Pistos** [comment]
Actually, Google accounts can no longer be made without supplying a phone number, so that's not an option for me, either. Sorry to be so problematic :sweat_smile: but I do appreciate your trying to help. You're giving a good impression of the Autokey community.

The Github Discussions feature does seem viable for me.

**Comment by josephj11** [comment]
@Pistos You may find this interesting. It just showed up in a Brave ad. It's new to me, so I'm not vouching for it.

https://www.cloaked.app

**Comment by Pistos** [comment]
Looks interesting, but I'm not seeing how they can make that profitable, giving out that many functional phone numbers. Anyway, we've veered way off the original topic of this github issue. We should probably continue our friendly conversation in some other medium. :)

**Comment by josephj11** [comment]
@Pistos I think this particular "thread" is done.

If you ever want to contact me directly:

The main difficulty is in establishing the initial private connection.

I prefer email, but since that probably won't suit you, maybe keet.io would be more convenient and private. It does text/audio/video peer to peers. I can generate an invitation link that lasts two days (but I don't regularly run it, so we'd have to arrange a time.) So far I have only used it between two of my notebooks to make sure it works. It seems very simple to use.

I can  also use Telegram, Status network, and Nostr, but aside from Telegram, I have very little experience with them. Didn't have anyone to talk to on them to get in any practice.

I'm open to other alternatives if there is something you prefer.

**Comment by Pistos** [comment]
You can find me (same name) on Libera IRC. I'm actually in the `#autokey` channel there already.
