### ISSUE TITLE
Kubuntu 22.04 Activate either version fails

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#817]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [X] autokey-qt
- [ ] beta
- [X] bug
- [X] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Kubuntu 22.04

### Which AutoKey GUI did you use?

Both

### Which AutoKey version did you use?

96.0

### How did you install AutoKey?

```
#!/usr/bin/bash
# 2022-11-18 06:46 - 01_all_install_autokey.sh (dgdrive /media/dgdrive/scripts)

sudo apt update
sudo apt install python3-pip -y
pip3 install cffi
pip3 install --user https://github.com/autokey/autokey/archive/v0.96.0.zip
sudo apt install xautomation
echo
read -p "autokey and xautomation installed"
```

### Can you briefly describe the issue?

```
ineuw@ku2204dt:~$ autokey-qt -c
Traceback (most recent call last):
  File "/home/ineuw/.local/bin/autokey-qt", line 5, in <module>
    from autokey.qtui.__main__ import Application
  File "/home/ineuw/.local/lib/python3.10/site-packages/autokey/qtui/__main__.py", line 23, in <module>
    from autokey.qtapp import Application
  File "/home/ineuw/.local/lib/python3.10/site-packages/autokey/qtapp.py", line 41, in <module>
    from autokey.qtui import common as ui_common
  File "/home/ineuw/.local/lib/python3.10/site-packages/autokey/qtui/common.py", line 26, in <module>
    from PyQt5.QtSvg import QSvgRenderer
ModuleNotFoundError: No module named 'PyQt5.QtSvg'
ineuw@ku2204dt:~$ autokey-gtk -c
Traceback (most recent call last):
  File "/home/ineuw/.local/lib/python3.10/site-packages/autokey/gtkui/notifier.py", line 29, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ineuw/.local/bin/autokey-gtk", line 5, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/ineuw/.local/lib/python3.10/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/ineuw/.local/lib/python3.10/site-packages/autokey/gtkapp.py", line 40, in <module>
    from autokey.gtkui.notifier import get_notifier
  File "/home/ineuw/.local/lib/python3.10/site-packages/autokey/gtkui/notifier.py", line 31, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
ineuw@ku2204dt:~$ 

```

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

see the above output in terminal

### What should have happened?

Load

### What actually happened?

nothing

### Do you have screenshots?

no

### Can you provide the output of the AutoKey command?

```bash
it shows in the error message
```

### Anything else?

nothing

**Comment by josephj11** [comment]
While this appears to be a valid issue, Given that you're using a Debian/Ubuntu derivative distro, why didn't you install from our debs or those in your distro's repositories (not sure if 0.96.0 is available in your repositories, but it's definitely on our GitHub site.
https://github.com/autokey/autokey/releases/
https://github.com/autokey/autokey/wiki/Installing

Joe

**Comment by Elliria** [comment]
AutoKey 0.96.0 isn't available in Ubuntu by default. All current releases offer AutoKey 0.95.10 or earlier releases: [https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=autokey](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=autokey)

It's unlikely that they'll update it for existing releases. Something like that is a lot of work because it can affect other packages. See their [StableReleaseUpdates](https://wiki.ubuntu.com/StableReleaseUpdates) page for their policy on how such cases are handled.

AutoKey is maintained by [Ubuntu MOTU](ubuntu-motu@lists.ubuntu.com), but we should have a build that installs before contacting them. If you have one or more compelling reasons for them to consider updating the AutoKey version in **existing** releases, you can reach out to them and share those reasons and they'll let you know if they'll do it or not. They're very friendly and helpful.

Otherwise, since they don't seem to have a copy of the current release, it would still be a good idea to get a copy of it to them so that they have it for the current release that they're working on and for future releases. Their [NewPackages](https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages) page would be useful for that. *Note that it says: "Submitting new packages through Debian is the preferred path." That means we'd probably have to go through Debian to get the current release to Ubuntu for current and future Ubuntu releases.*

**Comment by josephj11** [comment]
@Elliria  I looked into this a week or two ago when looking for packager email addresses. From what I could tell, it appeared that they "had" 0.96.0, but since it didn't build cleanly, they didn't include it. The work you're doing now will fix that. Once it's done, we have a choice. If we think 0.96.1 is immanent, we should do nothing  till it gets released and then send out a courtesy note to the packagers we know about. If we think 0.96.1 is further in the future, we can send out a notice that 0.96.0 now builds/tests cleanly so they can decide if any action is warranted on their parts.

**Comment by ineuw** [comment]
No worries - I used the script in Linux Mint Cinnamon since 96.0.4beta and forgot about the .deb file. After posting this issue, I came across another post, about what needs to be installed to correct the issue in Kubuntu. The K organization and layout needs to be learned in any case and this is my 2nd Ku OS install.

**Comment by josephj11** [comment]
@ineuw So, is this still a valid open issue or can you close it?

**Comment by ineuw** [comment]
I didn't forget about it. Please leave it open. I was unable to reboot into Kubuntu which I must repair first, but life keeps interfering.

**Comment by ineuw** [comment]
Autokey-qt works fine in Kubuntu when installing from Github and that is great. 
BTW. How can I set a dark background and larger font in the Qt Kubuntu Autokey editor?

**Comment by josephj11** [comment]
I'm not sure that you can. There's a theme option for that, but it was only added to the GTK front end.

My AutoKey (Qt) menu is in dark mode, buti I don't remember how I got it that way. (I do use a dark theme - Breeze Dark - on my desktop.)

AFAIK, there is no option for changing font sizes in either front end. There might be a way to "patch" it into the source code, If I have time later, I'll see if anything obvious presents itself.

The easiest workaround is to use an external editor where you can setup the display with a lot more flexibility.

**Comment by ineuw** [comment]
I am using Cobalt in GTK in LMC, but it's definitely not a deal breaker. :-) To save time, it's quicker to learn the available tools. Refinement can come afterwards.

**Comment by Elliria** [comment]
Do you happen to remember what was needed to be installed in Kubuntu? We might need to add it to the requirements file.

**Comment by Elliria** [comment]
> From what I could tell, it appeared that they "had" 0.96.0, but since it didn't build cleanly, they didn't include it.

Why did we release it that way? Isn't making sure it builds properly one of the requirements for creating a release?

**Comment by josephj11** [comment]
I think 0.96.0 may have been released before something like current Python version changed. It might have passed the tests initially, but IDK.

I'm guessing @ineuw got it working by installing the debs instead of using pip and that took care of any dependencies.

**Comment by Elliria** [comment]
> I think 0.96.0 may have been released before something like current Python version changed. It might have passed the tests initially, but IDK.

It must not have, since they had a copy of AutoKey 0.96.0 and didn't include it because it didn't build cleanly. It seems odd.

If the **deb** files work, that narrows the search.

**Comment by ineuw** [comment]
Yes, the deb files with qt work without a hitch. . . . . and now on to  getting better acquainted with Ku. 

@Elliria, nothing additional was needed

**Comment by josephj11** [comment]
@Elliria  We can ask them, but when we release something, I don't think anything automatic happens at their end. They would package it if and when they got around to it - which might introduce a delay long enough  for something external to change and break the build. They must have something that alerts them to project releases, because there are way too many packages to track manually.

**Comment by Elliria** [comment]
I'm not sure of their complete process, but am pretty confident that they rely on package submissions rather than actively chasing down new versions. That's also probably true pretty much anywhere. It's not a big deal, though. If we put out a new version, we've got a list of contacts and can reach out to get each of them what they need.
