### ISSUE TITLE
Apostrophe [ ' ] changed in É

### ISSUE THREAD

**Issue by davduf** [autokey/autokey#82]
Hello All,

When i put an Apostrophe [ ' ], it is changed by a É when I use AutoKey.
Do you knoq how I can fix this?

Thank you so much!
All my best

David

**Comment by troxor** [comment]
Perhaps you have a text replacement configured. It could be anything, but this doesn't sound like a bug. Please direct future support requests to the channels mentioned in the README. This issue tracker is for bug reporting only.

**Comment by davduf** [comment]
Sorry about this, but what do you mean by a  a text replacement configured? This is not happened under X11, only Wayland. Thank you !

**Comment by Elliria** [comment]
You may have a setting for Esperanto letters enabled in your advanced keyboard settings and depending on what else is in the script or phrase that you're using that's supposed to print an apostrophe, a Wayland keyboard shortcut is being triggered that causes the replacement to happen. It might also be a locale setting in Wayland that's causing it. Last, but not least, you might need to specify UTF-8 in the application you're pasting into. This is all guessing on my part, but maybe some of it will be of use.

**Comment by josephj11** [comment]
Ummm... This is from 2017 and should stay closed  from inactivity alone. And the OP says it occurred on Wayland where very little is _known_ to work correctly.

My opinion is that we shouldn't address any bugs that appear to be caused by using Wayland. There are plentiy of other things to do and who knows what will change if/when we replace our interface modules with the new ones for Wayland. When that happens, then all Wayland issues can be addressed. By then a lot of things, including Wayland, will have changed, hopefully for the better.

**Comment by Elliria** [comment]
Yeah, I just jumped in here because of CodeTriage.
