### ISSUE TITLE
keyboard.press_key freezes autokey

### ISSUE THREAD

**Issue by NicoReXDlol** [autokey/autokey#820]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Crash/Hang/Data loss

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [X] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [X] scripting
- [ ] technical debt
- [ ] user interface

### Other terms that describe this issue if not provided above:

keyboard press_key

### Which Linux distribution did you use?

Ubuntu 20.04

### Which AutoKey GUI did you use?

Both

### Which AutoKey version did you use?

0.95.10

### How did you install AutoKey?

I installed it from the Software app, which uses my distro and some custom repositories

### Can you briefly describe the issue?

Autokey freezes when trying to run keyboard.press_key

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. write "if keyboard.wait_for_keypress('c'):"
2. on the if result put "keyboard.press_key("e")"
3. play it and press c

### What should have happened?

It should have automatically pressed "e", i also had put a way of disabling with a toggle boolean

### What actually happened?

It freezed. i checked with different keys, adding a modifier and also erased the disabling part of the code, but it still freezes

### Do you have screenshots?

![Captura de pantalla de 2023-03-24 23-28-53](https://user-images.githubusercontent.com/114374887/227682166-e16e9466-14e4-479e-9316-86bf40117aad.png)
![Captura de pantalla de 2023-03-24 23-29-33](https://user-images.githubusercontent.com/114374887/227682167-f2807e39-609c-463f-984c-44c19c174016.png)

### Anything else?

I only know that its the keyboard.press_key command

**Comment by josephj11** [comment]
Let's unpack this a bit.

1. The main problem is a deficiency in the AutoKey API. Wait_for_keypress does not return a result (always succeeds), so you don't know if it ever got the desired keypress or just timed out after 10 seconds (default timeout). See #659.

There is a workaround for this that I don't see ATM: You set the optional timeout parameter to a reasonable value and record the time before issuing the API call. When the call returns, get the current time and subtract the starting time. If the result is roughly the same as the timeout parameter, then you know it timed out. If it's significantly less,  then you know the specified keypress was detected.

2. Your text mentions `c`, but your script uses `<ctrl>+c`. This may be fine, but a lot of things respond to that particular key sequence as sigint or copy to clipboard, so it would be better to (at least temporarily) use a different key sequence to see if that makes a difference.

3. AutoKey 0.95.10 is old. 0.96.0 has a lot of bug fixes and a few new features. I would highly suggest you upgrade if possible. [Source](https://github.com/autokey/autokey/releases/) Installation [Instructions](https://github.com/autokey/autokey/wiki/Installing).

Since you are using Ubuntu, a Debian derivative, you can upgrade the easy way by using the debs we provide.

There is a packaging issue with 0.96.0 that prevented it from being included in some distributions. We have fixed this, but haven't formally released it yet as 0.96.1.

IDK if upgrading will affect this issue, but if it doesn't, then the developers will know for sure that it still needs to be fixed.

4. It might help to run an AutoKey [trace](https://github.com/autokey/autokey/wiki/Troubleshooting#autokey-traceback) to see things from AutoKey's perspective. If it doesn't reveal the answer, it will help our developers analyse the issue.

5. I believe a number of other users use this API call. Since this is the first report of this particular problem, the first thing to look for/eliminate is something local to your system.

**Comment by Elliria** [comment]
I agree with @josephj11 that since `ctrl + c` is already used globally by the system as the shortcut for copying, so you might want to consider using a different key-combination.

That aside, though, there's an error in one line of the code. This line:
```
keyboard.key_press("e")
```
should be:
```
keyboard.press_key("e")
```
If you fix that and change the key-combination, that should take care of it.

Note that you might also want to put this line beneath that one so that the key is released afterwards:

```
keyboard.release_key("e")
```
Otherwise, AutoKey will happily leave it depressed and that may affect your other programs in unexpected ways.

**Comment by NicoReXDlol** [comment]
> Let's unpack this a bit.
> 
> 1. The main problem is a deficiency in the AutoKey API. Wait_for_keypress does not return a result (always succeeds), so you don't know if it ever got the desired keypress or just timed out after 10 seconds (default timeout). See [Add return codes to mouse.wait_for_click and keyboard.wait_for_keypress #659](https://github.com/autokey/autokey/issues/659).
> 
> There is a workaround for this that I don't see ATM: You set the optional timeout parameter to a reasonable value and record the time before issuing the API call. When the call returns, get the current time and subtract the starting time. If the result is roughly the same as the timeout parameter, then you know it timed out. If it's significantly less, then you know the specified keypress was detected.
> 
> 2. Your text mentions `c`, but your script uses `<ctrl>+c`. This may be fine, but a lot of things respond to that particular key sequence as sigint or copy to clipboard, so it would be better to (at least temporarily) use a different key sequence to see if that makes a difference.
> 3. AutoKey 0.95.10 is old. 0.96.0 has a lot of bug fixes and a few new features. I would highly suggest you upgrade if possible. [Source](https://github.com/autokey/autokey/releases/) Installation [Instructions](https://github.com/autokey/autokey/wiki/Installing).
> 
> Since you are using Ubuntu, a Debian derivative, you can upgrade the easy way by using the debs we provide.
> 
> There is a packaging issue with 0.96.0 that prevented it from being included in some distributions. We have fixed this, but haven't formally released it yet as 0.96.1.
> 
> IDK if upgrading will affect this issue, but if it doesn't, then the developers will know for sure that it still needs to be fixed.
> 
> 4. It might help to run an AutoKey [trace](https://github.com/autokey/autokey/wiki/Troubleshooting#autokey-traceback) to see things from AutoKey's perspective. If it doesn't reveal the answer, it will help our developers analyse the issue.
> 5. I believe a number of other users use this API call. Since this is the first report of this particular problem, the first thing to look for/eliminate is something local to your system.


> Let's unpack this a bit.
> 
> 1. The main problem is a deficiency in the AutoKey API. Wait_for_keypress does not return a result (always succeeds), so you don't know if it ever got the desired keypress or just timed out after 10 seconds (default timeout). See [Add return codes to mouse.wait_for_click and keyboard.wait_for_keypress #659](https://github.com/autokey/autokey/issues/659).
> 
> There is a workaround for this that I don't see ATM: You set the optional timeout parameter to a reasonable value and record the time before issuing the API call. When the call returns, get the current time and subtract the starting time. If the result is roughly the same as the timeout parameter, then you know it timed out. If it's significantly less, then you know the specified keypress was detected.
> 
> 2. Your text mentions `c`, but your script uses `<ctrl>+c`. This may be fine, but a lot of things respond to that particular key sequence as sigint or copy to clipboard, so it would be better to (at least temporarily) use a different key sequence to see if that makes a difference.
> 3. AutoKey 0.95.10 is old. 0.96.0 has a lot of bug fixes and a few new features. I would highly suggest you upgrade if possible. [Source](https://github.com/autokey/autokey/releases/) Installation [Instructions](https://github.com/autokey/autokey/wiki/Installing).
> 
> Since you are using Ubuntu, a Debian derivative, you can upgrade the easy way by using the debs we provide.
> 
> There is a packaging issue with 0.96.0 that prevented it from being included in some distributions. We have fixed this, but haven't formally released it yet as 0.96.1.
> 
> IDK if upgrading will affect this issue, but if it doesn't, then the developers will know for sure that it still needs to be fixed.
> 
> 4. It might help to run an AutoKey [trace](https://github.com/autokey/autokey/wiki/Troubleshooting#autokey-traceback) to see things from AutoKey's perspective. If it doesn't reveal the answer, it will help our developers analyse the issue.
> 5. I believe a number of other users use this API call. Since this is the first report of this particular problem, the first thing to look for/eliminate is something local to your system.

I will try this, i also had tried with only c, i added the ctrl modifier to see if that was the problem

**Comment by NicoReXDlol** [comment]
> I agree with @josephj11 that since `ctrl + c` is already used globally by the system as the shortcut for copying, so you might want to consider using a different key-combination.
> 
> That aside, though, there's an error in one line of the code. This line:
> 
> ```
> keyboard.key_press("e")
> ```
> 
> should be:
> 
> ```
> keyboard.press_key("e")
> ```
> 
> If you fix that and change the key-combination, that should take care of it.
> 
> Note that you might also want to put this line beneath that one so that the key is released afterwards:
> 
> ```
> keyboard.release_key("e")
> ```
> 
> Otherwise, AutoKey will happily leave it depressed and that may affect your other programs in unexpected ways.

But thats weird, it doesnt give an error of it not existen as a keyboard.key_press, in fact, the qt versiones gives it to me as keyboard.press_key

**Comment by NicoReXDlol** [comment]
![Captura de pantalla de 2023-03-25 18-03-00](https://user-images.githubusercontent.com/114374887/227742045-e92a7c07-7f49-40c6-8878-5efa353165a1.png)
So it made it work like this.
My issue on the full script (the one i showed is the one which causes the error, not the full script) was that i used not to turn True into False and False into True, since this is based off python, but it seems that in autokey not means False, no matter what

**Comment by josephj11** [comment]
Whatever you're trying to do, that code doesn't do it.

You set keypressed to false, so in the next test not keypressed will always be true, so it's effectively dead code. The rest of that test will always be true as well because wait_for_keypress is always true so that whole test reduces to if true with a delay of up to 10 seconds.

Likewise, the second test also resolves to if true with a similar delay.

BTW, AutoKey scripts are written and run in pure Python 3.x. There is no modification from standard Python behavior. The only thing AutoKey does is provide and expose its modules of API calls (which are also just Python with the occasional call to an external utility for window manipulation, dialog management, etc.).

Coding discussions really shouldn't be within issues. That's what our support forums are for. Come over to [Gitter](https://gitter.im/autokey/autokey) and we can go into whatever depth you like.

**Comment by josephj11** [comment]
> But thats weird, it doesnt give an error of it not existen as a keyboard.key_press, in fact, the qt versiones gives it to me as keyboard.press_key

That is weird. Can you elaborate on exactly what you see? I'm quite sure you can't call a nonexisent function without Python throwing an exception.

**Comment by Elliria** [comment]
> So it made it work like this. My issue on the full script (the one i showed is the one which causes the error, not the full script) was that i used not to turn True into False and False into True, since this is based off python, but it seems that in autokey not means False, no matter what

That script should not work for you. I just tried it and it created a race condition that I had to [REISUB](https://askubuntu.com/questions/926461/whats-the-difference-between-the-magic-reisub-reset-and-holding-down-the-power) my way out of, because it just kept pressing the **e** key over and over and over. I killed AutoKey and it started filling my text editor with **e**. I killed my text editor and the run box opened and started filling with **e**. I then did the **REISUB** and that restarted my computer, finally putting a stop to it. I have no idea how you're avoiding that at your end.

*Note that I was only able to kill AutoKey and the text editor because I have a shortcut to the **xkill** command on my panel with a bomb icon, so I was able to click that and bomb those programs without having to type anything. Typing would have been impossible.*

This works for me in AutoKey 0.95.10, sending one press of the **e** key when the **c** key is pressed:
```
keyboard.wait_for_keypress('c'):
keyboard.press_key("e")
keyboard.release_key("e")
```
This also works for me in AutoKey 0.95.10, sending one press of the **e** key when the **c** key is pressed:
```
if keyboard.wait_for_keypress('c'):
	keyboard.press_key("e")
	keyboard.release_key("e")
```

**Comment by Elliria** [comment]
> But thats weird, it doesnt give an error of it not existen as a keyboard.key_press, in fact, the qt versiones gives it to me as keyboard.press_key

This is also quite odd.

I get an exception when I try to run it with the wrong API call in GTK:

![GTKException](https://user-images.githubusercontent.com/25792925/227753694-6b6dc9fd-6267-4ea2-b83a-1f5aadeedec1.png)

I also get an exception when I try to run it with the wrong API call in Qt:

![QtException](https://user-images.githubusercontent.com/25792925/227753697-82de82e7-f598-4666-a074-de61998f4811.png)

Actually, you might be getting an error and not noticing it. I just get a tiny little pop-up in the bottom right corner of my screen. I then have to right-click the AutoKey tray icon and choose **View script error** from the context menu in order to see those errors above. It would be easy to miss that little pop-up.

I believe I either created or added to an issue in here with a wish for the errors to be "in your face" and on top of every other window instead of us having to go hunting for it.

**Comment by NicoReXDlol** [comment]
The thing is, it **ACTUALLY** worked, i have recently switched to windows and i really dont know what happened there. Maybe the download some solar radiation switched the bits to make this possible, but i still dont know wth was all of that

**Comment by NicoReXDlol** [comment]
> > But thats weird, it doesnt give an error of it not existen as a keyboard.key_press, in fact, the qt versiones gives it to me as keyboard.press_key
> 
> This is also quite odd.
> 
> I get an exception when I try to run it with the wrong API call in GTK:
> 
> ![GTKException](https://user-images.githubusercontent.com/25792925/227753694-6b6dc9fd-6267-4ea2-b83a-1f5aadeedec1.png)
> 
> I also get an exception when I try to run it with the wrong API call in Qt:
> 
> ![QtException](https://user-images.githubusercontent.com/25792925/227753697-82de82e7-f598-4666-a074-de61998f4811.png)
> 
> Actually, you might be getting an error and not noticing it. I just get a tiny little pop-up in the bottom right corner of my screen. I then have to right-click the AutoKey tray icon and choose **View script error** from the context menu in order to see those errors above. It would be easy to miss that little pop-up.
> 
> I believe I either created or added to an issue in here with a wish for the errors to be "in your face" and on top of every other window instead of us having to go hunting for it.

In fact, i checked there to see if my script worked. No errors.

**Comment by NicoReXDlol** [comment]
I think we must migrate this somewhere else fi we still want to talk about it, cause this aint an issue anymore.

**Comment by josephj11** [comment]
@Elliria The code for this is in the heart of AutoKey, so it doesn't matter which front end you use and I don't believe anything relevant has changed in quite a while, so the exact version of AutoKey (as long as it's fairly recent) shouldn't matter either.

I'm quite confused here. The OP appears to be successfully calling a nonexiting API function - which should only work if they wrote their own wrapper for the actual API function or imported the function using the 'as' argument to rename it. Neither of those special cases seems to have been coded by the OP.

I  think we need the full code for the script that is actually being run.

Something certainly doesn't add up.

**Comment by Elliria** [comment]
@NicoReXDlol, thank you for following up on this. Since your updated script worked as expected, this issue can be closed. Good luck in Windows, and if you come back to GNU/Linux, we'll be here.

**Comment by Elliria** [comment]
@josephj11, the different front-ends were for demonstration purposes to show that the error notification looks different depending on which one was used. Also, as far as I know, we had the full code.

At any rate, this is a non-issue. If you look at the issue-report screenshots at the top of the page, the original script had two issues, one of which caused the script not to run and the other of which would have caused an exception if the script had run.

This was the original code:
```python
if keyboard.wait_for_keypress('c', modifiers=['<ctrl>']):
	keyboard.key_press("e")
```
That script was doomed from the outset for these two reasons:
* The `<ctrl>+c` key-combination would have caused the script to not run at all since it's a default operating-system key-combination that would have been intercepted by the operating system so that AutoKey would never have received it. This is what the OP experienced and referred to as freezing.
* The `keyboard.key_press("e")` part was an invalid API call and would have thrown an exception if the script had run. The OP never saw the exception, because the script never ran.

When the OP changed the script, as you can see further down in this issue report, the script ran as expected. This is because the changed script used the `<ctrl>+2` key-combination, which isn't an operating-system default, so AutoKey received it and used it to run the script. The API call had also been corrected to `keyboard.press_key('e')`, so the key was pressed, as expected.

**Comment by josephj11** [comment]
@Elliria Thanks for unravelling this one.
