### ISSUE TITLE
<alt>+<tab> doesn't work

### ISSUE THREAD

**Issue by leonardofl** [autokey/autokey#84]
## Classification:

Bug

## Reproducibility:

Always

## Summary

`#keyboard.send_keys("<alt>+<tab>")` doesn't work on Ubuntu (Unit interface).

## Steps to Reproduce

Create a new script with the following content:

`keyboard.send_keys("<alt>+<tab>")`

Open Gedit, select a couple of lines and execute the script.

## Expected Results

Window should be changed.

## Actual Results

You got the select lines replaced by a "tab" and no window was changed.

`autokey-gtk --verbose` output:

`2017-06-20 13:27:16,257 DEBUG - interface - Send modified key: modifiers: [u'<alt>'] key: <tab>`

## Version

AutoKey (Qt) Version 0.90.4

Installed via: apt-get.

Distro:

Ubuntu 16.04, 64bits

**Comment by osama-h-rana** [comment]
Hi. 

Your summary says that the code is actually commented out with `#`. Maybe that is the problem?
Having said that, I'm unable to make alt+tab work on my PC as well.

**Comment by xircon** [comment]
Alt+tab is very likely to be "swallowed" by your desktop environment.

**Comment by samuelsimoes** [comment]
I tried it too, but without sucess too. :(

I even tried other combinations using press and release keys, but all without sucess.

**Comment by josephj11** [comment]
As @xircon says, there's a keystroke food chain and some key combinations never make it as far as AutoKey. In KDE Alt+Tab brings up a window switching list  without gedit ever seeing it.

Conversely, AutoKey speaks directly to the active window, so if you emit keystrokes intended to affect the desktop itself, they only do so if the application in the window honors them and produces the expected behavior.

There are also a number of applications, notably xterm, which do not honor synthetic keypresses (the way AutoKey works) and completely ignore them.

Using press and release keys with other API calls is tricky. If you go to [Gitter](https://gitter.im/autokey/autokey) and scroll back to March, 22, you'll see a discussion of this along with some working examples.

**Comment by asmith26** [comment]
Did anyone ever get this working? Thanks for any help :)

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @asmith26 .

This doesn't work because it's not the way AutoKey is designed. It talks directly to the active window, not to the DTE (desktop environment).

However, you can do such things in scripts by directly calling out to things like xdotool and wmctrl using subprocess().

I don't think we have any relevant examples, but if you ask over on [Gitter](https://gitter.im/autokey/autokey), we can work through it with you.

**Comment by josephj11** [comment]
Closing this as invalid/won't fix.
