### ISSUE TITLE
Error notification pops up regardless of notification settings

### ISSUE THREAD

**Issue by Celian-Butre** [autokey/autokey#891]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [X] user interface

### Which Linux distribution did you use?

Ubuntu 20.04

### Which AutoKey GUI did you use?

GTK

### Can you briefly describe the issue?

When the app is closed, and a script of mine encounters an error because of an exit() where and imported library wasn't ready for it (pynput) The notification that there is an error still appears even with all notifications both in app settings and in the notification settings on linux turned off.
I cannot get the notification to dissapear

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

close autokey
run a program with an error
get annoying notification

### What should have happened?

the notification should not have appeared since all notifications are off

### What actually happened?

the notification appeared

**Comment by josephj11** [comment]
I'm having a bit of difficulty understanding this issue.

By "the app is closed", I assume you mean that the AutoKey main menu is not being displayed, but that AutoKey itself is running in the background.

We need  to see the script itself (or something like it that recreates the issue without the rest of what you're doing) along with anything else we would need to do to recreate the issue.

(You can post it here using markdown to preserve the structure - Prefix your code with a blank line followed by a line that only has three backticks on it and end your code with a line that only has three backticks on it followed by a blank line.)

Since you're on a Debian-based distro, I assume you're using AutoKey 0.95.10. If that's not the case, we need to know which version you are running. (0.96.0 is our current release.)

Is this some sort of exception that you could catch and handle in a Python try: block?

Have you tried adding some delays with time.sleep() to give current operations more time to complete before the next step starts?

**Comment by Elliria** [comment]
Ah, yes. This is not a bug. AutoKey wasn't designed to do that. There's no setting in AutoKey to disable notifications. There's a setting to **Show a notification icon** that you can toggle on or off to determine whether there will be an icon in the system tray or not, but it won't stop AutoKey from notifying you when something goes wrong.

I was able to duplicate the circumstances you described by doing this:

**Steps**
1. Open AutoKey.
2. Open the **Edit** menu.
3. Choose **Preferences** from the menu.
4. Remove the check-mark from the **Show a notification icon** box.
5. Create this broken script:
   ```
   foo
   ```
6. Set a hotkey to run the script with.
7. Save the script.
8. Close the AutoKey main window, with AutoKey still running in the background.
9. Press the hotkey.

**Result:**
* I received the same notification I would normally get from AutoKey letting me know that something had gone wrong, but AutoKey also put its red icon (the one that indicates that something is wrong) into my system tray for me to click. I was able to use it normally to choose the **View script error** option from the context menu and see the error, and the icon was automatically removed from my system tray again by AutoKey, which I thought was a nice touch.

Since that's exactly the behavior that you don't want, this is worthy of becoming an enhancement (feature-request).

**Comment by josephj11** [comment]
@Elliria Based on your comment above, it looks like I should label this as invalid and the OP or I should close it. (an enhancement issue can still be opened if the OP desires - and can figure out exactly what the desired behavior should be). 

If it was added, it would probably have to be an optional feature because no one has complained about this before, so whatever notifications users are seeing are probably viewed as useful.

**Comment by Celian-Butre** [comment]
Thank you for all your hasty replies,
@Elliria has correctly understood my issue
If the app works in the intended way then I would suggest adding the possibility to suppress all notifications (or at least all error notifications) as some codes can be functional but trigger errors upon closing (at least when you are bodging stupid things like I am ;).
Thanks again for responding.

**Comment by josephj11** [comment]
@Celian-Butre If your script is failing, why don't you want to be notified of that? If there's a condition your script can't process successfully, it should still be able to detect the problem or avoid it somehow.

We're not Python experts, but we'll be glad to try to help with this.

**Comment by Celian-Butre** [comment]
The reason I didn't want the notification is the program (despite being broken) was working exactly like I wanted (the error appears when I did exit(), and I believe was triggered by pynput), but the notifications stopped it from being a pleasant experience, and as this wasn't meant to be very serious software, (after trying for a good amount of time and running into error messages about display connections terminating and other things far beyond my understanding) I was ready to content myself with a broken but working code
I don't know if that makes sense.

**Comment by josephj11** [comment]
That makes perfect sense. We've all been there.

If you're getting weird errors like that, it sounds like you're exit() is terminating more than just the thread your script is running in. In general, that shouldn't happen.

Does pynput open some sort of communications channel that it expects you to close when you're done using it?

The remaining questions are

what does pynput do that you can't do natively, etc. in AutoKey?

and does that package have a support forum, etc. where someone may have already solved this issue?

**Comment by Celian-Butre** [comment]
I just used pynput because I was more familiar with their documentation, but it's fine my program uses only autokey now and it works

**Comment by Elliria** [comment]
I'm glad you have it sorted out now, @Celian-Butre. If you ever have broken scripts again in the future, feel free to either create an [issue](https://github.com/autokey/autokey/issues) or a [discussion](https://github.com/autokey/autokey/discussions) on here. Very few people see the issues and discussions on here, though.

For a larger audience, you might want to try various platforms in our [community](https://github.com/autokey/autokey/wiki/Community), with [Gitter](https://github.com/autokey/autokey/wiki/Gitter) or [Google Groups](https://github.com/autokey/autokey/wiki/Google-Groups) probably being a good place to start when having code issues.
