### ISSUE TITLE
Autostart attempts two Autokey processes

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#894]
## Classification:
(Pick one: Bug, Crash/Hang/Data loss, Enhancement, Feature (new), Performance, UI/Usability)

Bug ?

## Reproducibility:
(Pick one: Always, Sometimes, Rarely, Unable, I didn't try)

Always

## AutoKey version:
(Paste in your AutoKey version and, if the problem is known to be present in more than one version, please list them all.)

96.0

## Used GUI:
(Pick one: Gtk, Qt, Both):

Qt in Kubuntu 22.04.2

## Installed via:
(Pick one: PPA, pip3, Git, package manager, etc.)

autokey-qt_0.96.0_all.deb

## Linux distribution:
(Provide information about your Linux distribution and its release or version number.)

Kubuntu 22.04.2 

## Summary:
(Provide a brief summary of the problem.)

Autokey-Qt is set to autostart, but attempts a 2nd process as well

## Steps to reproduce:
- I do this.
- login
- 
- Then I do that.
- Take a screenshot of the error.

## Expected result:
(Explain what should happen.)

## Actual result:
(Explain what actually happens.)

## Screenshot (if applicable):
(Include one or more screenshots of the issue by dragging the image file(s) here to help with debugging.)

## Verbose output (if applicable):
(Include the output from launching AutoKey via the `autokey-gtk --verbose` or `autokey-qt --verbose` command to help with debugging. Please upload the output somewhere accessible or paste it into a code block here, enclosing it in triple backticks.)
```
Example code block. Replace this with your output content.
```

## Notes:
(Describe debugging steps you've taken, a workaround you've figured out, or any other information you think we might need.)
![230722_kubuntu_autokey_on_login](https://github.com/autokey/autokey/assets/10367016/3ddd3196-4d1b-4506-b704-fffca9f00144)

**Comment by josephj11** [comment]
This is probably: (But see link at end of post)

This is expected behavior caused by incorrect local settings.

The first thing to try is to uncheck AutoKey Settings->Configure AutoKey->Automatically start AutoKey after login.

What is most likely happening is that your DTE is restoring your session when you log in (including starting AutoKey) and then the AutoKey.desktop file in your autostart folder is trying to start it again.

I think unchecking that box will get rid of the  AutoKey.desktop file.

Alternatively, you may find a list of applications to ignore when restoring your session. You can add AutoKey to that list and then leave the above box checked if you want to.

I know exactly how all this works in KDE, but I'm not sure for other DTEs.

This is another one that should be in our wiki somewhere.

See also

https://forums.linuxmint.com/viewtopic.php?t=241092 

at the bottom

I just noticed that you're on Ubuntu now, but I'm leaving the link there because you use Mint a lot and it might help anyway.

and try 

pkill autokey

and then start it again from the CLI so you see any messages that might be emitted.

autokey-qt &

**Comment by ineuw** [comment]
This is in KDE and Qt in Kubuntu 22.04.2.

**Comment by josephj11** [comment]
That's what I am running now and I do not have that issue. I do have the AutoKey startup option disabled.

**Comment by ineuw** [comment]
@josephj11, Thanks. The error is in Kubuntu autostart. I discovered it yesterday when adding Xfce-notes to autostart. The same in LMC produces no such error. I will report the issue.
