### ISSUE TITLE
phrases include the hotkey's printable characters in Remmina

### ISSUE THREAD

**Issue by nuno-andre** [autokey/autokey#918]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [X] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [X] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Kubuntu 22.04

### Which AutoKey GUI did you use?

Qt

### Which AutoKey version did you use?

0.95.10

### How did you install AutoKey?

apt

### Can you briefly describe the issue?

I've got a phrase whose hotkey is <kbd>Ctrl</kbd>+<kbd>Super</kbd>+<kbd>1</kbd>. When I type the shortcut in Remmina, the `1` is printed in front. I.e. if the phrase is _test_, _1test_ is printed.

This doesn't happen with other shortcuts (e.g. <kbd>Super</kbd>+<kbd>1</kbd> opens _System Settings_ but doesn't print anything in the console) and neither in other terminal emulators as Konsole or Yakuake.

### Can the issue be reproduced?

Always

**Comment by josephj11** [comment]
Welcome to the AutoKey community @nuno-andre !

Not sure if it will help with this particular issue, but you should consider upgrading to our current version, 0.96.0. It has lots of bug fixes and a few new features. You can find it [here](github.com/autokey/autokey/releases/) with installation instructions [here](https://github.com/autokey/autokey/wiki/Installing). Since you're running a Debian-based distro, you can install from our debs which makes it very easy.

Haven't seen Remmina before. It looks very powerful.

Ctrl+Super+1 sounds like a pretty safe hotkey choice, but have you tried using something else to see if the problem has anything to do with the specific hotkey or maybe something Remmina might be responding to.

**Comment by nuno-andre** [comment]
Hi @josephj11!

The latest Ubuntu repo version is 0.95, but I've installed the 0.96 from the .deb package and the error is gone.

Thank you!

> Haven't seen Remmina before. It looks very powerful.

It's an awesome tool if you need to access too many remote machines ;)

**Comment by nuno-andre** [comment]
Forgot to close the issue.

**Comment by josephj11** [comment]
We had a GitHub build issue that prevented a clean package build, so it didn't make it into Debian-based repos.

It's fixed, but we have to release 0.96.1 for them to see it and with a severe AutoKey developer shortage, that might be a while.
