### ISSUE TITLE
Jebus Cripes! I just want to install it! lol

### ISSUE THREAD

**Issue by YouveGotMeowxy** [autokey/autokey#938]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Unknown

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

UI/Usability

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [X] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Debian based. Kali, Ubuntu, Parrot, etc.

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

LORT HAVE MERCY!

I'm setting up a bash script to install AK; I'm looking over the Installation page, and my head is SPINNING.

I simply want to install the very latest version, with the built-in ability to keep it updated, just as one might do by using apt, but it's telling me to install a hundred dependencies this way and that way, and only this way if I want that, and that way if I want this, but be careful because if you do a dependency wrong it could blow up your python installation, yada yada yada.

The latest in the Releases area is from 2 years(!) ago, which would mean I need to curl/wget the 2 year old package, hard code in the version number, run dpkg, yada yada, and then figure out some way to keep it updated if a new one hits the releases page after any number of years, BUT the commits seems to say the source is newer, so THAT means I have to figure out all the python/pip/dependancies/yada stuff.

I mean... WOW. lol.

Maybe it actually isn't all that difficult, but after reading the installation page it's impossible to tell. I mean, even this form here to post the question has 50 fields to fill out.

### Can the issue be reproduced?

None

### What are the steps to reproduce the issue?

1. Visit this repo, all excited to install a cool app.
2. Read the main page that links to the install page
3. start reading the install page
4. visit the Releases page; notice the latest is 2 years old
5. go back to the install page looking for how to install the latest greatest version with built-in ability to keep it updated from the source code.
6. Keep reading
7. Keep reading
8. keep reading
9. Keep reading
10. Yell "Eff this sht!", and go lay down because your head is spinning and you just spent the only hour you had to spend on the computer reading the docs and still getting nowhere, and now you're dizzy and exhausted, and used up your computer time.
11. Come back a few hours later and rant here, hoping the constructive criticism will lead to improvements and streamlining the process. :)

### What should have happened?

Why can't there just be a simple apt package like most other apps?

`sudo apt install AutoHotkey`
And down the road `sudo apt upgrade -y`

Ahhhhhh, so simple and convenient. Refreshing! ;)

### What actually happened?

Gave up.

### Anything else?

Sorry for the rant! But ...... YEOW! :)

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @YouveGotMeowxy !

Sorry you found our documentation so confusing!

This is a support issue which would better be addressed on [Gitter](https://gitter.im/autokey/autokey).

But, since you're already here:

Writing good documentation is hard. Sometimes it can be more challenging than coding the application itself. We have put a lot of effort into improving our [wiki](https://github.com/autokey/autokey/wiki/) over the last few years and are always open to making it better.

First, let's get you installed.

Installing on a Debian based system is very easy.

You get the [debs](github.com/autokey/autokey/releases/) here and follow these [instructions](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives).

Use the Debian section. Note that you should install the common code and one or both of the front ends in one dpkg command as shown. The front ends depend on the common package, so installing them separately is harder.

Once that's done, I wouldn't bother with a bash script. etc. for updates because, until we get some developers, there won't be any. If you know any Python developers, please send them our way!

Once we have developers, there will be a new maintenance release fairly soon that fixes some very minor problems that broke things that distro packagers care about and prevented 0.96.0 from getting added to the official Debian repositories. That sort of stuff is pretty much all that is new in the trunk branch. The rest goes into our develop branch which is not intended to be used by non-developers.

With that fixed, any new releases will be able to be updated in your distro and will update like everything else. This process takes a while since the packagers don't start until sometime after we make a release. If you don't want to wait, you can just use the links above to DIY.

If you have any specific suggestions as to how our documentation could be better, you can open one or more documentation issues or contribute directly to our [wiki](https://github.com/autokey/autokey/wiki/).

**Comment by YouveGotMeowxy** [comment]
@josephj11 

Thanks for not taking it personally, lol.

I see this kinda thing all too much, and it absolutely drives me _nuts_ when wanting to zip through something but get all caught up in minutiae that just chews up time and brain cycles, and I was already in a cranky mood, lol.

I did get it going after a bunch of time and some burnout, lol. I told myself at the time "well, looks like I'll just use the 2 year old version for now and maybe figure out getting the latest version instead, down the road".

One thing to mention about the .deb procedure you mentioned; it's a full-on requirement to follow-up with: `sudo apt --fix-broken install` or it won't run. At least on a brand spanking new pure Debian system (tested with WSL Debian 10).

I dunno, maybe a TL;DR section or something? **shrug**

If it helps at all (or maybe a future reader); this is the script I came up with (note this is just it's respective portion of a Case statement:

```
        "AutoKey")

            # TODO: Would be nice to also auto-populate my already made phrases into it. Chezmoi?
            # Ref:  https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives

            echo
            echo -e "${YELLOW}+ --- INSTALLING (Step 1): ${app_name}. ${ITALIC}(fetching packages).${RESET}"
            echo

            # Fetch packages
            wget https://github.com/autokey/autokey/releases/download/v${AutoKey_VERSION}/autokey-common_${AutoKey_VERSION}_all.deb
            wget https://github.com/autokey/autokey/releases/download/v${AutoKey_VERSION}/autokey-${AutoKey_GUI}_${AutoKey_VERSION}_all.deb

            # To be a solid dev, should confirm they exist/downloaded ok, but for now, nah.

            echo -e "${YELLOW}+ --- INSTALLING (Step 2): ${app_name}. ${ITALIC}(expect some dependency errors; they'll be fixed next).${RESET}"
            echo

            # Install both .deb's
            sudo dpkg --install autokey-common_${AutoKey_VERSION}_all.deb autokey-${AutoKey_GUI}_${AutoKey_VERSION}_all.deb

            echo
            echo -e "${YELLOW}+ --- INSTALLING (Step 3): ${app_name}. ${ITALIC}(fixing dependency errors).${RESET}"
            echo

            # The above install is basically *designed* to spit out a dependency error,
            # with the following line *designed* to fix it all up. Weird.
            sudo apt --fix-broken install -y

            echo
            echo -e "${YELLOW}+ --- INSTALLING (Step 4): ${app_name}. ${ITALIC}(cleaning up).${RESET}"
            echo

            # Cleanup the downloaded .deb's
            sudo rm -rf autokey-common_${AutoKey_VERSION}_all.deb autokey-${AutoKey_GUI}_${AutoKey_VERSION}_all.deb

            echo -e "${GREEN}+ --- INSTALLING: ${app_name} Done!${RESET}"
            ;;
```

**Comment by josephj11** [comment]
We all get frustrated!

Based on very long experience, if you don't like occasionally slogging through some minutiae, Linux is not the best OS. It's orders of magnitude better than it was when I first used it, but I got stuck on something annoying a few minutes ago.

Dpkg is the level below apt. It only addresses one package at a time. That's great if you're doing low level work. But it does not try to install dependencies, etc. That's better left to apt which is very good at it. However, you have to convince apt to look at local packages that are not in a repository it knows about, so for initial installs, dpkg is easier.

When you use dpkg to upgrade an existing/previous AutoKey install, the dependencies are usually all already there, so it just works.

Throwing terminal color strings into (global) bash variables it a nice touch. I may play with that. The problem is that you can't (easily/reliably) have them work if you put them in .bashrc because they won't be there for any script launched from a non-interactive shell (the annoyance I was just dealing with). You have to put them somewhere else and source them...

It's a matter of taste, but as long as you're already using echo -e, you could surround your messages with newlines `\n` and get rid of those other echos.

BTW, some people might find scripts such as yours helpful, but they are unlikely to find them here, especially once the issue is closed. That's what our wiki is for. Anyone with a GitHub account can contribute to it. If you do, I would either add a few FIXME: tags or some defensive code to make sure things worked before proceeding to the next step.

On that note, it seems like this issue is resolved. If so, please close it.

**Comment by YouveGotMeowxy** [comment]
> Throwing terminal color strings into (global) bash variables it a nice touch. I may play with that. The problem is that you can't (easily/reliably) have them work if you put them in .bashrc because they won't be there for any script launched from a non-interactive shell (the annoyance I was just dealing with). You have to put them somewhere else and source them...

Those colors/vars are just in the install.sh script. I didn't put them in my .bashrc. :)

Admittedly I'm a windows first user, and only so-so w/linux, but I'm assuming any global vars I create in a .sh script go away once the script ends.

> It's a matter of taste, but as long as you're already using echo -e, you could surround your messages with newlines `\n` and get rid of those other echos.

THAT is a good idea! I think I will do that. Surprised that didn't even occur to me while creating it, lol. Seems like it has the exact same effect(?) but cleaner looking code.

> BTW, some people might find scripts such as yours helpful, but they are unlikely to find them here, especially once the issue is closed. That's what our wiki is for. Anyone with a GitHub account can contribute to it. If you do, I would either add a few FIXME: tags or some defensive code to make sure things worked before proceeding to the next step.

If you want to tweak that code and add it to your wiki, please feel free. :)

thanks for the help! :)

**Comment by josephj11** [comment]
Yep. Variables are context dependent and go away when the context goes away. You have to take various special steps to preserve them. I have never had WSL. It didn't come with the cheap/preinstalled versions of Windows I used long ago.

AFAIK, there's also no generic install.sh on regular Linux, but creating one, etc. is pretty easy.

Feel free to join us on our [forum](https://groups.google.com/forum/#!forum/autokey-users) and/or on [Gitter](https://gitter.im/autokey/autokey) to discuss anything AutoKey-related.
