### ISSUE TITLE
Fedora doesn't allow setting key

### ISSUE THREAD

**Issue by topper68** [autokey/autokey#942]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Wayland

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Fedora 39

### Which AutoKey GUI did you use?

GTK

### How did you install AutoKey?

Installed with dnf

### Can you briefly describe the issue?

I had previously been using it in Ubuntu without issue, but I migrated to Fedora and I have a strange issue.

When I try to set a hotkey for a script I am not able to type a key.

I click on the set button for the script, click on the press to set button, and when it says press a key and I type nothing happens at all!

any suggestions are appreciated

### Can the issue be reproduced?

Always

**Comment by josephj11** [comment]
I'm going to detail this step by step, so you can tell me exactly where it fails for you.
Try to follow these **_exact_** steps on one of your actions. You can Clear the hotkey right after you make sure it works, so if  you don't want a hotkey or that hotkey on your action, you can undo it easily.
It's important that you do these steps exactly because I'm not there looking over your shoulder to see what you did differently.

- Click on an action in the navigation panel to the left in the AutoKey main window
- The right panel displays the settings (metadata) for that action
       Most of the way down on the right, you see a line that looks like this (only spaced out)
       Hotkey:  (none configured)  Set Clear
- On that line, click on Set
- A Set Hotkey dialog pops up
        There are six modifier key buttons
        Below them it says
        Key: (none) Record a key combination
- click on Record a key combination
        The Control modifier button becomes highlighted (for no good reason) and, below it, the phrase
        Press a key or combination... appears and Record a key combination becomes grayed out
- Press a key combination (all keys at once and then release them), e.g. Ctrl Alt F
        The selected modifier buttons become highlighted and below them, it says
        Key: f
- Click on the OK button to the right to actually set the hotkey
        The pop-up dialog closes and in the right panel, you see
        ` Hotkey: <alt>+<ctrl>+f   Set Clear`
-Click on Save in the main toolbar near the upper left of the main window to save this and any other pending changes
         The Save button becomes disabled (grayed out) because there are no pending changes to save
- Click on a test window (where the successful operation of your action will be easily observed - like a text editor text editing panel open for editing with nothing important in it) and press the `<alt><ctrl>f` keys simultaneously 
          (you can press the modifier keys one at a time without releasing them and then press the f key)
-  Release all the hotkey keys
- Your action should now run

Now, tell me what happened.

**Comment by topper68** [comment]
When I click on Set for Hotkey I do get the Set Hotkey Window.

And then when I click on the button Press To Set the text changes from Key (none) to Press a key ...

But no key presses register at that point.


Here is a loom video to demonstrate:
https://www.loom.com/share/d9e41e6b64c64217bc3bd6fdd2e9d034

**Comment by topper68** [comment]
Just an update, I switched to Plasma (X11) and this works fine.

**Comment by josephj11** [comment]
Good. Nothing is supposed to work in Wayland. A few things do, but we don't care until we can support it with a reasonable subset of what AutoKey can do now.

X11 good. Wayland bad. LOL (for us)

You can close this issue now.
