### ISSUE TITLE
Add a way to go to the start of a line. It's possible to the end with keyboard.send_key("<end>") but seems not to have a start equivalent

### ISSUE THREAD

**Issue by ticketapp** [autokey/autokey#943]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Unknown

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [x] scripting
- [ ] technical debt
- [ ] user interface

### Which AutoKey GUI did you use?

None

### Can the issue be reproduced?

None

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @ticketapp !

Have you tried `keyboard.send_keys("<home>")` ?

See this article about [AutoKey Special Keys](https://github.com/autokey/autokey/wiki/Special-Keys)

If the above solves this issue for you, please close this issue.

If not, please post back here and fill in the above requested information so we know more about your setup. It will save a lot of time.

Joe

-----

Unrelated: I took a look at your GitHub page and you appear to be familiar with Docker (I'm not).

If it interests you, I would like your opinion on what impact Docker might have for AutoKey.

The central problem we are currently facing is that AutoKey is an X11 application and X11 is being replaced by Wayland.

Could AutoKey be packaged in a container of some sort along with X11 so it would work on systems running Wayland?

I appreciate that actually implementing something like this would probably require substantial effort. At this point, I primarily want to know if this makes any sense at all.

For some further details, see Discussion #866 and PR #844.

-----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

New users are encouraged to spend some time browsing through our [wiki](https://github.com/autokey/autokey/wiki). There are a number of helpful articles there as well as many example AutoKey scripts.

**Comment by ticketapp** [comment]
It works, thank you very much. I'll use the list or Gitter next time, noted!

For the docker question, I'm sorry I'm unfortunately not enough skilled with it to answer your question correctly. It could help you but for this king of app, I think you would also face other new problems, so I'm not sure you would decrease the developing time...
