### ISSUE TITLE
Wayland support now possible I believe

### ISSUE THREAD

**Issue by mercifulboss** [autokey/autokey#956]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Wayland

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

None

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [X] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Arch Linux 

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

Linux severely lacks a Wayland compatible AHK replacement. However I believe it is now possible to make this work with Wayland at least partially - the text expander ‘espanso’ works in Wayland via “xdg-desktop-portal” and by setting itself as a systemd service. Perhaps something similar can be done here?

### Can the issue be reproduced?

None

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @mercifulboss !

Thanks. We are aware of Espanso, but have not investigated it much or communicated with them.
See #775 . I think a few of our users also use it.

This should be a discussion rather than an issue, or, better yet, discussed on [Gitter](https://gitter.im/autokey/autokey)
where most of our knowledgeable users hang out. Only a few users see anything posted here on GitHub.

Please see #866 and #844 . (and all the way back to #87 ). This was already started and partially achieved by a former developer. We need someone who knows enough to pursue it further. We have never had any Wayland expertise.

Currently, we have no active developers, so if you know anyone who might be interested, please send them our way! There are a couple of OGs still lurking here who might be able to help someone new get started, so they wouldn't have to start totally cold.

Feel free to join our discussions on this topic and any others that interest you.

I'm closing this because it's a duplicate, but not from lack of interest...
