### ISSUE TITLE
need a programmatic way to en/dis-able monitoring

### ISSUE THREAD

**Issue by kstillson** [autokey/autokey#957]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [X] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Devuan GNU/Linux 5 (daedalus)

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.95.10-2.1

### How did you install AutoKey?

Devuan repo (Debian stable derived)

### Can you briefly describe the issue?

[Issue 249](https://github.com/autokey/autokey/issues/249) is a real security problem for me.  As a workaround, I figured I'd modify the auto-key script  I usually lock my screen with, by adding a Python API call to disable auto-key expansion (i.e. "monitoring").

However, there doesn't seem to be an API call to toggle expansion.  :-(  

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. Read entire [API documentation](https://autokey.github.io/api.html)
2. Be disappointed that there doesn't appear to be a way to do it.

### Anything else?

The "special hotkeys" configurable in preferences seem to provide this functionality, so there must be an internal API call for this..  Is it as simple as exposing that to the user-callable function set?  Or is it perhaps already exposed and this is just a documentation issue...?  :-)

**Comment by josephj11** [comment]
Welcome to the AutoKey community, Ken!TL;DR: it ain't pretty, but if you need this badly enough, there are a couple of hacks that might work.I can't research this immediately, but IIRC, there's a monitoring flag in $HOME/.config/autokey/.autokey.json.I suspect that if you terminate AutoKey (pkill AutoKey), manually reset that flag (with sed, etc.) and then restart AutoKey, that may do what you want - and the same for setting it on. (This could be done with a shell script...) You can try this by hand first to see if it works.You might also be able to turn it off using an AutoKey script that does it with the mouse. The reverse won't work because then AutoKey isn't running. However, you could use xdotool instead for this approach.The hard part is finding the coordinates of the AutoKey icon in your panel. That might not always be in the exact same location.You can solve that by using visgrep from Xautomation (called externally - our API call is probably broken) to search for it on the screen.In a day or two, I may have time to research this further to see if there's a better way.If you would like assistance working through these options (or to discuss anything else AutoKey related), you can join us over on Gitter https://gitter.im/autoKey/autokey (I think that's the link. I'm on my phone now.) in addition to posting here.Sent from my Galaxy
-------- Original message --------From: Ken ***@***.***> Date: 9/6/24  3:55 PM  (GMT-05:00) To: autokey/autokey ***@***.***> Cc: Subscribed ***@***.***> Subject: [autokey/autokey] need a programmatic way to en/dis-able monitoring (Issue #957) 
AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?
Xorg
Has this issue already been reported?

 I have searched through the existing issues.

Is this a question rather than an issue?

 This is not a question.

What type of issue is this?
Enhancement
Choose one or more terms that describe this issue:

 autokey triggers
 autokey-gtk
 autokey-qt
 beta
 bug
 critical
 development
 documentation
 enhancement
 installation/configuration
 phrase expansion
 scripting
 technical debt
 user interface

Other terms that describe this issue if not provided above:
No response
Which Linux distribution did you use?
Devuan GNU/Linux 5 (daedalus)
Which AutoKey GUI did you use?
GTK
Which AutoKey version did you use?
0.95.10-2.1
How did you install AutoKey?
Devuan repo (Debian stable derived)
Can you briefly describe the issue?
Issue 249 is a real security problem for me.  As a workaround, I figured I'd modify the auto-key script  I usually lock my screen with, by adding a Python API call to disable auto-key expansion (i.e. "monitoring").
However, there doesn't seem to be an API call to toggle expansion.  :-(
Can the issue be reproduced?
Always
What are the steps to reproduce the issue?

Read entire API documentation
Be disappointed that there doesn't appear to be a way to do it.

What should have happened?
No response
What actually happened?
No response
Do you have screenshots?
No response
Can you provide the output of the AutoKey command?
No response
Anything else?
The "special hotkeys" configurable in preferences seem to provide this functionality, so there must be an internal API call for this..  Is it as simple as exposing that to the user-callable function set?  Or is it perhaps already exposed and this is just a documentation issue...?  :-)

**Comment by josephj11** [comment]
Just looked at the issue you linked to and thought of another kludge. If you define an AutoKey global variable called something like enable, you could set it to a value false in one script assigned to a hotkey. Then, you could get that variable in any script that has adverse consequences and have it exit if it's false. Then, you could have another script with no triggers, but set to run from the AutoKey icon context menu to set that variable to true. This wouldn't affect phrases (without heroic measures), but it would get the scripts.Sent from my Galaxy
-------- Original message --------From: Ken ***@***.***> Date: 9/6/24  3:55 PM  (GMT-05:00) To: autokey/autokey ***@***.***> Cc: Subscribed ***@***.***> Subject: [autokey/autokey] need a programmatic way to en/dis-able monitoring (Issue #957) 
AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?
Xorg
Has this issue already been reported?

 I have searched through the existing issues.

Is this a question rather than an issue?

 This is not a question.

What type of issue is this?
Enhancement
Choose one or more terms that describe this issue:

 autokey triggers
 autokey-gtk
 autokey-qt
 beta
 bug
 critical
 development
 documentation
 enhancement
 installation/configuration
 phrase expansion
 scripting
 technical debt
 user interface

Other terms that describe this issue if not provided above:
No response
Which Linux distribution did you use?
Devuan GNU/Linux 5 (daedalus)
Which AutoKey GUI did you use?
GTK
Which AutoKey version did you use?
0.95.10-2.1
How did you install AutoKey?
Devuan repo (Debian stable derived)
Can you briefly describe the issue?
Issue 249 is a real security problem for me.  As a workaround, I figured I'd modify the auto-key script  I usually lock my screen with, by adding a Python API call to disable auto-key expansion (i.e. "monitoring").
However, there doesn't seem to be an API call to toggle expansion.  :-(
Can the issue be reproduced?
Always
What are the steps to reproduce the issue?

Read entire API documentation
Be disappointed that there doesn't appear to be a way to do it.

What should have happened?
No response
What actually happened?
No response
Do you have screenshots?
No response
Can you provide the output of the AutoKey command?
No response
Anything else?
The "special hotkeys" configurable in preferences seem to provide this functionality, so there must be an internal API call for this..  Is it as simple as exposing that to the user-callable function set?  Or is it perhaps already exposed and this is just a documentation issue...?  :-)

**Comment by kstillson** [comment]
Hi Joe--

trying to click on icons in the tray using xdotool sounds awful, but your
2nd idea made me think...

I believe I can detect whether the screen is locked by looking at the popen
response for:
   dbus-send --session --dest=org.freedesktop.ScreenSaver
--type=method_call --print-reply /org/freedesktop/ScreenSaver
org.freedesktop.ScreenSaver.GetActive

So I can just add a guard function at the top of all my scripts that
shouldn't work when the screen is locked..  That's not too much of a
kludge..  It's a bit of a shame that it's necessary, but certainly better
than leaving a security issue unresolved...

I agree it doesn't help with phrase expansion, but I'm not worried about
that, as even if the expansion worked (which, btw, it doesn't seem to), I
believe it would expand into the lock-screen prompt, not the underlying
window(s).  So it could cause confusion (if real or attempted passwords
contain an abbreviation trigger), and possibly enables poor judgement if
someone decides to put their password into an auto-phrase..  But arguably
saving people from poor judgement is slightly out of scope for autokey..
:-D

Anyway- thanks!  I'll try writing up the guard-function approach and
confirm it resolves my immediate concern.

If I get that working, do you think I should close FR #957, or leave it
around in hopes of an eventual more elegant solution from the internal
API...?

Thanks again!!  Best regards,

  - Ken

**Comment by kstillson** [comment]
I dug around in the source-code a bit, and I believe I actually found a solution...  The scripting environment has an instance of the class "Clipboard" named "clipboard", and that has an instance of class "Application" named "app"...   so:

clipboard.app.pause_service()
clipboard.app.toggle_service()
clipboard.app.unpause_service()

all seem to work without even needing to import anything.
So looks like I can do what I need without any kluding around.   :-)

**Comment by josephj11** [comment]
Great. Once it is proven to work, it would be good if you would contribute an example or two to our wiki for others to ***@***.*** what do you think about adding these "internal" functions to the API docs by adding the appropriate comments into the source code?Sent from my Galaxy
-------- Original message --------From: Ken ***@***.***> Date: 9/6/24  7:12 PM  (GMT-05:00) To: autokey/autokey ***@***.***> Cc: Joe ***@***.***>, Comment ***@***.***> Subject: Re: [autokey/autokey] need a programmatic way to en/dis-able monitoring (Issue #957) 
I dug around in the source-code a bit, and I believe I actually found a solution...  The scripting environment has an instance of the class "Clipboard" named "clipboard", and that has an instance of class "Application" named "app"...   so:
clipboard.app.pause_service()
clipboard.app.toggle_service()
clipboard.app.unpause_service()
all seem to work without even needing to import anything.
So looks like I can do what I need without any kluding around.   :-)

**Comment by kstillson** [comment]
Made a few additions to the Wiki, adding some example scripts for disabling from AutoKey and then re-enabling via DBus.  

Also added a block to the script debugging section on how to use an external program to display Python script state for old-style printf-debugging, which I found useful for figuring all this stuff out.

**Comment by josephj11** [comment]
Great! Thank you. My computers are temporarily offline. As soon as I get them going again , I'll take a look.Sent from my Galaxy
-------- Original message --------From: Ken ***@***.***> Date: 9/8/24  1:10 PM  (GMT-05:00) To: autokey/autokey ***@***.***> Cc: Joe ***@***.***>, Comment ***@***.***> Subject: Re: [autokey/autokey] need a programmatic way to en/dis-able monitoring (Issue #957) 
Made a few additions to the Wiki, adding some example scripts for disabling from AutoKey and then re-enabling via DBus.
Also added a block to the script debugging section on how to use an external program to display Python script state for old-style printf-debugging, which I found useful for figuring all this stuff out.

**Comment by Elliria** [comment]
It looks good and you [added it to the wiki perfectly](https://github.com/autokey/autokey/wiki/Advanced-Scripts#programmatically-toggle-autokey-service).

If you'd like a pure AutoKey way to do all of the toggling, AutoKey comes with the ```autokey-run``` command-line execution utility. With that, you can run any phrase or script by using the ```-p```  or ```-s``` option.

So, if you had, for example, the **pause** AutoKey script that toggles monitoring off, instead of using DBus to toggle monitoring on again, you could make the **unpause** AutoKey script. Then, if monitoring is off, this command in a terminal window would toggle it on again:
```python
autokey-run -s "unpause"
```

**Comment by josephj11** [comment]
That's a good idea. I haven't used that, so I don't usually think of it.Sent from my Galaxy
-------- Original message --------From: Elliria ***@***.***> Date: 9/8/24  2:33 PM  (GMT-05:00) To: autokey/autokey ***@***.***> Cc: Joe ***@***.***>, Comment ***@***.***> Subject: Re: [autokey/autokey] need a programmatic way to en/dis-able monitoring (Issue #957) 
It looks good and you added it to the wiki perfectly.
If you'd like a pure AutoKey way to do all of the toggling, AutoKey comes with the autokey-run command-line execution utility. With that, you can run any phrase or script by using the -p  or -s option.
So, if you had, for example, the pause AutoKey script that toggles monitoring off, instead of using DBus to toggle monitoring on again, you could make the unpause AutoKey script. Then, if monitoring is off, this command in a terminal window would toggle it on again:
autokey-run -s "unpause"

**Comment by kstillson** [comment]
<ken basks in Elliria's praise. :-) >

Thanks- I didn't know about autokey-run.  I added that as "the easiest way
to do it...", but left in the stuff about dbus, as I can imagine edge cases
where knowing about the dbus interface could be useful for folks.

much happiness...

  - Ken

**Comment by Elliria** [comment]
It looks good, although it might be easier for new users to work with if each command is in its own code-block. Also, removing the leading dollar signs from the commands would prevent new users who don't know not to type those from getting the ```$: command not found``` error instead of the desired result.

The `dbus` commands are fascinating. I had no idea we could use `dbus` in that way. That's another note that's getting added to my personal wiki and will be explored further, not just for AutoKey, but also for other system services.

**Comment by kstillson** [comment]
great suggestions- done.. thx..

btw- there's a wonderful package called "d-feet" that provides a GUI
interface to DBus- you can search, explore via hierarchy, and even try
calling methods from the UI.  Very handy for cases like this where you
know/suspect there's a DBus interface, and want to see what your options
are...

  - Ken

**Comment by Elliria** [comment]
Thanks. It looks like [D-Feet is no longer maintained](https://wiki.gnome.org/Apps/DFeet) and [has been replaced with D-Spy](https://apps.gnome.org/Dspy/), but only the **D-Feet** package is in the Ubuntu repositories, so that's what I'd use. Would I just type `autokey` into its search box to find all the ways I can access AutoKey via D-Bus?

**Comment by kstillson** [comment]
at least in my version, first you select "session bus" (as autokey is a
user thing, not a system thing), then you can search for autokey, and it
should find "org.autokey.Service".  From that, expand the possible object
paths on the right panel, and you'll quickly see that "/AppService" is the
interesting area.  Double click on an individual method to bring up its
signature and the dialog where you can try giving it arguments and
executing it.  :-)

  - Ken

**Comment by Elliria** [comment]
Perfect - thank you so much. I've added those steps to my personal wiki as well.
