### ISSUE TITLE
Autokey latest release (Jun 6, 2022) 0.96.0 binary (deb) discrepent version

### ISSUE THREAD

**Issue by Bigfootmech** [autokey/autokey#959]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Unknown

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [X] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Kubuntu

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

Error.

### How did you install AutoKey?

https://github.com/autokey/autokey/releases/tag/v0.96.0
Downloading the common and gtk .deb files

### Can you briefly describe the issue?

When installed, trying to version in console
autokey --version 
returns autokey Version 0.96.0
autokey-gtk --version
returns autokey-gtk Version 0.96.0

but 

running either, and having the program open up
help -> About Autokey
shows 0.95.10

And the latest mouse movement commands don't work (say they don't exist on mouse)

### Can the issue be reproduced?

None

### What are the steps to reproduce the issue?

1. Download 0.96.0 binaries from github repo
2. double click file
3. follow through installation
4. launch autokey
5. open Help -> About
6. Try to write a script including
`mouse.move_relative_self(50,50)`

### What should have happened?

shows version 0.96.0
mouse moves

### What actually happened?

shows version 0.95.10
script throws error, that move_relative_self does not exist on mouse

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #959</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Bigfootmech</code> (replace <code>20</code> with the amount, and <code>@Bigfootmech</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by Elliria** [comment]
Just curious, but did you already have AutoKey 0.95.10 installed on the system when you installed 0.96.0? The behavior you describe is just like what I experience when I clone AutoKey and forget to run a very specific command to ensure that I'm running the cloned copy instead of the installed copy.

**Comment by josephj11** [comment]
I was going to say almost the same thing. Did you uninstall/purge any previous version before installing the new one?

Unless you're just testing using the zero install method, we always recommend starting with a clean slate. If you do this, first make sure to backup all your actions (everything under `$HOME/.config/data/` (being sure to get all hidden files if you are running any version lower than 0.96.0).

I did a little inconclusive testing on my system that didn't recreate the problem.

**Comment by Bigfootmech** [comment]
I am new to linux, so if you guys can't reproduce it, it might well be a fault on my end.

I had installed AutoKey through Discover (Kubuntu), and then uninstalled it the same way (seemed uninstalled).

How would I go about purging it?

**Comment by josephj11** [comment]
@Bigfootmech IDK how to do that in Discover.
In Muon, there's an action dropdown on an installed package that includes a Purge option. Apt also has a purge flag.
I don't think either will work on a package which has already been removed.

Assuming you've already backed up your actions (phrases and scripts) elsewhere, I'd start by running

```
rm -rf "$HOME/.config/autokey"
```

and then do an install.
That should get rid of most things. IDK what if any other more system level things might be left behind by a normal uninstall.

I might first do a

```
cd "$HOME"
grep -r '0.95.10'  *
```

to see if I could find the offending file.
If that produces too many error messages, you change the grep to

```
grep -r '0.95.10'  * 2>/dev/null
```

**Comment by Elliria** [comment]
Since you mentioned being new to Linux, I thought I'd add some detailed steps for backing up AutoKey and purging it from your system.

### Back up AutoKey
Before you begin, although the following instructions are unlikely to remove your AutoKey data, it's always a good idea to back up your data. You can do that in Dolphin or on the command-line.

**Back up AutoKey using Dolphin:**
1. Open Dolphin.
2. If you're not in your Home directory, click the little house icon in the toolbar or press Ctrl+H.
3. Left-cick the **View** menu.
4. Make sure there's a check in the "Show hidden files" box.
5. Double-click on the `.config` directory to open it.
6. Right-click the `autokey` directory.
7. Choose **Copy** from the context menu.
8. Browse to the location where you'd like to put your backup.
9. Left-click the **Edit** menu.
10. Choose **Paste clipboard contents...** from the context menu.

**Back up AutoKey using Konsole:**
1. Open Konsole.
2. Type or paste this command into the Konsole window, replacing `$HOME/Desktop/autokey` with the location where you'd like to put your backup (the example puts it onto your desktop):
   ```python
   cp -a "$HOME/.config/autokey" "$HOME/Desktop/autokey-backup"
   ```

### Purge AutoKey
**Purge AutoKey with Discover:**
I'm pretty sure that the **Mark for Purge** option in **Discover** will only work if the package is installed, but I suppose you could reinstall AutoKey with **Discover** and then purge it with **Discover**.

**Purge AutoKey on the command-line:**
As an alternative, purging can also be done on the command-line in a terminal window. If the package isn't installed, this will remove any configuration files that are associated with it. If the package is installed, this will remove the package from your local repository and remove any configuration files that are associated with it.

Note that this will not remove AutoKey's dependencies and will not remove anything from your Home directory, which is where your AutoKey data is stored. Only configuration files that are outside of your HOME directory (like in the `/usr/share` directory or the `/etc` directory) will be purged.

1. Open Konsole.
2. Type this command to purge the `autokey-common` configuration files:
   ```python
   sudo apt purge autokey-common
   ```
3. Read the output and press the **Enter** key or type `y` to accept the change or `n` to refuse the change.
4. Type this command to purge the `autokey-gtk` configuration files:
   ```python
   sudo apt purge autokey-gtk
   ```
5. Read the output and press the **Enter** key or type `y` to accept the change or `n` to refuse the change.
6. Type this command to purge the `autokey-qt` configuration files:
   ```python
   sudo apt purge autokey-qt
   ```
7. Read the output and press the **Enter** key or type `y` to accept the change or `n` to refuse the change.

Note that you can simulate these first to see what they would do without making any changes by adding -s to the commands, like this:
```python
sudo apt -s purge autokey-gtk
```

**Comment by josephj11** [comment]
@Elliria  Thanks for expanding on my answer.

It's a fine point/nit, but I would go with a `cp -a "$HOME/.config/autokey" "$HOME/Desktop/autokey-backup"`. It preserves symlinks. This is very unlikely to affect the OP, but I use a few in my setup.

Do you know if this is still a thing or can it be closed?

**Comment by Elliria** [comment]
Thanks. You're absolutely right. I updated it above and also noted it in my personal wiki.

I suppose it will be up to @Bigfootmech to decide if it's still a thing or not.

**Comment by Bigfootmech** [comment]
Thank you so much guys, and sorry for the wait!

Yup, deleting that folder, and purging worked

I managed to install 0.96.0 correctly afterwards

**Comment by Elliria** [comment]
That's great news. I'm glad it worked out.
