### ISSUE TITLE
Does not replace text in CLI on Deb12

### ISSUE THREAD

**Issue by basnyder** [autokey/autokey#962]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [X] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.1.0-26-amd64

### Which AutoKey GUI did you use?

None

### Which AutoKey version did you use?

0.96.0

### How did you install AutoKey?

sudo dpkg --install autokey-common_${VERSION}_all.deb autokey-gtk_${VERSION}_all.deb
sudo apt --fix-broken install

### Can you briefly describe the issue?

Autokey replacements work fine in browser or a text editor, but when I try to make a replacement in my command prompt, it removes the "abbreviation" but never replaces it with the right text

### Can the issue be reproduced?

None

### What are the steps to reproduce the issue?

1 Create a new "Phrase"
2 Set the abbreviation
3 Save
4 test phrase in text editor or command line to confirm it works
5 test phrase in command line and confirm it did not

### What should have happened?

abbreviation replaced with phrase

### What actually happened?

abbreviation removed but phrase not present

### Do you have screenshots?

<img width="595" alt="Screenshot 2024-11-06 at 11 10 02 AM" src="https://github.com/user-attachments/assets/c5a8842a-7f27-4069-b242-bea452385a3a">

https://github.com/user-attachments/assets/ea0aefb0-a492-463d-ba8d-7a7ff9331c4a

### Can you provide the output of the AutoKey command?

```bash
2024-11-06 11:11:33,845 INFO - autokey.service - Matched Phrase "getNonConstSLBlock()" having abbreviations "['someAbbr']" against current input
```

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #962</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @basnyder</code> (replace <code>20</code> with the amount, and <code>@basnyder</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by josephj11** [comment]
Welcome to the AutoKey community @basnyder !

This looks like a simple misunderstanding of how terminal programs work.

Terminals need to be able to send raw `Ctrl+C` and `Ctrl+V` (sometimes by having to type them twice). To accommodate this, they use `Ctrl+Shift+C` and `Ctrl+Shift+V` for copy and paste respectively.

AutoKey accommodates this by allowing you to choose Paste using Ctrl+Shift+V as an option for phrases.
(Your screenshot shows that this option was not selected.)

This fixes the original issue, but if your situation is more nuanced, keep reading.

If your phrase needs to work in both terminals and non-terminals, there are several ways to do that.

The simplest approach is to assign a window filter to your original phrase that matches the non-terminal windows where it will already work. Then, clone that phrase as a new phrase, but assign it a window filter that matches the terminal window(s) where it will work and change its Paste using option to `Ctrl+Shift+V`.

Because the two phrases use mutually exclusive window filters, they can both use the same trigger abbreviation(s) and hotkey.

If you want to have the original phrase work everywhere _except_ in your terminal, that's called a negative window filter. Unfortunately, that's hard to do. If you need that, then ask on [Gitter](https://gitter.im/autokey/autokey) where we can expand on how to get that to work.

Another alternative is two have two separate phrases each with unique triggers.

Yet another alternative is to write a script instead of a phrase and use our API call to get the window class and use that to decide which type of paste to do.

We can discuss all of this and anything else generally AutoKey related over on Gitter.

**Comment by josephj11** [comment]
If the above comment fixes this issue, please close this issue as completed.

**Comment by basnyder** [comment]
Using the "Paste using" value of "Clipboard" has resolved this issue
