### ISSUE TITLE
Bump Python versions in workflow files + replace asyncore

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#964]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [X] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Other terms that describe this issue if not provided above:

update

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

Update the Python versions in the [build.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/build.yml) file, and the [python-test.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/python-test.yml) file.

### Can the issue be reproduced?

None

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #964</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Elliria</code> (replace <code>20</code> with the amount, and <code>@Elliria</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by Elliria** [comment]
Although [**Python 3.12.7** is supported by GitHub in ubuntu-latest](https://github.com/actions/runner-images#available-images), we can't currently support it. The **asyncore** module is [deprecated in Python 3.12](https://docs.python.org/3.11/library/asyncore.html) and it's used by **pyinotify**, which is one of AutoKey's dependencies. I've reached out to the author of **pyinotify** for suggestions. Another possibility might be replacing pyinotify with something else, although such a change would be beyond my skill-level. Meanwhile, we'll be supporting **Python 3.9** through **Python 3.11**. Any help in sorting this out would be appreciated.

**Comment by BlueDrink9** [comment]
Ah, sorry, I misread the issue when I closed it earlier

**Comment by BlueDrink9** [comment]
Easiest option would probably be to plug 
https://pypi.org/project/pyasyncore/ into the dependencies in setup.py (and optionally insert the code to silence the warnings). I've seen other projects do this.

**Comment by josephj11** [comment]
@Elliria This issue and the previous one address changes in the upstream environment. The proposed label, "update", could be applied to anything. I think we have an upstream label which sort of applies. Maybe there should be an "environment" label for this sort of thing. 
I'm on my phone ATM and can't get into AutoKey with full permissions for some reason.

**Comment by Elliria** [comment]
I'm liking the idea of an "environment" label.

**Comment by Elliria** [comment]
I can't heart your addition of the **environment** label, @josephj11, so here's your heart: ♥️

**Comment by Elliria** [comment]
@dlk3 submitted a patch in a comment under issue #946 demonstrating how **pyasyncore** can be added to the `[testdev]` section of the `setup.cfg` file to solve the **asyncore** issue so that we can support **Python 3.12**.

I'm still not fully clear on exactly what, on the **master** branch is untouchable and what's not. My question here is where the change should be made. I believe `tox` gets its configuration from the **master** branch, so do we do it there, on the **develop** branch, both?

Also, do we need to worry about the warnings mentioned in [this PyPi page](https://pypi.org/project/pyasyncore/) for **Python 3.10** and **Python 3.11** when we do that? If so, would we insert the example block of code on that page into the top part of `setup.py` or would it go somewhere else?

**Comment by Elliria** [comment]
Issue #916 is related to this.

**Comment by josephj11** [comment]
@Elliria and @dlk3 This one's over my head. The goal is to clean up the sync problems between master and develop, so whatever works best for that is the way to go.

Ideally, I would like the master branch to be frozen when a release is generated, but when we last discussed this, it appeared that git/GitHub makes doing that largely impractical.

The question to answer is: what should a user get if they clone master? If they intend to debug a current production issue, but get code that has changed since the release, how serious a concern is that? ... 

I may be spinning wheels, but is there a way to leave master untouched by creating a patch or set of patches to it for changes that "have to be made", so a user could install it as released and then choose whether to apply the subsequent patches?

**Comment by dlk3** [comment]
> The question to answer is: what should a user get if they clone master? If they intend to debug a current production issue, but get code that has changed since the release, how serious a concern is that? ...

I would normally expect the master branch of a project to be the code under active development.  It may or may not build, test and/or execute successfully.  There is no guarantee.  Despite having that understanding, I'd expect that a project like AutoKey would not pull changes into its master branch until there had been at least some basic testing to make sure things still mostly worked.

To contribute to a project I'd normally fork my own of the repo and start from the master branch, as it exists when I start, expecting that it has the latest development code in it.  I'd make my own local development branch in my forked repo, make my changes there, test them using the tox tests, and then send you a pull request with those changes to be pulled into the master in the main repo.  (There wouldn't be any need for a "develop" branch in this scenario and I have to say that I don't fully understand the purpose of the one that's in the AutoKey repo.)

If I want to work with the code from a specific  production release I would create a new local branch for it in my forked repo, and do a git checkout into that branch of the hash that is given for the release on the [Releases page](https://github.com/autokey/autokey/releases).  That would give me the code as it existed back when the release was made.  I could do work in that branch and submit pull requests from it just as I did from my development branch above.

The git workflow for AutoKey has already been [documented in the AutoKey wiki](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet).  Those instructions should be updated to reflect whatever it is you guys ultimately decide to do.

**Comment by dlk3** [comment]
> I may be spinning wheels, but is there a way to leave master untouched by creating a patch or set of patches to it for changes that "have to be made", so a user could install it as released and then choose whether to apply the subsequent patches?

AutoKey needs to move to a more frequent release schedule, in my opinion.  As patches are made, make a new point release.  If different versions of the code are necessary for different environments, make the creation of those versions part of the release-building process.  Telling users to install an aged, stable release and then patch it from git is a recipe for disaster, in my opinion.

**Comment by dlk3** [comment]
> Also, do we need to worry about the warnings mentioned in [this PyPi page](https://pypi.org/project/pyasyncore/) for **Python 3.10** and **Python 3.11** when we do that? If so, would we insert the example block of code on that page into the top part of `setup.py` or would it go somewhere else?

Using this as the line in ```setup.cfg``` will make it so that the module is only installed during tox testing for python 3.12.0 or later:
```pyasyncore; python_version>='3.12'```

It is possible to have tox run the tests for multiple version of python at the same time by setting the ```env_list``` configuration option to the versions of python you want.  See https://tox.wiki/en/latest/config.html#setup-cfg

> I'm still not fully clear on exactly what, on the master branch is untouchable and what's not. My question here is where the change should be made. I believe tox gets its configuration from the master branch, so do we do it there, on the develop branch, both?

Whichever git branch you are switched into at the given moment is the only active one.  It's like the other one doesn't exist.  So when tox is run it gets its config from the setup.cfg as it exists in the active branch.  So, in this case, I'd suggest that you make these changes in the setup.cfg files in both branches, master and develop.

As I suggested in my other comments, if I was in charge of this project, I'd be looking to find the right time to merge the stuff that's in "develop" into "master" and do away with "develop".  Developers should be working in their own forked copies of your "official" repo, sending you pull requests when their code is ready in their repo asking you to pull their changes from their repo into the master branch in your "official" repo.  If you want to read more about standard practices for git workflows like this I'd recommend some of the [stuff on the Atlassian site](https://www.atlassian.com/git/tutorials/comparing-workflows).  The [Forking Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) described there seems to be pretty much the standard these days.  It's also the workflow described in the [AutoKey wiki](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet).

My best guess is that the "develop" branch is probably a relic from when there was only one developer/admin whose personal repo was the official repo.  They probably created the "develop" branch to do their development and testing in and then moved their finished changes into the master branch as they completed them.  Then, periodically, they would do a release of project code from the master branch to the public.  They'd then continue on working in the develop branch and pulling their changes into master until they were ready for the next release.  If someone else wanted to contribute code then they'd follow the procedure documented in the wiki to pull the new code from the contributor's forked copy of the repo into the master branch on the "official" repo.  If the contributor's code didn't work out for some reason, the admin could simply back the changes off in the master branch.

**Comment by josephj11** [comment]
@dlk3  Thanks for the detailed explanations!

OK. I misunderstood the development workflow. It's not my call because I'm not an AutoKey developer, but based on the above, I am in favor of merging anything useful from develop into master and getting rid of develop.

However, @sebastiansam55 made changes to the master that disabled or broke the X11 functionality (temporarily). If we go to a master only branch strategy, a change like that probably should not be merged in the future. It's OK if a new feature like this or a small issue doesn't quite work to start with, but it shouldn't break something else, especially something large.

Also, this merge  was done without review by anyone else, That may be OK for very small changes, but not for major ones.

Thoughts? (everyone)

**Comment by josephj11** [comment]
@dlk3 I support a more frequent release schedule. I opened #770 a discussion for 0.96.1 a long time ago. The problem is that we had and still have no one to merge and release anything. If it were up to me, I would have put out 0.96.1 as long as it had #600 in it.

**Comment by Elliria** [comment]
@josephj11:
> Ideally, I would like the master branch to be frozen when a release is generated, but when we last discussed this, it appeared that git/GitHub makes doing that largely impractical.

Actually, the more I learn about git, the more I like it. Every commit, every PR, and every tag is a frozen moment in time for AutoKey, so there doesn't seem to be a practical purpose to keeping a frozen branch. I'd love to hear some philosophy from folks who think having a frozen branch is a good idea so I could understand it, but from where I sit at the moment, it doesn't seem to benefit us in any way. In fact, it sometimes gets in the way.

> The question to answer is: what should a user get if they clone master?

If they use the `git clone https://github.com/autokey/autokey.git` command in a terminal window, they'll create the `autokey` subdirectory inside of the current directory and it will contain all branches of the current AutoKey code from the repository.

If they'd like to test out a specific release, they can follow that up by fetching all of AutoKey's tags with the `git fetch --all --tags --prune` command followed by checking out the specified release by using the **tags** prefix and the tag's name, as in this example of checking out the latest release: `git checkout tags/v0.96.0`

>If they intend to debug a current production issue, but get code that has changed since the release, how serious a concern is that? ...

Current production is the changed code, so that's fine.
 
> I may be spinning wheels, but is there a way to leave master untouched by creating a patch or set of patches to it for changes that "have to be made", so a user could install it as released and then choose whether to apply the subsequent patches?

No idea, but in our case, the workflows rely on the **master** branch, so **master** has to be updated from time to time. Hotfixes, when necessary, also get applied to the **master** branch.

**Comment by Elliria** [comment]
@dlk3:

Our project uses a variant of the **Git flow** strategy, which is one of the most difficult and frustrating strategies there are. See the [Branching strategies](https://github.com/autokey/autokey/discussions/823) discussion for a really interesting deep-dive (I can't recommend that video highly enough - grab a bucket of popcorn and enjoy). Your branching strategy is one of the least frustrating ones listed on that page. I just added a comment to the bottom of that page with my current understanding of our branching/workflow/release strategy.
 
> If I want to work with the code from a specific production release I would create a new local branch for it in my forked repo, and do a git checkout into that branch of the hash that is given for the release on the [Releases page](https://github.com/autokey/autokey/releases). That would give me the code as it existed back when the release was made. I could do work in that branch and submit pull requests from it just as I did from my development branch above.

That sounds good. I also just recently figured out that if you click the **master** button when you're in the **Code** tab of the AutoKey project on GitHub, you can open the **Tags** tab inside that drop-down menu and pick any release from that list to check out the release on GitHub. Very cool.
 
> The git workflow for AutoKey has already been [documented in the AutoKey wiki](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet). Those instructions should be updated to reflect whatever it is you guys ultimately decide to do.

Those were written by me and aren't necessarily correct. I've been trying to figure out our strategy, but I'm still very much a junior coder, so I've got a lot to learn. I'm always open to suggestions for how to get a better understanding or improve what's already there.

**Comment by Elliria** [comment]
@dlk3: 

> Using this as the line in `setup.cfg` will make it so that the module is only installed during tox testing for python 3.12.0 or later: `pyasyncore; python_version>='3.12'`

Perfect. Thank you.
 
> It is possible to have tox run the tests for multiple version of python at the same time by setting the `env_list` configuration option to the versions of python you want. See https://tox.wiki/en/latest/config.html#setup-cfg

I'm pretty sure it already does, but thanks for the link. I'm always interested in learning more.
 
> Whichever git branch you are switched into at the given moment is the only active one. It's like the other one doesn't exist. So when tox is run it gets its config from the setup.cfg as it exists in the active branch. So, in this case, I'd suggest that you make these changes in the setup.cfg files in both branches, master and develop.

Perfect. Is the same true for version updates in [setup.cfg](https://github.com/autokey/autokey/blob/master/setup.cfg) and [setup.py](https://github.com/autokey/autokey/blob/master/setup.py)? I'm about to be updating those, too.
 
> As I suggested in my other comments, if I was in charge of this project, I'd be looking to find the right time to merge the stuff that's in "develop" into "master" and do away with "develop". Developers should be working in their own forked copies of your "official" repo, sending you pull requests when their code is ready in their repo asking you to pull their changes from their repo into the master branch in your "official" repo.

It's a great idea. There's also the **beta** branch as part of the mess and it's required by a workflow, so it can't currently be deleted. And there are several feature branches still languishing in the code-base. I'd think that all of that should probably be sorted out before we make any major changes.

> If you want to read more about standard practices for git workflows like this I'd recommend some of the [stuff on the Atlassian site](https://www.atlassian.com/git/tutorials/comparing-workflows). The [Forking Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) described there seems to be pretty much the standard these days. It's also the workflow described in the [AutoKey wiki](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet).

Thank you for the link to more information about workflows. I'll check it out. And the cheat sheet is also my monster that I created as part of trying to learn how all of this works. Feel free to correct or improve that if you like. Anyone can edit the wiki.

**Comment by Elliria** [comment]
> However, @sebastiansam55 made changes to the master that disabled or broke the X11 functionality (temporarily).

That's happening on the **develop** branch.

> Also, this merge was done without review by anyone else, That may be OK for very small changes, but not for major ones.
> 
> Thoughts? (everyone)

That's a good idea.

**Comment by BlueDrink9** [comment]
(you could delete beta if you want. You wouldn't break anything; the relevant workflow will just never get run. You could always fix that in the future by creating a new branch called beta. The name that is the only thing that matters.)
